/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Room10-v1.glb -k -K -T -j -M 
Files: public/Room10-v1.glb [44.8MB] > Room10-v1-transformed.glb [9.51MB] (79%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MyRoom(props) {
	const { nodes, materials } = useGLTF("/Room10-v1-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Wooden_Shelf"
					geometry={nodes.Wooden_Shelf.geometry}
					material={materials["Pine Wood"]}
					position={[-1.632, 0.1, -3.695]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Text"
					geometry={nodes.Text.geometry}
					material={materials.outline}
					position={[0.677, 2.24, -1.988]}
					rotation={[Math.PI / 2, 0, Math.PI]}
				/>
				<mesh
					name="Table_Enterprise"
					geometry={nodes.Table_Enterprise.geometry}
					material={materials["Material.085"]}
					position={[-1.488, 0.092, 0.974]}
					rotation={[0, 1.571, 0]}
				/>
				<group name="SzobaFalak" position={[0, 0.1, 0]}>
					<mesh
						name="Plane044"
						geometry={nodes.Plane044.geometry}
						material={materials.Wall}
					/>
					<mesh
						name="Plane044_1"
						geometry={nodes.Plane044_1.geometry}
						material={materials.Floor}
					/>
					<mesh
						name="Plane044_2"
						geometry={nodes.Plane044_2.geometry}
						material={materials.Edges}
					/>
				</group>
				<group
					name="Plane013"
					position={[0.583, 1.917, -2.021]}
					rotation={[1.76, 0, Math.PI]}
				>
					<mesh
						name="Plane013_1"
						geometry={nodes.Plane013_1.geometry}
						material={materials.outline}
					/>
					<mesh
						name="Plane013_2"
						geometry={nodes.Plane013_2.geometry}
						material={materials["Material.001"]}
					/>
					<mesh
						name="Plane013_3"
						geometry={nodes.Plane013_3.geometry}
						material={materials["black skin"]}
					/>
					<mesh
						name="Plane013_4"
						geometry={nodes.Plane013_4.geometry}
						material={materials.Material}
					/>
					<mesh
						name="Plane013_5"
						geometry={nodes.Plane013_5.geometry}
						material={materials["black plactic"]}
					/>
					<mesh
						name="Plane013_6"
						geometry={nodes.Plane013_6.geometry}
						material={materials["metal.001"]}
					/>
				</group>
				<group
					name="Painting_with_frame001"
					position={[1.437, 3.154, -4.019]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube092"
						geometry={nodes.Cube092.geometry}
						material={materials["PORTA_TINTA.001"]}
					/>
					<mesh
						name="Cube092_1"
						geometry={nodes.Cube092_1.geometry}
						material={materials["Material.083"]}
					/>
					<mesh
						name="Cube092_2"
						geometry={nodes.Cube092_2.geometry}
						material={materials.quadro2_figura}
					/>
				</group>
				<group
					name="Painting_with_frame"
					position={[-4.013, 2.971, -1.007]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube091"
						geometry={nodes.Cube091.geometry}
						material={materials["PORTA_TINTA.001"]}
					/>
					<mesh
						name="Cube091_1"
						geometry={nodes.Cube091_1.geometry}
						material={materials.Carvalho}
					/>
					<mesh
						name="Cube091_2"
						geometry={nodes.Cube091_2.geometry}
						material={materials["Material.003"]}
					/>
				</group>
				<group name="Flowerke" position={[-0.548, 1.199, 0.133]}>
					<mesh
						name="NurbsPath006"
						geometry={nodes.NurbsPath006.geometry}
						material={materials["Material.051"]}
					/>
					<mesh
						name="NurbsPath006_1"
						geometry={nodes.NurbsPath006_1.geometry}
						material={materials["Material.040"]}
					/>
					<mesh
						name="NurbsPath006_2"
						geometry={nodes.NurbsPath006_2.geometry}
						material={materials.material}
					/>
					<mesh
						name="NurbsPath006_3"
						geometry={nodes.NurbsPath006_3.geometry}
						material={materials["Material.051"]}
					/>
					<mesh
						name="NurbsPath006_4"
						geometry={nodes.NurbsPath006_4.geometry}
						material={materials["Material.051"]}
					/>
					<mesh
						name="NurbsPath006_5"
						geometry={nodes.NurbsPath006_5.geometry}
						material={materials["Material.051"]}
					/>
					<mesh
						name="NurbsPath006_6"
						geometry={nodes.NurbsPath006_6.geometry}
						material={materials["Material.051"]}
					/>
					<mesh
						name="NurbsPath006_7"
						geometry={nodes.NurbsPath006_7.geometry}
						material={materials["Material.051"]}
					/>
				</group>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={materials["Mouse - Wheel Grey"]}
					position={[0.729, 0.092, -3.62]}
				/>
				<mesh
					name="Edges"
					geometry={nodes.Edges.geometry}
					material={materials["Edges.001"]}
					position={[0, 0.1, 0]}
				/>
				<group name="Clock_alarm_dekad" position={[-1.843, 1.066, -3.756]}>
					<mesh
						name="prop_clock_alarm_ikea_dekad"
						geometry={nodes.prop_clock_alarm_ikea_dekad.geometry}
						material={materials["Clock body"]}
					/>
					<mesh
						name="prop_clock_alarm_ikea_dekad_1"
						geometry={nodes.prop_clock_alarm_ikea_dekad_1.geometry}
						material={materials["clock chrome"]}
					/>
					<mesh
						name="prop_clock_alarm_ikea_dekad_2"
						geometry={nodes.prop_clock_alarm_ikea_dekad_2.geometry}
						material={materials["clock dial"]}
					/>
					<mesh
						name="prop_clock_alarm_ikea_dekad_3"
						geometry={nodes.prop_clock_alarm_ikea_dekad_3.geometry}
						material={materials["clock glass"]}
					/>
				</group>
				<group name="CACTUS" position={[0.264, 0.338, 0]}>
					<mesh
						name="Cylinder020"
						geometry={nodes.Cylinder020.geometry}
						material={materials["Material.053"]}
					/>
					<mesh
						name="Cylinder020_1"
						geometry={nodes.Cylinder020_1.geometry}
						material={materials["Material.052"]}
					/>
					<mesh
						name="Cylinder020_2"
						geometry={nodes.Cylinder020_2.geometry}
						material={materials["Material.054"]}
					/>
					<mesh
						name="Cylinder020_3"
						geometry={nodes.Cylinder020_3.geometry}
						material={materials["Material.055"]}
					/>
				</group>
				<mesh
					name="Cylinder"
					geometry={nodes.Cylinder.geometry}
					material={nodes.Cylinder.material}
					position={[-1.61, 0.746, 0.978]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={[-0.054, -0.001, -0.054]}
				/>
				<group
					name="macBook_TopPart"
					position={[-0.435, 0.374, -4.282]}
					rotation={[1.484, 0, Math.PI]}
					scale={[1.572, 0.03, 1.433]}
				>
					<mesh
						name="Cube001_1"
						geometry={nodes.Cube001_1.geometry}
						material={materials.Outline}
					/>
					<mesh
						name="Cube001_2"
						geometry={nodes.Cube001_2.geometry}
						material={materials.Screen}
					/>
					<mesh
						name="Cube001_3"
						geometry={nodes.Cube001_3.geometry}
						material={materials.Base}
					/>
					<mesh
						name="Cube001_4"
						geometry={nodes.Cube001_4.geometry}
						material={materials.Base}
					/>
					<mesh
						name="Cube001_5"
						geometry={nodes.Cube001_5.geometry}
						material={materials.Main}
					/>
					<mesh
						name="Cube001_6"
						geometry={nodes.Cube001_6.geometry}
						material={materials.Text}
					/>
					<mesh
						name="Cube001_7"
						geometry={nodes.Cube001_7.geometry}
						material={materials.Camera}
					/>
					<mesh
						name="Cube001_8"
						geometry={nodes.Cube001_8.geometry}
						material={materials.Camera1}
					/>
					<mesh
						name="Cube001_9"
						geometry={nodes.Cube001_9.geometry}
						material={materials.CameraGreen}
					/>
				</group>
				<group
					name="macBook_BottomPart"
					position={[1.398, 0.355, -2.86]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={[1.57, 0.032, 1.429]}
				>
					<mesh
						name="Cube003"
						geometry={nodes.Cube003.geometry}
						material={materials.Main}
					/>
					<mesh
						name="Cube003_1"
						geometry={nodes.Cube003_1.geometry}
						material={materials.Base}
					/>
					<mesh
						name="Cube003_2"
						geometry={nodes.Cube003_2.geometry}
						material={materials.Second}
					/>
					<mesh
						name="Cube003_3"
						geometry={nodes.Cube003_3.geometry}
						material={materials.KeysMain}
					/>
					<mesh
						name="Cube003_4"
						geometry={nodes.Cube003_4.geometry}
						material={materials["Material.001"]}
					/>
					<mesh
						name="Cube003_5"
						geometry={nodes.Cube003_5.geometry}
						material={materials.DarkGrey}
					/>
				</group>
				<group
					name="Monitor"
					position={[0, -0.095, 0]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube"
						geometry={nodes.Cube.geometry}
						material={materials.Glossy_material}
					/>
					<mesh
						name="Cube_1"
						geometry={nodes.Cube_1.geometry}
						material={materials["Screen.001"]}
					/>
					<mesh
						name="Cube_2"
						geometry={nodes.Cube_2.geometry}
						material={materials.White_diff}
					/>
					<mesh
						name="Cube_3"
						geometry={nodes.Cube_3.geometry}
						material={materials.Steel}
					/>
				</group>
				<group name="body" position={[-1.615, 0.706, 0.938]}>
					<mesh
						name="Cube100"
						geometry={nodes.Cube100.geometry}
						material={materials.veneer}
					/>
					<mesh
						name="Cube100_1"
						geometry={nodes.Cube100_1.geometry}
						material={materials["veneer (side)"]}
					/>
				</group>
				<mesh
					name="engine"
					geometry={nodes.engine.geometry}
					material={materials["black glossy"]}
					position={[-1.613, 0.717, 0.977]}
				/>
				<mesh
					name="thorn"
					geometry={nodes.thorn.geometry}
					material={materials["grungy metal"]}
					position={[-1.613, 0.732, 0.977]}
				/>
				<group name="tuning_handle_1" position={[-1.529, 0.732, 0.724]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
				<group name="tuning_handle_2" position={[-1.486, 0.732, 0.724]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
				<mesh
					name="dust_cover"
					geometry={nodes.dust_cover.geometry}
					position={[-1.826, 0.712, 0.938]}
					rotation={[0, 0, 0.891]}
				>
					<meshStandardMaterial
						color={"#a7c7cb"}
						transparent={true}
						opacity={0.8}
					/>
				</mesh>
				<mesh
					name="fastening_2"
					geometry={nodes.fastening_2.geometry}
					material={materials["grungy metal"]}
					position={[-1.826, 0.712, 0.938]}
					rotation={[-Math.PI / 2, 0.68, Math.PI / 2]}
				/>
				<mesh
					name="legs"
					geometry={nodes.legs.geometry}
					material={materials["black glossy"]}
					position={[-1.615, 0.64, 0.938]}
				/>
				<mesh
					name="pickup001"
					geometry={nodes.pickup001.geometry}
					material={materials["black matte"]}
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<group
					name="pickup003"
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cylinder059"
						geometry={nodes.Cylinder059.geometry}
						material={materials["grungy metal"]}
					/>
					<mesh
						name="Cylinder059_1"
						geometry={nodes.Cylinder059_1.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						name="Cylinder059_2"
						geometry={nodes.Cylinder059_2.geometry}
						material={materials["pink plastik"]}
					/>
				</group>
				<mesh
					name="piece"
					geometry={nodes.piece.geometry}
					material={materials["black glossy"]}
					position={[-1.716, 0.724, 0.755]}
				/>
				<group name="vinyl_plate" position={[-1.613, 0.733, 0.977]}>
					<mesh
						name="Cylinder056"
						geometry={nodes.Cylinder056.geometry}
						material={materials["Vinyl disc"]}
					/>
					<mesh
						name="Cylinder056_1"
						geometry={nodes.Cylinder056_1.geometry}
						material={materials["Material.019"]}
					/>
				</group>
				<mesh
					name="Cabinet_cover"
					geometry={nodes.Cabinet_cover.geometry}
					material={materials["Pine Wood"]}
					position={[-3.674, 0.229, 1.163]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet1"
					geometry={nodes.Cabinet1.geometry}
					material={materials.ceramic}
					position={[-3.948, 0.244, 2.5]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet2"
					geometry={nodes.Cabinet2.geometry}
					material={materials.ceramic}
					position={[-3.948, 0.244, 1.608]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet3"
					geometry={nodes.Cabinet3.geometry}
					material={materials.ceramic}
					position={[-3.948, 0.244, 0.717]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="legs003"
					geometry={nodes.legs003.geometry}
					material={materials["wood (Oak Matt Antracite Gray)"]}
					position={[-3.882, 0.181, 2.294]}
					rotation={[Math.PI / 2, 1.416, -1.806]}
				/>
				<group
					name="TV"
					position={[-3.703, 1.251, 1.163]}
					rotation={[0, Math.PI / 2, 0]}
				>
					<mesh
						name="TV_1"
						geometry={nodes.TV_1.geometry}
						material={materials.frame}
					/>
					<mesh
						name="TV_2"
						geometry={nodes.TV_2.geometry}
						material={materials.tv}
					/>
				</group>
				<mesh
					name="tv_legs"
					geometry={nodes.tv_legs.geometry}
					material={materials.frame}
					position={[-3.728, 0.639, 1.833]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<group
					name="microphone"
					position={[-0.39, 1.122, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane131"
						geometry={nodes.Plane131.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane131_1"
						geometry={nodes.Plane131_1.geometry}
						material={materials["Material.045"]}
					/>
					<mesh
						name="Plane131_2"
						geometry={nodes.Plane131_2.geometry}
						material={materials["plastic grey"]}
					/>
					<mesh
						name="Plane131_3"
						geometry={nodes.Plane131_3.geometry}
						material={materials["Metal Wire Mesh"]}
					/>
					<mesh
						name="Plane131_4"
						geometry={nodes.Plane131_4.geometry}
						material={materials["Fabric 02"]}
					/>
					<mesh
						name="Plane131_5"
						geometry={nodes.Plane131_5.geometry}
						material={materials["Material.046"]}
					/>
				</group>
				<group
					name="microphone_table_holder"
					position={[-0.39, 1.142, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane130"
						geometry={nodes.Plane130.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane130_1"
						geometry={nodes.Plane130_1.geometry}
						material={materials["Material.045"]}
					/>
				</group>
				<group
					name="Cube001"
					position={[-1.206, 0.64, 0.78]}
					rotation={[-Math.PI, 0.962, -Math.PI]}
				>
					<mesh
						name="Cube019"
						geometry={nodes.Cube019.geometry}
						material={materials["gamepad_base.001"]}
					/>
					<mesh
						name="Cube019_1"
						geometry={nodes.Cube019_1.geometry}
						material={materials["gamepad_color.001"]}
					/>
					<mesh
						name="Cube019_2"
						geometry={nodes.Cube019_2.geometry}
						material={materials["gamepad_light.001"]}
					/>
					<mesh
						name="Cube019_3"
						geometry={nodes.Cube019_3.geometry}
						material={materials["gamepad_metal.001"]}
					/>
					<mesh
						name="Cube019_4"
						geometry={nodes.Cube019_4.geometry}
						material={materials["gamepad_screen.001"]}
					/>
					<mesh
						name="Cube019_5"
						geometry={nodes.Cube019_5.geometry}
						material={materials["gamepad_button r.001"]}
					/>
					<mesh
						name="Cube019_6"
						geometry={nodes.Cube019_6.geometry}
						material={materials["gamepad_logo.001"]}
					/>
				</group>
				<group
					name="Cube006"
					position={[-1.206, 0.64, 1.015]}
					rotation={[0, 1.513, 0]}
				>
					<mesh
						name="Cube022"
						geometry={nodes.Cube022.geometry}
						material={materials["gamepad_base.001"]}
					/>
					<mesh
						name="Cube022_1"
						geometry={nodes.Cube022_1.geometry}
						material={materials["gamepad_color.001"]}
					/>
					<mesh
						name="Cube022_2"
						geometry={nodes.Cube022_2.geometry}
						material={materials["gamepad_light.001"]}
					/>
					<mesh
						name="Cube022_3"
						geometry={nodes.Cube022_3.geometry}
						material={materials["gamepad_metal.001"]}
					/>
					<mesh
						name="Cube022_4"
						geometry={nodes.Cube022_4.geometry}
						material={materials["gamepad_screen.001"]}
					/>
					<mesh
						name="Cube022_5"
						geometry={nodes.Cube022_5.geometry}
						material={materials["gamepad_button r.001"]}
					/>
					<mesh
						name="Cube022_6"
						geometry={nodes.Cube022_6.geometry}
						material={materials["gamepad_logo.001"]}
					/>
				</group>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={materials["Pine Wood"]}
					position={[0.729, 0.092, -3.62]}
				/>
				<group
					name="Cube067"
					position={[-1.232, 1.182, -3.744]}
					rotation={[1.573, -0.183, -1.563]}
				>
					<mesh
						name="Cube010"
						geometry={nodes.Cube010.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube010_1"
						geometry={nodes.Cube010_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube068"
					position={[-1.214, 1.185, -3.744]}
					rotation={[1.572, -0.181, -1.562]}
				>
					<mesh
						name="Cube009"
						geometry={nodes.Cube009.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube009_1"
						geometry={nodes.Cube009_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube069"
					position={[-1.254, 1.186, -3.742]}
					rotation={[1.572, -0.184, -1.563]}
				>
					<mesh
						name="Cube006_1"
						geometry={nodes.Cube006_1.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube006_2"
						geometry={nodes.Cube006_2.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube070"
					position={[-1.365, 1.177, -3.741]}
					rotation={[1.565, -0.343, -1.566]}
				>
					<mesh
						name="Cube004"
						geometry={nodes.Cube004.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube004_1"
						geometry={nodes.Cube004_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube071"
					position={[-1.345, 1.182, -3.747]}
					rotation={[1.574, -0.339, -1.563]}
				>
					<mesh
						name="Cube014"
						geometry={nodes.Cube014.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube014_1"
						geometry={nodes.Cube014_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube072"
					position={[-1.292, 1.164, -3.751]}
					rotation={[1.575, -0.323, -1.563]}
				>
					<mesh
						name="Cube008"
						geometry={nodes.Cube008.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube008_1"
						geometry={nodes.Cube008_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube073"
					position={[-1.304, 1.18, -3.746]}
					rotation={[1.571, -0.337, -1.564]}
				>
					<mesh
						name="Cube013"
						geometry={nodes.Cube013.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube013_1"
						geometry={nodes.Cube013_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube074"
					position={[-1.322, 1.18, -3.742]}
					rotation={[1.573, -0.338, -1.564]}
				>
					<mesh
						name="Cube012"
						geometry={nodes.Cube012.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube012_1"
						geometry={nodes.Cube012_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<group
					name="Cube075"
					position={[-1.391, 1.171, -3.739]}
					rotation={[1.573, -0.44, -1.564]}
				>
					<mesh
						name="Cube011"
						geometry={nodes.Cube011.geometry}
						material={materials["book cover"]}
					/>
					<mesh
						name="Cube011_1"
						geometry={nodes.Cube011_1.geometry}
						material={materials["stacked paper"]}
					/>
				</group>
				<mesh
					name="CoffeeTable"
					geometry={nodes.CoffeeTable.geometry}
					material={materials["Material.085"]}
					position={[1.465, 0.092, 1.031]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane"
					geometry={nodes.Plane.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane001"
					geometry={nodes.Plane001.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane002"
					geometry={nodes.Plane002.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane003"
					geometry={nodes.Plane003.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane004"
					geometry={nodes.Plane004.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane005"
					geometry={nodes.Plane005.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane006"
					geometry={nodes.Plane006.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane007"
					geometry={nodes.Plane007.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane010"
					geometry={nodes.Plane010.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane011"
					geometry={nodes.Plane011.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 1.127]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane016"
					geometry={nodes.Plane016.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane017"
					geometry={nodes.Plane017.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane018"
					geometry={nodes.Plane018.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane019"
					geometry={nodes.Plane019.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane020"
					geometry={nodes.Plane020.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane021"
					geometry={nodes.Plane021.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane025"
					geometry={nodes.Plane025.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.85]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane028"
					geometry={nodes.Plane028.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="Plane030"
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Plane008"
						geometry={nodes.Plane008.geometry}
						material={materials["Wood.001"]}
					/>
					<mesh
						name="Plane008_1"
						geometry={nodes.Plane008_1.geometry}
						material={materials["Material.002"]}
					/>
				</group>
				<mesh
					name="ладья"
					geometry={nodes.ладья.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья001"
					geometry={nodes.ладья001.geometry}
					material={materials["Material.002"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья002"
					geometry={nodes.ладья002.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья003"
					geometry={nodes.ладья003.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Bed_low"
					geometry={nodes.Bed_low.geometry}
					material={materials.Base}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Cover_low"
					geometry={nodes.Cover_low.geometry}
					material={nodes.Cover_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Pillow1_low"
					geometry={nodes.Pillow1_low.geometry}
					material={nodes.Pillow1_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Pillow2_low"
					geometry={nodes.Pillow2_low.geometry}
					material={nodes.Pillow2_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure1_low001"
					geometry={nodes.Structure1_low001.geometry}
					material={nodes.Structure1_low001.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure2_low"
					geometry={nodes.Structure2_low.geometry}
					material={nodes.Structure2_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure3_low"
					geometry={nodes.Structure3_low.geometry}
					material={nodes.Structure3_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="BODY"
					geometry={nodes.BODY.geometry}
					material={materials["Gray white plastic"]}
					position={[0.575, 0.954, -3.404]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<group name="BUTTON" position={[0.575, 0.954, -3.404]}>
					<mesh
						name="Circle002"
						geometry={nodes.Circle002.geometry}
						material={materials["grungy metal"]}
					/>
					<mesh
						name="Circle002_1"
						geometry={nodes.Circle002_1.geometry}
						material={materials["Material.057"]}
					/>
				</group>
				<mesh
					name="KEYS"
					geometry={nodes.KEYS.geometry}
					material={materials["Material.056"]}
					position={[0.575, 0.954, -3.404]}
					rotation={[0.111, 0, 0]}
				/>
				<group
					name="Base"
					position={[1.02, 0.957, -3.429]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cube007"
						geometry={nodes.Cube007.geometry}
						material={materials["Mouse - Shiny Grey"]}
					/>
					<mesh
						name="Cube007_1"
						geometry={nodes.Cube007_1.geometry}
						material={materials["Mouse - Mat Grey"]}
					/>
				</group>
				<mesh
					name="Top"
					geometry={nodes.Top.geometry}
					material={materials["Mouse - Mat Grey"]}
					position={[1.02, 0.969, -3.431]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Wheel"
					geometry={nodes.Wheel.geometry}
					material={materials["Mouse - Wheel Grey"]}
					position={[1.02, 0.964, -3.469]}
					rotation={[1.267, 0, -Math.PI]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/Room10-v1-transformed.glb");
