/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/RoomUnderBakeTOGO.glb -k -K -T -j -M 
Files: public/RoomUnderBakeTOGO.glb [4.69MB] > RoomUnderBakeTOGO-transformed.glb [3.6MB] (23%)
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function ModelGO(props) {
	const { nodes, materials } = useGLTF("/RoomUnderBakeTOGO-transformed.glb");
	const bakedTexture = useTexture("/static/Baked.jpg");
	bakedTexture.flipY = false;
	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Wooden_Shelf"
					geometry={nodes.Wooden_Shelf.geometry}
					material={nodes.Wooden_Shelf.material}
					position={[-1.632, 0.1, -3.695]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Text"
					geometry={nodes.Text.geometry}
					material={nodes.Text.material}
					position={[0.677, 2.24, -1.988]}
					rotation={[Math.PI / 2, 0, Math.PI]}
				/>
				<mesh
					name="Table_Enterprise"
					geometry={nodes.Table_Enterprise.geometry}
					material={nodes.Table_Enterprise.material}
					position={[-1.488, 0.092, 0.974]}
					rotation={[0, 1.571, 0]}
				/>
				<mesh
					name="SzobaFalak"
					geometry={nodes.SzobaFalak.geometry}
					material={nodes.SzobaFalak.material}
					position={[0, 0.1, 0]}
				/>
				<mesh
					name="Plane013"
					geometry={nodes.Plane013.geometry}
					material={nodes.Plane013.material}
					position={[0.583, 1.917, -2.021]}
					rotation={[1.76, 0, Math.PI]}
				/>
				<mesh
					name="Painting_with_frame001"
					geometry={nodes.Painting_with_frame001.geometry}
					material={nodes.Painting_with_frame001.material}
					position={[1.437, 3.154, -4.019]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="Painting_with_frame"
					geometry={nodes.Painting_with_frame.geometry}
					material={nodes.Painting_with_frame.material}
					position={[-4.013, 2.971, -1.007]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="Flowerke"
					geometry={nodes.Flowerke.geometry}
					material={nodes.Flowerke.material}
					position={[-0.548, 1.199, 0.133]}
				/>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={nodes.Floor_Laptop_Desk_80x40x45.material}
					position={[0.729, 0.092, -3.62]}
				/>
				<mesh
					name="Edges"
					geometry={nodes.Edges.geometry}
					material={nodes.Edges.material}
					position={[0, 0.1, 0]}
				/>
				<mesh
					name="Clock_alarm_dekad"
					geometry={nodes.Clock_alarm_dekad.geometry}
					material={nodes.Clock_alarm_dekad.material}
					position={[-1.843, 1.066, -3.756]}
				/>
				<mesh
					name="CACTUS"
					geometry={nodes.CACTUS.geometry}
					material={nodes.CACTUS.material}
					position={[0.264, 0.338, 0]}
				/>
				<mesh
					name="Cylinder"
					geometry={nodes.Cylinder.geometry}
					material={nodes.Cylinder.material}
					position={[-1.61, 0.746, 0.978]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={[-0.054, -0.001, -0.054]}
				/>
				<mesh
					name="macBook_TopPart"
					geometry={nodes.macBook_TopPart.geometry}
					material={nodes.macBook_TopPart.material}
					position={[-0.435, 0.371, -4.282]}
					rotation={[1.484, 0, Math.PI]}
					scale={[1.572, 0.03, 1.433]}
				/>
				<mesh
					name="macBook_BottomPart"
					geometry={nodes.macBook_BottomPart.geometry}
					material={nodes.macBook_BottomPart.material}
					position={[1.398, 0.341, -2.854]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={[1.57, 0.032, 1.429]}
				/>
				<mesh
					name="Monitor"
					geometry={nodes.Monitor.geometry}
					material={nodes.Monitor.material}
					position={[0, -0.095, 0]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="body"
					geometry={nodes.body.geometry}
					material={nodes.body.material}
					position={[-1.615, 0.706, 0.938]}
				/>
				<mesh
					name="engine"
					geometry={nodes.engine.geometry}
					material={nodes.engine.material}
					position={[-1.613, 0.717, 0.977]}
				/>
				<mesh
					name="thorn"
					geometry={nodes.thorn.geometry}
					material={nodes.thorn.material}
					position={[-1.613, 0.732, 0.977]}
				/>
				<mesh
					name="tuning_handle_1"
					geometry={nodes.tuning_handle_1.geometry}
					material={nodes.tuning_handle_1.material}
					position={[-1.529, 0.732, 0.724]}
				/>
				<mesh
					name="tuning_handle_2"
					geometry={nodes.tuning_handle_2.geometry}
					material={nodes.tuning_handle_2.material}
					position={[-1.486, 0.732, 0.724]}
				/>
				<mesh
					name="dust_cover"
					geometry={nodes.dust_cover.geometry}
					material={nodes.dust_cover.material}
					position={[-1.826, 0.712, 0.938]}
					rotation={[0, 0, 0.891]}
				/>
				<mesh
					name="fastening_2"
					geometry={nodes.fastening_2.geometry}
					material={nodes.fastening_2.material}
					position={[-1.826, 0.712, 0.938]}
					rotation={[-Math.PI / 2, 0.68, Math.PI / 2]}
				/>
				<mesh
					name="legs"
					geometry={nodes.legs.geometry}
					material={nodes.legs.material}
					position={[-1.615, 0.64, 0.938]}
				/>
				<mesh
					name="pickup001"
					geometry={nodes.pickup001.geometry}
					material={nodes.pickup001.material}
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<mesh
					name="pickup003"
					geometry={nodes.pickup003.geometry}
					material={nodes.pickup003.material}
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<mesh
					name="piece"
					geometry={nodes.piece.geometry}
					material={nodes.piece.material}
					position={[-1.716, 0.724, 0.755]}
				/>
				<mesh
					name="vinyl_plate"
					geometry={nodes.vinyl_plate.geometry}
					material={nodes.vinyl_plate.material}
					position={[-1.613, 0.733, 0.977]}
				/>
				<mesh
					name="Cabinet_cover"
					geometry={nodes.Cabinet_cover.geometry}
					material={nodes.Cabinet_cover.material}
					position={[-3.674, 0.229, 1.163]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet1"
					geometry={nodes.Cabinet1.geometry}
					material={nodes.Cabinet1.material}
					position={[-3.948, 0.244, 2.5]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet2"
					geometry={nodes.Cabinet2.geometry}
					material={nodes.Cabinet2.material}
					position={[-3.948, 0.244, 1.608]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cabinet3"
					geometry={nodes.Cabinet3.geometry}
					material={nodes.Cabinet3.material}
					position={[-3.948, 0.244, 0.717]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="legs003"
					geometry={nodes.legs003.geometry}
					material={nodes.legs003.material}
					position={[-3.882, 0.181, 2.294]}
					rotation={[Math.PI / 2, 1.416, -1.806]}
				/>
				<mesh
					name="TV"
					geometry={nodes.TV.geometry}
					material={nodes.TV.material}
					position={[-3.703, 1.251, 1.163]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="tv_legs"
					geometry={nodes.tv_legs.geometry}
					material={nodes.tv_legs.material}
					position={[-3.728, 0.639, 1.833]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="microphone"
					geometry={nodes.microphone.geometry}
					material={nodes.microphone.material}
					position={[-0.39, 1.122, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				/>
				<mesh
					name="microphone_table_holder"
					geometry={nodes.microphone_table_holder.geometry}
					material={nodes.microphone_table_holder.material}
					position={[-0.39, 1.142, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				/>
				<mesh
					name="Cube001"
					geometry={nodes.Cube001.geometry}
					material={nodes.Cube001.material}
					position={[-1.206, 0.64, 0.78]}
					rotation={[-Math.PI, 0.962, -Math.PI]}
				/>
				<mesh
					name="Cube006"
					geometry={nodes.Cube006.geometry}
					material={nodes.Cube006.material}
					position={[-1.206, 0.64, 1.015]}
					rotation={[0, 1.513, 0]}
				/>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={nodes.Plane014.material}
					position={[0.729, 0.092, -3.62]}
				/>
				<mesh
					name="Cube067"
					geometry={nodes.Cube067.geometry}
					material={nodes.Cube067.material}
					position={[-1.232, 1.182, -3.744]}
					rotation={[1.573, -0.183, -1.563]}
				/>
				<mesh
					name="Cube068"
					geometry={nodes.Cube068.geometry}
					material={nodes.Cube068.material}
					position={[-1.214, 1.185, -3.744]}
					rotation={[1.572, -0.181, -1.562]}
				/>
				<mesh
					name="Cube069"
					geometry={nodes.Cube069.geometry}
					material={nodes.Cube069.material}
					position={[-1.254, 1.186, -3.742]}
					rotation={[1.572, -0.184, -1.563]}
				/>
				<mesh
					name="Cube070"
					geometry={nodes.Cube070.geometry}
					material={nodes.Cube070.material}
					position={[-1.365, 1.177, -3.741]}
					rotation={[1.565, -0.343, -1.566]}
				/>
				<mesh
					name="Cube071"
					geometry={nodes.Cube071.geometry}
					material={nodes.Cube071.material}
					position={[-1.345, 1.182, -3.747]}
					rotation={[1.574, -0.339, -1.563]}
				/>
				<mesh
					name="Cube072"
					geometry={nodes.Cube072.geometry}
					material={nodes.Cube072.material}
					position={[-1.292, 1.164, -3.751]}
					rotation={[1.575, -0.323, -1.563]}
				/>
				<mesh
					name="Cube073"
					geometry={nodes.Cube073.geometry}
					material={nodes.Cube073.material}
					position={[-1.304, 1.18, -3.746]}
					rotation={[1.571, -0.337, -1.564]}
				/>
				<mesh
					name="Cube074"
					geometry={nodes.Cube074.geometry}
					material={nodes.Cube074.material}
					position={[-1.322, 1.18, -3.742]}
					rotation={[1.573, -0.338, -1.564]}
				/>
				<mesh
					name="Cube075"
					geometry={nodes.Cube075.geometry}
					material={nodes.Cube075.material}
					position={[-1.391, 1.171, -3.739]}
					rotation={[1.573, -0.44, -1.564]}
				/>
				<mesh
					name="CoffeeTable"
					geometry={nodes.CoffeeTable.geometry}
					position={[1.465, 0.092, 1.031]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<meshStandardMaterial map={bakedTexture} />
				</mesh>

				<mesh
					name="Plane"
					geometry={nodes.Plane.geometry}
					material={nodes.Plane.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane001"
					geometry={nodes.Plane001.geometry}
					material={nodes.Plane001.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane002"
					geometry={nodes.Plane002.geometry}
					material={nodes.Plane002.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane003"
					geometry={nodes.Plane003.geometry}
					material={nodes.Plane003.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane004"
					geometry={nodes.Plane004.geometry}
					material={nodes.Plane004.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane005"
					geometry={nodes.Plane005.geometry}
					material={nodes.Plane005.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane006"
					geometry={nodes.Plane006.geometry}
					material={nodes.Plane006.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane007"
					geometry={nodes.Plane007.geometry}
					material={nodes.Plane007.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane010"
					geometry={nodes.Plane010.geometry}
					material={nodes.Plane010.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane011"
					geometry={nodes.Plane011.geometry}
					material={nodes.Plane011.material}
					position={[1.451, 0.75, 1.127]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane016"
					geometry={nodes.Plane016.geometry}
					material={nodes.Plane016.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane017"
					geometry={nodes.Plane017.geometry}
					material={nodes.Plane017.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane018"
					geometry={nodes.Plane018.geometry}
					material={nodes.Plane018.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane019"
					geometry={nodes.Plane019.geometry}
					material={nodes.Plane019.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane020"
					geometry={nodes.Plane020.geometry}
					material={nodes.Plane020.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane021"
					geometry={nodes.Plane021.geometry}
					material={nodes.Plane021.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane025"
					geometry={nodes.Plane025.geometry}
					material={nodes.Plane025.material}
					position={[1.451, 0.75, 0.85]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane028"
					geometry={nodes.Plane028.geometry}
					material={nodes.Plane028.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane030"
					geometry={nodes.Plane030.geometry}
					material={nodes.Plane030.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья"
					geometry={nodes.ладья.geometry}
					material={nodes.ладья.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья001"
					geometry={nodes.ладья001.geometry}
					material={nodes.ладья001.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья002"
					geometry={nodes.ладья002.geometry}
					material={nodes.ладья002.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья003"
					geometry={nodes.ладья003.geometry}
					material={nodes.ладья003.material}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Bed_low"
					geometry={nodes.Bed_low.geometry}
					material={nodes.Bed_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Cover_low"
					geometry={nodes.Cover_low.geometry}
					material={nodes.Cover_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Pillow1_low"
					geometry={nodes.Pillow1_low.geometry}
					material={nodes.Pillow1_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Pillow2_low"
					geometry={nodes.Pillow2_low.geometry}
					material={nodes.Pillow2_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure1_low001"
					geometry={nodes.Structure1_low001.geometry}
					material={nodes.Structure1_low001.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure2_low"
					geometry={nodes.Structure2_low.geometry}
					material={nodes.Structure2_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="Structure3_low"
					geometry={nodes.Structure3_low.geometry}
					material={nodes.Structure3_low.material}
					position={[-3.282, 0.092, -2.665]}
				/>
				<mesh
					name="BODY"
					geometry={nodes.BODY.geometry}
					material={nodes.BODY.material}
					position={[0.575, 0.954, -3.404]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<mesh
					name="BUTTON"
					geometry={nodes.BUTTON.geometry}
					material={nodes.BUTTON.material}
					position={[0.575, 0.954, -3.404]}
				/>
				<mesh
					name="KEYS"
					geometry={nodes.KEYS.geometry}
					material={nodes.KEYS.material}
					position={[0.575, 0.954, -3.404]}
					rotation={[0.111, 0, 0]}
				/>
				<mesh
					name="Base"
					geometry={nodes.Base.geometry}
					material={nodes.Base.material}
					position={[1.02, 0.957, -3.429]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Top"
					geometry={nodes.Top.geometry}
					material={nodes.Top.material}
					position={[1.02, 0.969, -3.431]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Wheel"
					geometry={nodes.Wheel.geometry}
					material={nodes.Wheel.material}
					position={[1.02, 0.964, -3.469]}
					rotation={[1.267, 0, -Math.PI]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/RoomUnderBakeTOGO-transformed.glb");
