/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Roomversion1.glb -k -K 
*/

import React, { useRef } from "react";
import { Plane, useGLTF, useTexture } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";
import { editable as e } from "@theatre/r3f";
export function RoomVersion1(props) {
	const { nodes, materials } = useGLTF("/RoomVersion1.glb");
	const bakedTexture = useTexture("/static/decompressed.jpg");
	bakedTexture.flipY = false;

	const nbaTexture = useLoader(TextureLoader, "/static/nba.jpg");
	nbaTexture.flipY = false;

	const macbookScreen = useLoader(TextureLoader, "/static/macbookscreen.jpg");
	macbookScreen.flipY = false;

	const whitePiece = useLoader(TextureLoader, "/static/white.jpg");
	whitePiece.flipY = false;
	const blackPiece = useLoader(TextureLoader, "/static/black.jpg");
	blackPiece.flipY = false;
	const imageMirror = useLoader(TextureLoader, "/static/mirror.jpg");
	imageMirror.flipY = false;

	const graffiti = useLoader(TextureLoader, "/static/graffiti.jpg");
	graffiti.flipY = false;

	const vangogh = useLoader(TextureLoader, "/static/asdad.jpg");
	vangogh.flipY = false;
	const macbookKeyboard = useLoader(
		TextureLoader,
		"/static/macbookkeyboard.jpg"
	);
	macbookKeyboard.flipY = false;

	const computerScreen = useLoader(
		TextureLoader,
		"/static/computerscreen.jpg"
	);
	computerScreen.flipY = false;

	const computerKeyboard = useLoader(
		TextureLoader,
		"/static/computerkeyboard.jpg"
	);
	computerKeyboard.flipY = false;
	return (
		<group {...props} dispose={null}>
			<e.group name="Scene" theatreKey="Scene">
				<group name="Bed" position={[-3.67, 0.594, -2.665]}>
					<mesh
						name="Bed_low"
						geometry={nodes.Bed_low.geometry}
						material={nodes.Bed_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Cover_low"
						geometry={nodes.Cover_low.geometry}
						material={nodes.Cover_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Pillow1_low"
						geometry={nodes.Pillow1_low.geometry}
						material={nodes.Pillow1_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Pillow2_low"
						geometry={nodes.Pillow2_low.geometry}
						material={nodes.Pillow2_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Structure1_low001"
						geometry={nodes.Structure1_low001.geometry}
						material={nodes.Structure1_low001.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Structure2_low"
						geometry={nodes.Structure2_low.geometry}
						material={nodes.Structure2_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Structure3_low"
						geometry={nodes.Structure3_low.geometry}
						material={nodes.Structure3_low.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<group
					name="TV_set001"
					position={[-4.036, 0.602, 1.163]}
					rotation={[0, 1.571, 0]}
				>
					<group name="TV_CTRL" position={[0, 0.412, -0.036]}>
						<mesh
							name="TV001"
							geometry={nodes.TV001.geometry}
							material={nodes.TV001.material}
							position={[0, 0.612, 0]}
						>
							<mesh
								name="tv_legs001"
								geometry={nodes.tv_legs001.geometry}
								material={nodes.tv_legs001.material}
								position={[-0.67, -0.612, -0.025]}
							>
								<meshBasicMaterial map={bakedTexture} />
							</mesh>
						</mesh>
						<mesh
							name="TVSCREEN"
							geometry={nodes.TVSCREEN.geometry}
							material={nodes.TVSCREEN.material}
							position={[0, 0.612, 0]}
						>
							<meshBasicMaterial map={nbaTexture} />
						</mesh>
					</group>
				</group>
				<group
					name="XBOX2KAR"
					position={[-1.683, 1.143, 0.983]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cube006"
						geometry={nodes.Cube006.geometry}
						material={nodes.Cube006.material}
						position={[0, 0, -0.032]}
						rotation={[Math.PI, -1.513, Math.PI]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<group
					name="XBOX1KAR"
					position={[-1.682, 1.143, 0.734]}
					rotation={[Math.PI, -0.611, Math.PI]}
				>
					<mesh
						name="Cube001"
						geometry={nodes.Cube001.geometry}
						material={nodes.Cube001.material}
						position={[0, 0, -0.032]}
						rotation={[Math.PI, -1.513, Math.PI]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<group
					name="Vinyl_Player_41*33*12"
					position={[-2.093, 1.143, 0.938]}
				>
					<group
						name="cover_rotate"
						position={[-0.211, 0.072, 0]}
						rotation={[0, 0, 0.891]}
					>
						<mesh
							name="dust_cover"
							geometry={nodes.dust_cover.geometry}
							material={nodes.dust_cover.material}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
						<mesh
							name="fastening_2"
							geometry={nodes.fastening_2.geometry}
							material={nodes.fastening_2.material}
							rotation={[0, 1.571, 0]}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
					</group>
					<mesh
						name="body"
						geometry={nodes.body.geometry}
						material={nodes.body.material}
						position={[0, 0.066, 0]}
					>
						<meshBasicMaterial map={bakedTexture} />
						<mesh
							name="engine"
							geometry={nodes.engine.geometry}
							material={nodes.engine.material}
							position={[0.002, 0.011, 0.039]}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
						<mesh
							name="thorn"
							geometry={nodes.thorn.geometry}
							material={nodes.thorn.material}
							position={[0.002, 0.026, 0.039]}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
						<mesh
							name="tuning_handle_1"
							geometry={nodes.tuning_handle_1.geometry}
							material={nodes.tuning_handle_1.material}
							position={[0.087, 0.026, -0.213]}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
						<mesh
							name="tuning_handle_2"
							geometry={nodes.tuning_handle_2.geometry}
							material={nodes.tuning_handle_2.material}
							position={[0.13, 0.026, -0.213]}
						>
							<meshBasicMaterial map={bakedTexture} />
						</mesh>
					</mesh>
					<mesh
						name="legs"
						geometry={nodes.legs.geometry}
						material={nodes.legs.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="pickup001"
						geometry={nodes.pickup001.geometry}
						material={nodes.pickup001.material}
						position={[-0.181, 0.125, -0.162]}
						rotation={[0, 0, -Math.PI / 2]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<e.mesh
						theatreKey="VinylCylinder"
						name="pickup003"
						geometry={nodes.pickup003.geometry}
						// material={nodes.pickup003.material}
						position={[-0.181, 0.125, -0.162]}
						rotation={[0, 0, -Math.PI / 2]}
					>
						<meshStandardMaterial map={whitePiece} />
					</e.mesh>
					<mesh
						name="piece"
						geometry={nodes.piece.geometry}
						material={nodes.piece.material}
						position={[-0.101, 0.083, -0.183]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<e.mesh
						theatreKey="VinylPlate"
						name="vinyl_plate"
						geometry={nodes.vinyl_plate.geometry}
						material={nodes.vinyl_plate.material}
						position={[0.002, 0.093, 0.039]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</e.mesh>
				</group>
				<group
					name="Book001"
					position={[-2.08, 1.565, -3.823]}
					rotation={[-Math.PI, 0, 0]}
					scale={-1}
				>
					<mesh
						name="Cube002"
						geometry={nodes.Cube002.geometry}
						material={nodes.Cube002.material}
						position={[0.018, 0.197, 0.051]}
						rotation={[1.573, -0.44, -1.564]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<group name="Book" position={[-1.592, 1.565, -3.823]}>
					<mesh
						name="Cube075"
						geometry={nodes.Cube075.geometry}
						material={nodes.Cube075.material}
						position={[0.018, 0.197, 0.051]}
						rotation={[1.573, -0.44, -1.564]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<group name="Apple_Keyboard" position={[0.641, 1.459, -3.446]}>
					<mesh
						name="BODY"
						geometry={nodes.BODY.geometry}
						material={nodes.BODY.material}
						position={[-0.066, -0.002, 0.042]}
						rotation={[0, 0, -Math.PI / 2]}
					>
						<meshBasicMaterial color={"white"} />
					</mesh>
					<mesh
						name="BUTTON"
						geometry={nodes.BUTTON.geometry}
						material={nodes.BUTTON.material}
						position={[-0.066, -0.002, 0.042]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="KEYS"
						geometry={nodes.KEYS.geometry}
						material={nodes.KEYS.material}
						position={[-0.066, -0.002, 0.042]}
						rotation={[0.111, 0, 0]}
					>
						<meshBasicMaterial map={computerKeyboard} />
					</mesh>
				</group>
				<group
					name="Wireless_Mouse"
					position={[1.02, 1.44, -3.43]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Base"
						geometry={nodes.Base.geometry}
						material={nodes.Base.material}
						position={[0, 0.02, -0.001]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Top"
						geometry={nodes.Top.geometry}
						material={nodes.Top.material}
						position={[0, 0.031, 0.001]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
					<mesh
						name="Wheel"
						geometry={nodes.Wheel.geometry}
						material={nodes.Wheel.material}
						position={[0, 0.026, 0.039]}
						rotation={[1.875, 0, 0]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</group>
				<mesh
					name="SzobaFalak"
					geometry={nodes.SzobaFalak.geometry}
					material={nodes.SzobaFalak.material}
					position={[-0.437, 0.589, -0.074]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="Edges"
					geometry={nodes.Edges.geometry}
					material={nodes.Edges.material}
					position={[-0.432, 0.601, -0.066]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="Painting_with_frame"
					geometry={nodes.Painting_with_frame.geometry}
					material={nodes.Painting_with_frame.material}
					position={[-4.438, 3.529, -1.203]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="PAINTINGPICTURE"
					geometry={nodes.PAINTINGPICTURE.geometry}
					material={nodes.PAINTINGPICTURE.material}
					position={[-4.438, 3.529, -1.203]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<meshBasicMaterial map={imageMirror} />
				</mesh>
				<mesh
					name="Painting_with_frame001"
					geometry={nodes.Painting_with_frame001.geometry}
					material={nodes.Painting_with_frame001.material}
					position={[0.338, 3.529, -4.075]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				{/* <mesh
					name="PAINTINGPICTURE001"
					geometry={nodes.PAINTINGPICTURE001.geometry}
					material={nodes.PAINTINGPICTURE001.material}
					position={[0.338, 3.529, -4.075]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				>
					<meshBasicMaterial map={vangogh} />
				</mesh> */}

				<Plane
					position={[0.64, 3.529, -4.073]}
					// rotation={[Math.PI / 2, -Math.PI / 2, 0]}
					args={[0.7, 0.9]}
				>
					<meshBasicMaterial map={vangogh} />
				</Plane>
				<mesh
					name="Cabinet_cover"
					geometry={nodes.Cabinet_cover.geometry}
					material={nodes.Cabinet_cover.material}
					position={[-4.1, 0.608, 1.163]}
					rotation={[0, 1.571, 0]}
				>
					<meshBasicMaterial map={bakedTexture} />
					<mesh
						name="Cabinet3"
						geometry={nodes.Cabinet3.geometry}
						material={nodes.Cabinet3.material}
						position={[0.446, 0.015, -0.274]}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</mesh>
				<mesh
					name="Vinyl_table"
					geometry={nodes.Vinyl_table.geometry}
					material={nodes.Vinyl_table.material}
					position={[-1.966, 0.594, 0.974]}
					rotation={[0, 1.571, 0]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<e.mesh
					theatreKey="VinylGraffiti"
					name="Vinylfeher"
					geometry={nodes.Cylinder.geometry}
					material={nodes.Cylinder.material}
					position={[0, 1.82, 0]}
					rotation={[0, 0, 0]}
				>
					<meshBasicMaterial map={graffiti} />
				</e.mesh>
				<mesh
					name="CHESSASZTAL"
					geometry={nodes.CHESSASZTAL.geometry}
					material={nodes.CHESSASZTAL.material}
					position={[0.938, 0.592, 1.031]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="king000"
					geometry={nodes.king000.geometry}
					material={nodes.king000.material}
					position={[-4.622, 2.561, 0.273]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn000"
					geometry={nodes.Pawn000.geometry}
					material={nodes.Pawn000.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Rook003"
					geometry={nodes.Rook003.geometry}
					material={nodes.Rook003.material}
					position={[6.551, -0.886, -4.555]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Pawn001"
					geometry={nodes.Pawn001.geometry}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<e.mesh
					theatreKey="whiteKnight"
					name="RUYLOPEZKNIGHTWHITE"
					geometry={nodes.RUYLOPEZKNIGHTWHITE.geometry}
					material={nodes.RUYLOPEZKNIGHTWHITE.material}
					position={[6.327, 0.554, 1.043]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</e.mesh>
				<mesh
					name="queeen001"
					geometry={nodes.queeen001.geometry}
					material={nodes.queeen001.material}
					position={[6.548, 1.987, 0.275]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="bishop001"
					geometry={nodes.bishop001.geometry}
					material={nodes.bishop001.material}
					position={[6.539, 1.347, 1.055]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="king001"
					geometry={nodes.king001.geometry}
					material={nodes.king001.material}
					position={[6.548, 2.561, 1.892]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="bishop"
					geometry={nodes.bishop.geometry}
					material={nodes.bishop.material}
					position={[-4.65, -0.886, -1.027]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="queeen"
					geometry={nodes.queeen.geometry}
					material={nodes.queeen.material}
					position={[-4.65, -0.886, -1.027]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<e.mesh
					theatreKey="blackKnight"
					name="RUYLOPEZKNIGHT"
					geometry={nodes.RUYLOPEZKNIGHT.geometry}
					material={nodes.RUYLOPEZKNIGHT.material}
					position={[-4.65, -0.886, -2.87]}
				>
					<meshStandardMaterial roughness={1} color={"black"} />
				</e.mesh>
				<mesh
					name="Rook"
					geometry={nodes.Rook.geometry}
					material={nodes.Rook.material}
					position={[-4.65, -0.886, -4.523]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="board"
					geometry={nodes.board.geometry}
					material={nodes.board.material}
					position={[0.925, -0.942, 1.053]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="Pawn003"
					geometry={nodes.Pawn003.geometry}
					material={nodes.Pawn003.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn005"
					geometry={nodes.Pawn005.geometry}
					material={nodes.Pawn005.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn007"
					geometry={nodes.Pawn007.geometry}
					material={nodes.Pawn007.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<e.mesh
					theatreKey="blackPawn"
					name="RUYLOPEZPAWNBLACK"
					geometry={nodes.RUYLOPEZPAWNBLACK.geometry}
					material={nodes.RUYLOPEZPAWNBLACK.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</e.mesh>
				<mesh
					name="Pawn011"
					geometry={nodes.Pawn011.geometry}
					material={nodes.Pawn011.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn013"
					geometry={nodes.Pawn013.geometry}
					material={nodes.Pawn013.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn015"
					geometry={nodes.Pawn015.geometry}
					material={nodes.Pawn015.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Pawn006"
					geometry={nodes.Pawn006.geometry}
					material={nodes.Pawn006.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Pawn008"
					geometry={nodes.Pawn008.geometry}
					material={nodes.Pawn008.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Pawn014"
					geometry={nodes.Pawn014.geometry}
					material={nodes.Pawn014.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<e.mesh
					theatreKey="whitePawn1"
					name="RUYLOPEZPAWNWHITE"
					geometry={nodes.RUYLOPEZPAWNWHITE.geometry}
					material={nodes.RUYLOPEZPAWNWHITE.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</e.mesh>
				<mesh
					name="Pawn019"
					geometry={nodes.Pawn019.geometry}
					material={nodes.Pawn019.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Pawn020"
					geometry={nodes.Pawn020.geometry}
					material={nodes.Pawn020.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Pawn023"
					geometry={nodes.Pawn023.geometry}
					material={nodes.Pawn023.material}
					position={[4.955, 0.378, 1.098]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Knight002"
					geometry={nodes.Knight002.geometry}
					material={nodes.Knight002.material}
					position={[6.327, 0.554, 1.043]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshStandardMaterial map={whitePiece} />
				</mesh>
				<mesh
					name="Knight003"
					geometry={nodes.Knight003.geometry}
					material={nodes.Knight003.material}
					position={[-4.65, -0.886, -2.87]}
				>
					<meshStandardMaterial map={blackPiece} />
				</mesh>
				<mesh
					name="Flowerke"
					geometry={nodes.Flowerke.geometry}
					material={nodes.Flowerke.material}
					position={[-0.737, 2.799, 0.06]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="CACTUS"
					geometry={nodes.CACTUS.geometry}
					material={nodes.CACTUS.material}
					position={[0.092, 1.938, 0.017]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="Wall_Book_Shelf001"
					geometry={nodes.Wall_Book_Shelf001.geometry}
					material={nodes.Wall_Book_Shelf001.material}
					position={[-1.829, 0.594, -3.735]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={nodes.Floor_Laptop_Desk_80x40x45.material}
					position={[0.729, 0.594, -3.62]}
				>
					<mesh
						name="DeskLaptop"
						geometry={nodes.DeskLaptop.geometry}
						material={nodes.DeskLaptop.material}
					>
						<meshBasicMaterial map={bakedTexture} />
					</mesh>
				</mesh>
				<mesh
					name="macBook_BottomPart"
					geometry={nodes.macBook_BottomPart.geometry}
					material={nodes.macBook_BottomPart.material}
					position={[1.398, 0.843, -2.854]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="macBook_TopPart"
					geometry={nodes.macBook_TopPart.geometry}
					material={nodes.macBook_TopPart.material}
					position={[-0.435, 0.873, -4.282]}
					rotation={[1.484, 0, Math.PI]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="MACBOOKSCREEN"
					geometry={nodes.MACBOOKSCREEN.geometry}
					material={nodes.MACBOOKSCREEN.material}
					position={[-0.435, 0.873, -4.282]}
					rotation={[1.484, 0, Math.PI]}
				>
					<meshBasicMaterial map={macbookScreen} />
				</mesh>
				<mesh
					name="KEYBOARDMAC"
					geometry={nodes.KEYBOARDMAC.geometry}
					material={nodes.KEYBOARDMAC.material}
					position={[1.398, 0.843, -2.854]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<meshBasicMaterial map={macbookKeyboard} />
				</mesh>
				<mesh
					name="Monitor"
					geometry={nodes.Monitor.geometry}
					material={nodes.Monitor.material}
					position={[0, 0.408, 0]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<meshBasicMaterial map={bakedTexture} />
				</mesh>
				<mesh
					name="MonitorScreen"
					geometry={nodes.MonitorScreen.geometry}
					material={nodes.MonitorScreen.material}
					position={[0, 0.408, 0]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<meshBasicMaterial map={computerScreen} />
				</mesh>
			</e.group>
		</group>
	);
}

useGLTF.preload("/RoomVersion1.glb");
