/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/roomgood-v1.glb -T -K -k 
Files: public/roomgood-v1.glb [132.37MB] > roomgood-v1-transformed.glb [58.21MB] (56%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function PortfolioRoom(props) {
	const { nodes, materials } = useGLTF("/roomgood-v1-transformed.glb");

	const textureGlassMaterial = new THREE.MeshStandardMaterial({
		transparent: true,
		color: "lightgrey",
		opacity: 0.8,
	});
	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<group name="Plane015" position={[0, 0.1, 0]}>
					<mesh
						name="Plane044"
						geometry={nodes.Plane044.geometry}
						material={materials.Floor}
					/>
					<mesh
						name="Plane044_1"
						geometry={nodes.Plane044_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={materials["Black Powder Coating"]}
					position={[0.657, 0.1, -3.616]}
				/>
				<group name="TV_Unit" position={[-4.006, 0.1, 1.254]}>
					<mesh
						name="Cube036"
						geometry={nodes.Cube036.geometry}
						material={materials.PaletteMaterial024}
					/>
					<mesh
						name="Cube036_1"
						geometry={nodes.Cube036_1.geometry}
						material={materials["book covers"]}
					/>
				</group>
				<mesh
					name="Table_Enterprise"
					geometry={nodes.Table_Enterprise.geometry}
					material={materials["Material.085"]}
					position={[-2.516, 0.1, 0.847]}
					rotation={[0, 1.571, 0]}
				/>
				<group
					name="Picture_frame-01"
					position={[-3.717, 0.606, 0.789]}
					rotation={[0, 1.571, 0]}
				>
					<mesh
						name="Picture_frame-01_1"
						geometry={nodes["Picture_frame-01_1"].geometry}
						material={materials["Moldura de madeira.001"]}
					/>
					<mesh
						name="Picture_frame-01_2"
						geometry={nodes["Picture_frame-01_2"].geometry}
						material={materials["Moldura textura.003"]}
					/>
				</group>
				<group
					name="Painting_with_frame"
					position={[-4, 3.53, 1.548]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube091"
						geometry={nodes.Cube091.geometry}
						material={materials.Carvalho}
					/>
					<mesh
						name="Cube091_1"
						geometry={nodes.Cube091_1.geometry}
						material={materials.quadro_figura}
					/>
				</group>
				<mesh
					name="Painting_with_frame001"
					geometry={nodes.Painting_with_frame001.geometry}
					material={materials.quadro2_figura}
					position={[-0.337, 2.549, -4]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="Forty-two_books001"
					geometry={nodes["Forty-two_books001"].geometry}
					material={materials["Books.002"]}
					position={[-2.402, 0.975, -3.843]}
					rotation={[0, 1.571, 0]}
					scale={0.843}
				/>
				<group
					name="Monitor_MSI_Optix_MAG341CQ"
					position={[0.598, 0.777, -3.827]}
				>
					<mesh
						name="Cylinder007"
						geometry={nodes.Cylinder007.geometry}
						material={materials.Fuss_grau}
					/>
					<mesh
						name="Cylinder007_1"
						geometry={nodes.Cylinder007_1.geometry}
						material={materials.PaletteMaterial002}
					/>
					<mesh
						name="Cylinder007_2"
						geometry={nodes.Cylinder007_2.geometry}
						material={materials.PaletteMaterial003}
					/>
					<mesh
						name="Cylinder007_3"
						geometry={nodes.Cylinder007_3.geometry}
						material={materials.PaletteMaterial004}
					/>
					<mesh
						name="Cylinder007_4"
						geometry={nodes.Cylinder007_4.geometry}
						material={materials["Gehäuse_grau.Stecker"]}
					/>
					<mesh
						name="Cylinder007_5"
						geometry={nodes.Cylinder007_5.geometry}
						material={materials.Screen}
					/>
					<mesh
						name="Cylinder007_6"
						geometry={nodes.Cylinder007_6.geometry}
						material={materials.MSI_Grau_Back}
					/>
				</group>
				<group
					name="Cube021"
					position={[1.248, 0.778, -3.605]}
					rotation={[1.309, 0, 0]}
				>
					<mesh
						name="Cube016"
						geometry={nodes.Cube016.geometry}
						material={materials.screen}
					/>
					<mesh
						name="Cube016_1"
						geometry={nodes.Cube016_1.geometry}
						material={materials.PaletteMaterial006}
					/>
					<mesh
						name="Cube016_2"
						geometry={nodes.Cube016_2.geometry}
						material={materials.PaletteMaterial008}
					/>
					<mesh
						name="Cube016_3"
						geometry={nodes.Cube016_3.geometry}
						material={materials["Apple-logo"]}
					/>
					<mesh
						name="Cube016_4"
						geometry={nodes.Cube016_4.geometry}
						material={materials.PaletteMaterial009}
					/>
					<mesh
						name="Cube016_5"
						geometry={nodes.Cube016_5.geometry}
						material={materials["key.002"]}
					/>
					<mesh
						name="Cube016_6"
						geometry={nodes.Cube016_6.geometry}
						material={materials.PaletteMaterial010}
					/>
					<mesh
						name="Cube016_7"
						geometry={nodes.Cube016_7.geometry}
						material={materials.PaletteMaterial011}
					/>
					<mesh
						name="Cube016_8"
						geometry={nodes.Cube016_8.geometry}
						material={materials.PaletteMaterial005}
					/>
					<mesh
						name="Cube016_9"
						geometry={nodes.Cube016_9.geometry}
						material={materials.PaletteMaterial007}
					/>
				</group>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={materials["Pine Wood"]}
					position={[0.657, 0.1, -3.616]}
				/>
				<group name="Bluetooth" position={[0.683, 0.803, -3.464]}>
					<mesh
						name="Cube028"
						geometry={nodes.Cube028.geometry}
						material={materials.PaletteMaterial013}
					/>
					<mesh
						name="Cube028_1"
						geometry={nodes.Cube028_1.geometry}
						material={materials.PaletteMaterial015}
					/>
					<mesh
						name="Cube028_2"
						geometry={nodes.Cube028_2.geometry}
						material={materials.PaletteMaterial016}
					/>
					<mesh
						name="Cube028_3"
						geometry={nodes.Cube028_3.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cube028_4"
						geometry={nodes.Cube028_4.geometry}
						material={materials.PaletteMaterial014}
					/>
				</group>
				<mesh
					name="Vase"
					geometry={nodes.Vase.geometry}
					material={materials["Flower Vase_Color"]}
					position={[2.096, 0.1, -3.519]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="MouseThermaltakeBlack"
					geometry={nodes.MouseThermaltakeBlack.geometry}
					material={materials.PaletteMaterial017}
					position={[0.868, 0.792, -3.489]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack002"
					geometry={nodes.MouseThermaltakeBlack002.geometry}
					material={materials.PaletteMaterial018}
					position={[0.847, 0.791, -3.471]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="MouseThermaltakeBlack003"
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="MouseThermaltakeBlack003_1"
						geometry={nodes.MouseThermaltakeBlack003_1.geometry}
						material={materials.PaletteMaterial019}
					/>
					<mesh
						name="MouseThermaltakeBlack003_2"
						geometry={nodes.MouseThermaltakeBlack003_2.geometry}
						material={materials.PaletteMaterial020}
					/>
				</group>
				<mesh
					name="MouseThermaltakeBlack005"
					geometry={nodes.MouseThermaltakeBlack005.geometry}
					material={materials.PaletteMaterial021}
					position={[0.869, 0.777, -3.461]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack008"
					geometry={nodes.MouseThermaltakeBlack008.geometry}
					material={materials.PaletteMaterial022}
					position={[0.871, 0.792, -3.489]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack012"
					geometry={nodes.MouseThermaltakeBlack012.geometry}
					material={materials.PaletteMaterial023}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="Cube026"
					geometry={nodes.Cube026.geometry}
					material={materials["Outlet_White Plastic 2.004"]}
					position={[1.777, 0.877, -3.996]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="CoffeeTable"
					geometry={nodes.CoffeeTable.geometry}
					material={materials["beech wood"]}
					position={[1.495, 0.1, 1.462]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Horse_B8"
					geometry={nodes.Black_Horse_B8.geometry}
					material={materials.BlackHorse}
					position={[1.62, 0.648, 1.643]}
				/>
				<group
					name="Board"
					position={[1.482, 0.648, 1.45]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Plane"
						geometry={nodes.Plane.geometry}
						material={materials.White}
					/>
					<mesh
						name="Plane_1"
						geometry={nodes.Plane_1.geometry}
						material={materials.DarkWood}
					/>
				</group>
				<mesh
					name="White_Horse_B1"
					geometry={nodes.White_Horse_B1.geometry}
					material={materials.WhiteHorse}
					position={[1.62, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Cylinder008"
					geometry={nodes.Cylinder008.geometry}
					material={materials.PaletteMaterial025}
					position={[-2.417, 0.575, 1.241]}
					rotation={[0, 1.471, -2.546]}
				/>
				<group
					name="_MAIN_KEY002"
					position={[-2.336, 0.539, 0.956]}
					rotation={[-Math.PI, 0.262, -Math.PI]}
				>
					<mesh
						name="Cylinder072"
						geometry={nodes.Cylinder072.geometry}
						material={materials["ZenUV_Generic_Material.002"]}
					/>
					<mesh
						name="Cylinder072_1"
						geometry={nodes.Cylinder072_1.geometry}
						material={materials.PaletteMaterial026}
					/>
					<mesh
						name="Cylinder072_2"
						geometry={nodes.Cylinder072_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_3"
						geometry={nodes.Cylinder072_3.geometry}
						material={materials["TRIGGER BUTTONS "]}
					/>
					<mesh
						name="Cylinder072_4"
						geometry={nodes.Cylinder072_4.geometry}
						material={materials["dotted withe.001"]}
					/>
					<mesh
						name="Cylinder072_5"
						geometry={nodes.Cylinder072_5.geometry}
						material={materials["ZenUV_Generic_Material.006"]}
					/>
					<mesh
						name="Cylinder072_6"
						geometry={nodes.Cylinder072_6.geometry}
						material={materials["ZenUV_Generic_Material.004"]}
					/>
					<mesh
						name="Cylinder072_7"
						geometry={nodes.Cylinder072_7.geometry}
						material={materials["Material.075"]}
					/>
				</group>
				<group name="body" position={[-2.618, 0.591, 0.611]}>
					<mesh
						name="Cube100"
						geometry={nodes.Cube100.geometry}
						material={materials.veneer}
					/>
					<mesh
						name="Cube100_1"
						geometry={nodes.Cube100_1.geometry}
						material={materials["veneer (side)"]}
					/>
				</group>
				<mesh
					name="engine"
					geometry={nodes.engine.geometry}
					material={materials.PaletteMaterial027}
					position={[-2.616, 0.6, 0.642]}
				/>
				<mesh
					name="thorn"
					geometry={nodes.thorn.geometry}
					material={materials["grungy metal"]}
					position={[-2.616, 0.612, 0.642]}
				/>
				<mesh
					name="tuning_handle_1"
					geometry={nodes.tuning_handle_1.geometry}
					material={materials.PaletteMaterial028}
					position={[-2.549, 0.612, 0.44]}
				/>
				<mesh
					name="dust_cover"
					geometry={nodes.dust_cover.geometry}
					material={textureGlassMaterial}
					position={[-2.787, 0.596, 0.611]}
					rotation={[0, 0, 0.891]}
				/>
				<mesh
					name="vinyl_plate"
					geometry={nodes.vinyl_plate.geometry}
					material={materials.fabric}
					position={[-2.616, 0.613, 0.642]}
				/>
				<mesh
					name="01"
					geometry={nodes["01"].geometry}
					material={materials["01"]}
					position={[-1.361, 1.984, -3.94]}
					rotation={[-1.605, -0.104, 0.01]}
				/>
				<mesh
					name="Helix"
					geometry={nodes.Helix.geometry}
					material={materials.PaletteMaterial029}
					position={[-1.379, 2.086, -3.946]}
					rotation={[-1.588, -0.208, -1.573]}
				/>
				<mesh
					name="10"
					geometry={nodes["10"].geometry}
					material={materials["10"]}
					position={[-2.987, 1.979, -3.941]}
					rotation={[-1.571, 0.047, 0.005]}
				/>
				<mesh
					name="09"
					geometry={nodes["09"].geometry}
					material={materials["09"]}
					position={[-2.796, 1.952, -3.943]}
					rotation={[-Math.PI / 2, -0.002, 0]}
				/>
				<mesh
					name="08"
					geometry={nodes["08"].geometry}
					material={materials["08"]}
					position={[-2.617, 1.933, -3.939]}
					rotation={[-1.568, 0.145, 0.016]}
				/>
				<mesh
					name="07"
					geometry={nodes["07"].geometry}
					material={materials["07"]}
					position={[-2.447, 1.924, -3.938]}
					rotation={[-1.571, 0.036, 0.004]}
				/>
				<mesh
					name="06"
					geometry={nodes["06"].geometry}
					material={materials["06"]}
					position={[-2.272, 1.916, -3.938]}
					rotation={[-1.571, -0.019, -0.002]}
				/>
				<mesh
					name="05"
					geometry={nodes["05"].geometry}
					material={materials["05"]}
					position={[-2.108, 1.914, -3.937]}
					rotation={[-1.571, 0.048, 0.006]}
				/>
				<mesh
					name="04"
					geometry={nodes["04"].geometry}
					material={materials["04"]}
					position={[-1.928, 1.917, -3.943]}
					rotation={[-1.574, -0.039, 0.003]}
				/>
				<mesh
					name="03"
					geometry={nodes["03"].geometry}
					material={materials["03"]}
					position={[-1.755, 1.927, -3.944]}
					rotation={[-1.571, -0.018, -0.002]}
				/>
				<mesh
					name="02"
					geometry={nodes["02"].geometry}
					material={materials["02"]}
					position={[-1.556, 1.952, -3.937]}
					rotation={[-1.57, 0.097, 0.011]}
				/>
				<mesh
					name="Audio_Procesor"
					geometry={nodes.Audio_Procesor.geometry}
					material={materials["Electro Panel"]}
					position={[-3.676, 0.661, 2.085]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Camera_NUI"
					geometry={nodes.Camera_NUI.geometry}
					material={materials["Electro Panel"]}
					position={[-3.661, 0.661, 2.119]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverBottom"
					geometry={nodes.CoverBottom.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.628, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder028"
					geometry={nodes.Cylinder028.geometry}
					material={materials.PaletteMaterial026}
					position={[-3.642, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="LED"
					geometry={nodes.LED.geometry}
					material={materials.PaletteMaterial031}
					position={[-3.628, 0.659, 2.129]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Modem"
					geometry={nodes.Modem.geometry}
					material={materials.PaletteMaterial032}
					position={[-3.652, 0.659, 2.088]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Procesor"
					geometry={nodes.Procesor.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.668, 0.664, 2.141]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="basketball"
					geometry={nodes.basketball.geometry}
					material={materials.Basketball}
					position={[-1.183, 0.1, -3.67]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="microphone"
					position={[-0.238, 0.924, -3.625]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane131"
						geometry={nodes.Plane131.geometry}
						material={materials["Metal Wire Mesh"]}
					/>
					<mesh
						name="Plane131_1"
						geometry={nodes.Plane131_1.geometry}
						material={materials["Fabric 02"]}
					/>
					<mesh
						name="Plane131_2"
						geometry={nodes.Plane131_2.geometry}
						material={materials["Material.043"]}
					/>
				</group>
				<mesh
					name="ground_real002"
					geometry={nodes.ground_real002.geometry}
					material={materials["Mud and grass.001"]}
					position={[-2.011, 0.243, -3.847]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={0.075}
				/>
				<mesh
					name="succulent_plant002"
					geometry={nodes.succulent_plant002.geometry}
					material={materials["succulent material.001"]}
					position={[-2.011, 0.315, -3.847]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={1.405}
				/>
				<mesh
					name="AV40_Speaker_Left_DC_PLUG_female001"
					geometry={nodes.AV40_Speaker_Left_DC_PLUG_female001.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.212, 1.399, -3.869]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_plug001"
					geometry={nodes.AV40_Speaker_Left_Line_White_plug001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.159, 1.528, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Serial_number001"
					geometry={nodes.AV40_Speaker_Left_Serial_number001.geometry}
					material={materials["Material.104"]}
					position={[-2.185, 1.441, -3.874]}
					scale={1.125}
				/>
				<mesh
					name="AV40_Speaker_Right_Back003"
					geometry={nodes.AV40_Speaker_Right_Back003.geometry}
					material={materials["noir_back_left.001"]}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Grid002"
					geometry={nodes.AV40_Speaker_Right_Grid002.geometry}
					material={materials["Metal wire mesh.003"]}
					position={[-2.199, 1.492, -3.697]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Back002"
					geometry={nodes.AV40_Speaker_Right_Back002.geometry}
					material={materials["noir_back_right.001"]}
					position={[-1.857, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="twig001"
					position={[-2.253, 0.211, -3.752]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig003"
						geometry={nodes.twig003.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig003_1"
						geometry={nodes.twig003_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<mesh
					name="twig_fluffy002"
					geometry={nodes.twig_fluffy002.geometry}
					material={materials["flower.002"]}
					position={[-2.253, 0.211, -3.752]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="lod2001"
					geometry={nodes.lod2001.geometry}
					material={materials["baseball.001"]}
					position={[-1.706, 0.629, -3.789]}
					rotation={[-Math.PI, 0.007, -Math.PI]}
					scale={0.037}
				/>
				<mesh
					name="Alarm_Clock002"
					geometry={nodes.Alarm_Clock002.geometry}
					material={materials["Material.105"]}
					position={[-1.885, 0.665, -3.74]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={[0.066, 0.023, 0.066]}
				/>
				<instancedMesh
					args={[
						nodes.Phillips_Pan_Head_Screw033.geometry,
						materials["MI_screw_T.001"],
						34,
					]}
					name="Phillips_Pan_Head_Screw033"
					instanceMatrix={nodes.Phillips_Pan_Head_Screw033.instanceMatrix}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/roomgood-v1-transformed.glb");
