/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/roomsolutioncop2-v1.glb -T -j -K -k 
Files: public/roomsolutioncop2-v1.glb [132.08MB] > roomsolutioncop2-v1-transformed.glb [60.08MB] (55%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export function Room(props) {
	const { nodes, materials } = useGLTF("/roomsolutioncop2-v1-transformed.glb");
	const textureGlassMaterial = new THREE.MeshStandardMaterial({
		transparent: true,
		color: "lightgrey",
		opacity: 0.8,
	});
	console.log(materials);
	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<group name="Plane015" position={[0, 0.1, 0]}>
					<mesh
						name="Plane044_1"
						geometry={nodes.Plane044_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane044_2"
						geometry={nodes.Plane044_2.geometry}
						material={materials.Floor}
					/>
					<mesh
						name="Plane044_3"
						geometry={nodes.Plane044_3.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Edges"
					geometry={nodes.Edges.geometry}
					material={materials.PaletteMaterial001}
					position={[0, 0.1, 0]}
				/>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={materials["Black Powder Coating"]}
					position={[0.657, 0.1, -3.616]}
				/>
				<mesh
					name="Text"
					geometry={nodes.Text.geometry}
					material={materials.PaletteMaterial001}
					position={[0.616, 1.818, -2.31]}
					rotation={[Math.PI / 2, 0, Math.PI]}
				/>
				<group
					name="Plane013"
					position={[0.54, 1.56, -2.336]}
					rotation={[1.76, 0, Math.PI]}
				>
					<mesh
						name="Plane013_1"
						geometry={nodes.Plane013_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane013_2"
						geometry={nodes.Plane013_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane013_3"
						geometry={nodes.Plane013_3.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane013_4"
						geometry={nodes.Plane013_4.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane013_5"
						geometry={nodes.Plane013_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane013_6"
						geometry={nodes.Plane013_6.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Bean_Bag_chair"
					geometry={nodes.Bean_Bag_chair.geometry}
					material={materials.PaletteMaterial001}
					position={[1.499, 0.1, 0.293]}
					rotation={[0, 0.332, 0]}
				/>
				<mesh
					name="Bean_Bag_chair001"
					geometry={nodes.Bean_Bag_chair001.geometry}
					material={materials.PaletteMaterial001}
					position={[1.499, 0.1, 2.502]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group name="TV_Unit" position={[-4.006, 0.1, 1.254]}>
					<mesh
						name="Cube036_1"
						geometry={nodes.Cube036_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_2"
						geometry={nodes.Cube036_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_3"
						geometry={nodes.Cube036_3.geometry}
						material={materials.PaletteMaterial024}
					/>
					<mesh
						name="Cube036_4"
						geometry={nodes.Cube036_4.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_5"
						geometry={nodes.Cube036_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_6"
						geometry={nodes.Cube036_6.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_7"
						geometry={nodes.Cube036_7.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_8"
						geometry={nodes.Cube036_8.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_9"
						geometry={nodes.Cube036_9.geometry}
						material={materials["book covers"]}
					/>
					<mesh
						name="Cube036_10"
						geometry={nodes.Cube036_10.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube036_11"
						geometry={nodes.Cube036_11.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Table_Enterprise"
					geometry={nodes.Table_Enterprise.geometry}
					material={materials["Material.085"]}
					position={[-2.516, 0.1, 0.847]}
					rotation={[0, 1.571, 0]}
				/>
				<group
					name="Picture_frame-01"
					position={[-3.717, 0.606, 0.789]}
					rotation={[0, 1.571, 0]}
				>
					<mesh
						name="Picture_frame-01_1"
						geometry={nodes["Picture_frame-01_1"].geometry}
						material={materials["Moldura de madeira.001"]}
					/>
					<mesh
						name="Picture_frame-01_2"
						geometry={nodes["Picture_frame-01_2"].geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Picture_frame-01_3"
						geometry={nodes["Picture_frame-01_3"].geometry}
						material={materials["Moldura textura.003"]}
					/>
				</group>
				<group
					name="Painting_with_frame"
					position={[-4, 3.53, 1.548]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube091"
						geometry={nodes.Cube091.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube091_1"
						geometry={nodes.Cube091_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube091_2"
						geometry={nodes.Cube091_2.geometry}
						material={materials.Carvalho}
					/>
					<mesh
						name="Cube091_3"
						geometry={nodes.Cube091_3.geometry}
						material={materials.quadro_figura}
					/>
				</group>
				<group
					name="Painting_with_frame001"
					position={[-0.337, 2.549, -4]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube092"
						geometry={nodes.Cube092.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube092_1"
						geometry={nodes.Cube092_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube092_2"
						geometry={nodes.Cube092_2.geometry}
						material={materials.quadro2_figura}
					/>
				</group>
				<mesh
					name="Succulent_plant002"
					geometry={nodes.Succulent_plant002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.011, 0.208, -3.847]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={1.405}
				/>
				<mesh
					name="Indoor_potted_plant002"
					geometry={nodes.Indoor_potted_plant002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.253, 0.208, -3.752]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Forty-two_books001"
					geometry={nodes["Forty-two_books001"].geometry}
					material={materials["Books.002"]}
					position={[-2.402, 0.975, -3.843]}
					rotation={[0, 1.571, 0]}
					scale={0.843}
				/>
				<group
					name="Monitor_MSI_Optix_MAG341CQ"
					position={[0.598, 0.777, -3.827]}
				>
					<mesh
						name="Cylinder007"
						geometry={nodes.Cylinder007.geometry}
						material={materials.MSI_Grau_Back}
					/>
					<mesh
						name="Cylinder007_1"
						geometry={nodes.Cylinder007_1.geometry}
						material={materials.MSI_Grau_Back}
					/>
					<mesh
						name="Cylinder007_2"
						geometry={nodes.Cylinder007_2.geometry}
						material={materials.Fuss_grau}
					/>
					<mesh
						name="Cylinder007_3"
						geometry={nodes.Cylinder007_3.geometry}
						material={materials.PaletteMaterial002}
					/>
					<mesh
						name="Cylinder007_4"
						geometry={nodes.Cylinder007_4.geometry}
						material={materials.PaletteMaterial003}
					/>
					<mesh
						name="Cylinder007_5"
						geometry={nodes.Cylinder007_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_6"
						geometry={nodes.Cylinder007_6.geometry}
						material={materials.PaletteMaterial004}
					/>
					<mesh
						name="Cylinder007_7"
						geometry={nodes.Cylinder007_7.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_8"
						geometry={nodes.Cylinder007_8.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_9"
						geometry={nodes.Cylinder007_9.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_10"
						geometry={nodes.Cylinder007_10.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_11"
						geometry={nodes.Cylinder007_11.geometry}
						material={materials["Gehäuse_grau.Stecker"]}
					/>
					<mesh
						name="Cylinder007_12"
						geometry={nodes.Cylinder007_12.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder007_13"
						geometry={nodes.Cylinder007_13.geometry}
						material={materials.Screen}
					/>
				</group>
				<group
					name="Cube021"
					position={[1.248, 0.778, -3.605]}
					rotation={[1.309, 0, 0]}
				>
					<mesh
						name="Cube016"
						geometry={nodes.Cube016.geometry}
						material={materials.PaletteMaterial005}
					/>
					<mesh
						name="Cube016_1"
						geometry={nodes.Cube016_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube016_2"
						geometry={nodes.Cube016_2.geometry}
						material={materials.screen}
					/>
					<mesh
						name="Cube016_3"
						geometry={nodes.Cube016_3.geometry}
						material={materials.PaletteMaterial006}
					/>
					<mesh
						name="Cube016_4"
						geometry={nodes.Cube016_4.geometry}
						material={materials.PaletteMaterial007}
					/>
					<mesh
						name="Cube016_5"
						geometry={nodes.Cube016_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube016_6"
						geometry={nodes.Cube016_6.geometry}
						material={materials.PaletteMaterial008}
					/>
					<mesh
						name="Cube016_7"
						geometry={nodes.Cube016_7.geometry}
						material={materials.PaletteMaterial007}
					/>
					<mesh
						name="Cube016_8"
						geometry={nodes.Cube016_8.geometry}
						material={materials["Apple-logo"]}
					/>
					<mesh
						name="Cube016_9"
						geometry={nodes.Cube016_9.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube016_10"
						geometry={nodes.Cube016_10.geometry}
						material={materials.PaletteMaterial009}
					/>
					<mesh
						name="Cube016_11"
						geometry={nodes.Cube016_11.geometry}
						material={materials["key.002"]}
					/>
					<mesh
						name="Cube016_12"
						geometry={nodes.Cube016_12.geometry}
						material={materials.PaletteMaterial005}
					/>
					<mesh
						name="Cube016_13"
						geometry={nodes.Cube016_13.geometry}
						material={materials.PaletteMaterial010}
					/>
					<mesh
						name="Cube016_14"
						geometry={nodes.Cube016_14.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube016_15"
						geometry={nodes.Cube016_15.geometry}
						material={materials.PaletteMaterial011}
					/>
					<mesh
						name="Cube016_16"
						geometry={nodes.Cube016_16.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={materials["Pine Wood"]}
					position={[0.657, 0.1, -3.616]}
				/>
				<group name="Bluetooth" position={[0.683, 0.803, -3.464]}>
					<mesh
						name="Cube028"
						geometry={nodes.Cube028.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cube028_1"
						geometry={nodes.Cube028_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube028_2"
						geometry={nodes.Cube028_2.geometry}
						material={materials.PaletteMaterial013}
					/>
					<mesh
						name="Cube028_3"
						geometry={nodes.Cube028_3.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube028_4"
						geometry={nodes.Cube028_4.geometry}
						material={materials.PaletteMaterial014}
					/>
					<mesh
						name="Cube028_5"
						geometry={nodes.Cube028_5.geometry}
						material={materials.PaletteMaterial014}
					/>
					<mesh
						name="Cube028_6"
						geometry={nodes.Cube028_6.geometry}
						material={materials.PaletteMaterial015}
					/>
					<mesh
						name="Cube028_7"
						geometry={nodes.Cube028_7.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube028_8"
						geometry={nodes.Cube028_8.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube028_9"
						geometry={nodes.Cube028_9.geometry}
						material={materials.PaletteMaterial016}
					/>
					<mesh
						name="Cube028_10"
						geometry={nodes.Cube028_10.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube028_11"
						geometry={nodes.Cube028_11.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Vase"
					geometry={nodes.Vase.geometry}
					material={materials["Flower Vase_Color"]}
					position={[2.096, 0.1, -3.519]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="MouseThermaltakeBlack"
					geometry={nodes.MouseThermaltakeBlack.geometry}
					material={materials.PaletteMaterial017}
					position={[0.868, 0.792, -3.489]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack001"
					geometry={nodes.MouseThermaltakeBlack001.geometry}
					material={materials.PaletteMaterial001}
					position={[0.853, 0.796, -3.45]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack002"
					geometry={nodes.MouseThermaltakeBlack002.geometry}
					material={materials.PaletteMaterial018}
					position={[0.847, 0.791, -3.471]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="MouseThermaltakeBlack003"
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="MouseThermaltakeBlack003_1"
						geometry={nodes.MouseThermaltakeBlack003_1.geometry}
						material={materials.PaletteMaterial019}
					/>
					<mesh
						name="MouseThermaltakeBlack003_2"
						geometry={nodes.MouseThermaltakeBlack003_2.geometry}
						material={materials.PaletteMaterial020}
					/>
					<mesh
						name="MouseThermaltakeBlack003_3"
						geometry={nodes.MouseThermaltakeBlack003_3.geometry}
						material={materials.PaletteMaterial018}
					/>
					<mesh
						name="MouseThermaltakeBlack003_4"
						geometry={nodes.MouseThermaltakeBlack003_4.geometry}
						material={materials.PaletteMaterial019}
					/>
				</group>
				<mesh
					name="MouseThermaltakeBlack004"
					geometry={nodes.MouseThermaltakeBlack004.geometry}
					material={materials.PaletteMaterial017}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack005"
					geometry={nodes.MouseThermaltakeBlack005.geometry}
					material={materials.PaletteMaterial021}
					position={[0.869, 0.777, -3.461]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack007"
					geometry={nodes.MouseThermaltakeBlack007.geometry}
					material={materials.PaletteMaterial017}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack008"
					geometry={nodes.MouseThermaltakeBlack008.geometry}
					material={materials.PaletteMaterial022}
					position={[0.871, 0.792, -3.489]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack009"
					geometry={nodes.MouseThermaltakeBlack009.geometry}
					material={materials.PaletteMaterial019}
					position={[0.869, 0.787, -3.461]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack010"
					geometry={nodes.MouseThermaltakeBlack010.geometry}
					material={materials.PaletteMaterial021}
					position={[0.851, 0.795, -3.457]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack011"
					geometry={nodes.MouseThermaltakeBlack011.geometry}
					material={materials.PaletteMaterial019}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack012"
					geometry={nodes.MouseThermaltakeBlack012.geometry}
					material={materials.PaletteMaterial023}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack013"
					geometry={nodes.MouseThermaltakeBlack013.geometry}
					material={materials.PaletteMaterial023}
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack014"
					geometry={nodes.MouseThermaltakeBlack014.geometry}
					material={materials.PaletteMaterial001}
					position={[0.868, 0.792, -3.49]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="MouseThermaltakeBlack015"
					position={[0.862, 0.787, -3.473]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="MouseThermaltakeBlack015_1"
						geometry={nodes.MouseThermaltakeBlack015_1.geometry}
						material={materials.PaletteMaterial023}
					/>
					<mesh
						name="MouseThermaltakeBlack015_2"
						geometry={nodes.MouseThermaltakeBlack015_2.geometry}
						material={materials.PaletteMaterial020}
					/>
					<mesh
						name="MouseThermaltakeBlack015_3"
						geometry={nodes.MouseThermaltakeBlack015_3.geometry}
						material={materials.PaletteMaterial019}
					/>
				</group>
				<group
					name="Cube026"
					position={[1.777, 0.877, -3.996]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials.PaletteMaterial022}
					/>
				</group>
				<group
					name="Cube027"
					position={[-3.996, 1.103, -2.026]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials.PaletteMaterial022}
					/>
				</group>
				<group
					name="Cube032"
					position={[-3.996, 0.753, 2.602]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials.PaletteMaterial022}
					/>
				</group>
				<mesh
					name="CoffeeTable"
					geometry={nodes.CoffeeTable.geometry}
					material={materials["beech wood"]}
					position={[1.495, 0.1, 1.462]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Bishop_C8"
					geometry={nodes.Black_Bishop_C8.geometry}
					material={materials.PaletteMaterial001}
					position={[1.565, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Bishop_F8"
					geometry={nodes.Black_Bishop_F8.geometry}
					material={materials.PaletteMaterial001}
					position={[1.399, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Horse_B8"
					geometry={nodes.Black_Horse_B8.geometry}
					material={materials.BlackHorse}
					position={[1.62, 0.648, 1.643]}
				/>
				<mesh
					name="Black_Horse_G8"
					geometry={nodes.Black_Horse_G8.geometry}
					material={materials.BlackHorse}
					position={[1.344, 0.648, 1.643]}
				/>
				<mesh
					name="White_Horse_B1"
					geometry={nodes.White_Horse_B1.geometry}
					material={materials.WhiteHorse}
					position={[1.62, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Horse_G1"
					geometry={nodes.White_Horse_G1.geometry}
					material={materials.WhiteHorse}
					position={[1.344, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_King"
					geometry={nodes.Black_King.geometry}
					material={materials.PaletteMaterial001}
					position={[1.454, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Pawns"
					geometry={nodes.Black_Pawns.geometry}
					material={materials.PaletteMaterial001}
					position={[1.675, 0.648, 1.588]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Queen"
					geometry={nodes.Black_Queen.geometry}
					material={materials.PaletteMaterial001}
					position={[1.509, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Rook_A8"
					geometry={nodes.Black_Rook_A8.geometry}
					material={materials.PaletteMaterial001}
					position={[1.675, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Black_Rook_H8"
					geometry={nodes.Black_Rook_H8.geometry}
					material={materials.PaletteMaterial001}
					position={[1.289, 0.648, 1.643]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="Board"
					position={[1.482, 0.648, 1.45]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Plane"
						geometry={nodes.Plane.geometry}
						material={materials.White}
					/>
					<mesh
						name="Plane_1"
						geometry={nodes.Plane_1.geometry}
						material={materials.DarkWood}
					/>
				</group>
				<mesh
					name="White_Bishop_C1"
					geometry={nodes.White_Bishop_C1.geometry}
					material={materials.PaletteMaterial001}
					position={[1.565, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Bishop_F1"
					geometry={nodes.White_Bishop_F1.geometry}
					material={materials.PaletteMaterial001}
					position={[1.399, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_king"
					geometry={nodes.White_king.geometry}
					material={materials.PaletteMaterial001}
					position={[1.454, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Pawns"
					geometry={nodes.White_Pawns.geometry}
					material={materials.PaletteMaterial001}
					position={[1.675, 0.648, 1.312]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Queen"
					geometry={nodes.White_Queen.geometry}
					material={materials.PaletteMaterial001}
					position={[1.509, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Rook_A1"
					geometry={nodes.White_Rook_A1.geometry}
					material={materials.PaletteMaterial001}
					position={[1.675, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="White_Rook_H1"
					geometry={nodes.White_Rook_H1.geometry}
					material={materials.PaletteMaterial001}
					position={[1.289, 0.648, 1.257]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Circle"
					geometry={nodes.Circle.geometry}
					material={materials.PaletteMaterial005}
					position={[-2.414, 0.539, 1.212]}
					rotation={[0, 1.471, 0]}
				/>
				<mesh
					name="Cylinder008"
					geometry={nodes.Cylinder008.geometry}
					material={materials.PaletteMaterial025}
					position={[-2.417, 0.575, 1.241]}
					rotation={[0, 1.471, -2.546]}
				/>
				<group
					name="Base"
					position={[-2.645, 0.561, 1.359]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cylinder053"
						geometry={nodes.Cylinder053.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder053_1"
						geometry={nodes.Cylinder053_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder053_2"
						geometry={nodes.Cylinder053_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder053_3"
						geometry={nodes.Cylinder053_3.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="_MAIN_KEY002"
					position={[-2.336, 0.539, 0.956]}
					rotation={[-Math.PI, 0.262, -Math.PI]}
				>
					<mesh
						name="Cylinder072"
						geometry={nodes.Cylinder072.geometry}
						material={materials["ZenUV_Generic_Material.002"]}
					/>
					<mesh
						name="Cylinder072_1"
						geometry={nodes.Cylinder072_1.geometry}
						material={materials.PaletteMaterial026}
					/>
					<mesh
						name="Cylinder072_2"
						geometry={nodes.Cylinder072_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_3"
						geometry={nodes.Cylinder072_3.geometry}
						material={materials["TRIGGER BUTTONS "]}
					/>
					<mesh
						name="Cylinder072_4"
						geometry={nodes.Cylinder072_4.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_5"
						geometry={nodes.Cylinder072_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_6"
						geometry={nodes.Cylinder072_6.geometry}
						material={materials["dotted withe.001"]}
					/>
					<mesh
						name="Cylinder072_7"
						geometry={nodes.Cylinder072_7.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_8"
						geometry={nodes.Cylinder072_8.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_9"
						geometry={nodes.Cylinder072_9.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_10"
						geometry={nodes.Cylinder072_10.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_11"
						geometry={nodes.Cylinder072_11.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder072_12"
						geometry={nodes.Cylinder072_12.geometry}
						material={materials["Material.075"]}
					/>
				</group>
				<group
					name="_MAIN_KEY001"
					position={[-2.316, 0.539, 0.774]}
					rotation={[-Math.PI, 0.698, -Math.PI]}
				>
					<mesh
						name="Cylinder038_1"
						geometry={nodes.Cylinder038_1.geometry}
						material={materials["ZenUV_Generic_Material.002"]}
					/>
					<mesh
						name="Cylinder038_2"
						geometry={nodes.Cylinder038_2.geometry}
						material={materials.PaletteMaterial026}
					/>
					<mesh
						name="Cylinder038_3"
						geometry={nodes.Cylinder038_3.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_4"
						geometry={nodes.Cylinder038_4.geometry}
						material={materials["TRIGGER BUTTONS "]}
					/>
					<mesh
						name="Cylinder038_5"
						geometry={nodes.Cylinder038_5.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_6"
						geometry={nodes.Cylinder038_6.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_7"
						geometry={nodes.Cylinder038_7.geometry}
						material={materials["dotted withe.001"]}
					/>
					<mesh
						name="Cylinder038_8"
						geometry={nodes.Cylinder038_8.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_9"
						geometry={nodes.Cylinder038_9.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_10"
						geometry={nodes.Cylinder038_10.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_11"
						geometry={nodes.Cylinder038_11.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_12"
						geometry={nodes.Cylinder038_12.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder038_13"
						geometry={nodes.Cylinder038_13.geometry}
						material={materials["Material.075"]}
					/>
				</group>
				<group name="body" position={[-2.618, 0.591, 0.611]}>
					<mesh
						name="Cube100"
						geometry={nodes.Cube100.geometry}
						material={materials.veneer}
					/>
					<mesh
						name="Cube100_1"
						geometry={nodes.Cube100_1.geometry}
						material={materials["veneer (side)"]}
					/>
				</group>
				<mesh
					name="engine"
					geometry={nodes.engine.geometry}
					material={materials.PaletteMaterial027}
					position={[-2.616, 0.6, 0.642]}
				/>
				<mesh
					name="thorn"
					geometry={nodes.thorn.geometry}
					material={materials["grungy metal"]}
					position={[-2.616, 0.612, 0.642]}
				/>
				<group name="tuning_handle_1" position={[-2.549, 0.612, 0.44]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials.PaletteMaterial028}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
				<group name="tuning_handle_2" position={[-2.514, 0.612, 0.44]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials.PaletteMaterial028}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
				<mesh
					name="dust_cover"
					geometry={nodes.dust_cover.geometry}
					material={nodes.dust_cover.material}
					position={[-2.787, 0.596, 0.611]}
					rotation={[0, 0, 0.891]}
				/>
				<mesh
					name="fastening_2"
					geometry={nodes.fastening_2.geometry}
					material={materials["grungy metal"]}
					position={[-2.787, 0.596, 0.611]}
					rotation={[-Math.PI / 2, 0.68, Math.PI / 2]}
				/>
				<mesh
					name="legs"
					geometry={nodes.legs.geometry}
					material={materials.PaletteMaterial027}
					position={[-2.618, 0.539, 0.611]}
				/>
				<mesh
					name="pickup001"
					geometry={nodes.pickup001.geometry}
					material={materials.PaletteMaterial028}
					position={[-2.763, 0.639, 0.481]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<group
					name="pickup003"
					position={[-2.763, 0.639, 0.481]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cylinder059"
						geometry={nodes.Cylinder059.geometry}
						material={materials["grungy metal"]}
					/>
					<mesh
						name="Cylinder059_1"
						geometry={nodes.Cylinder059_1.geometry}
						material={materials.PaletteMaterial028}
					/>
					<mesh
						name="Cylinder059_2"
						geometry={nodes.Cylinder059_2.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="piece"
					geometry={nodes.piece.geometry}
					material={materials.PaletteMaterial027}
					position={[-2.699, 0.605, 0.464]}
				/>
				<mesh
					name="tuning_handle_3"
					geometry={nodes.tuning_handle_3.geometry}
					material={materials.PaletteMaterial028}
					position={[-2.647, 0.606, 0.464]}
				/>
				<group name="vinyl_plate" position={[-2.616, 0.613, 0.642]}>
					<mesh
						name="Cylinder056"
						geometry={nodes.Cylinder056.geometry}
						material={materials.fabric}
					/>
					<mesh
						name="Cylinder056_1"
						geometry={nodes.Cylinder056_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
				<mesh
					name="BezierCurve"
					geometry={nodes.BezierCurve.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.323, 2.199, -3.944]}
					rotation={[Math.PI, 0, 0]}
				/>
				<mesh
					name="Cube033"
					geometry={nodes.Cube033.geometry}
					material={materials.PaletteMaterial012}
					position={[-1.379, 2.086, -3.946]}
					rotation={[-1.571, 1.388, -1.55]}
				/>
				<mesh
					name="01"
					geometry={nodes["01"].geometry}
					material={materials["01"]}
					position={[-1.361, 1.984, -3.94]}
					rotation={[-1.605, -0.104, 0.01]}
				/>
				<mesh
					name="Helix"
					geometry={nodes.Helix.geometry}
					material={materials.PaletteMaterial029}
					position={[-1.379, 2.086, -3.946]}
					rotation={[-1.588, -0.208, -1.573]}
				/>
				<mesh
					name="Cube034"
					geometry={nodes.Cube034.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.967, 2.081, -3.944]}
					rotation={[1.571, 1.462, 1.558]}
				/>
				<mesh
					name="10"
					geometry={nodes["10"].geometry}
					material={materials["10"]}
					position={[-2.987, 1.979, -3.941]}
					rotation={[-1.571, 0.047, 0.005]}
				/>
				<mesh
					name="Helix009"
					geometry={nodes.Helix009.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.967, 2.081, -3.944]}
					rotation={[-1.595, 0.122, -1.547]}
				/>
				<mesh
					name="Cube035"
					geometry={nodes.Cube035.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.792, 2.057, -3.946]}
					rotation={[Math.PI / 2, 1.512, 1.564]}
				/>
				<mesh
					name="09"
					geometry={nodes["09"].geometry}
					material={materials["09"]}
					position={[-2.796, 1.952, -3.943]}
					rotation={[-Math.PI / 2, -0.002, 0]}
				/>
				<mesh
					name="Helix008"
					geometry={nodes.Helix008.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.792, 2.057, -3.946]}
					rotation={[-1.6, 0.066, -1.534]}
				/>
				<mesh
					name="Cube036"
					geometry={nodes.Cube036.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.618, 2.04, -3.941]}
					rotation={[1.571, 1.495, 1.562]}
				/>
				<mesh
					name="08"
					geometry={nodes["08"].geometry}
					material={materials["08"]}
					position={[-2.617, 1.933, -3.939]}
					rotation={[-1.568, 0.145, 0.016]}
				/>
				<mesh
					name="Helix007"
					geometry={nodes.Helix007.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.618, 2.04, -3.941]}
					rotation={[-1.598, 0.086, -1.539]}
				/>
				<mesh
					name="Cube037"
					geometry={nodes.Cube037.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.438, 2.028, -3.941]}
					rotation={[Math.PI / 2, 1.506, 1.563]}
				/>
				<mesh
					name="07"
					geometry={nodes["07"].geometry}
					material={materials["07"]}
					position={[-2.447, 1.924, -3.938]}
					rotation={[-1.571, 0.036, 0.004]}
				/>
				<mesh
					name="Helix006"
					geometry={nodes.Helix006.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.438, 2.028, -3.941]}
					rotation={[-1.599, 0.073, -1.536]}
				/>
				<mesh
					name="Cube038"
					geometry={nodes.Cube038.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.273, 2.019, -3.94]}
					rotation={[-1.571, 1.552, -1.569]}
				/>
				<mesh
					name="06"
					geometry={nodes["06"].geometry}
					material={materials["06"]}
					position={[-2.272, 1.916, -3.938]}
					rotation={[-1.571, -0.019, -0.002]}
				/>
				<mesh
					name="Helix005"
					geometry={nodes.Helix005.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.273, 2.019, -3.94]}
					rotation={[-1.602, -0.069, -1.572]}
				/>
				<mesh
					name="Cube039"
					geometry={nodes.Cube039.geometry}
					material={materials.PaletteMaterial012}
					position={[-2.104, 2.017, -3.94]}
					rotation={[-1.571, 1.538, -1.567]}
				/>
				<mesh
					name="05"
					geometry={nodes["05"].geometry}
					material={materials["05"]}
					position={[-2.108, 1.914, -3.937]}
					rotation={[-1.571, 0.048, 0.006]}
				/>
				<mesh
					name="Helix004"
					geometry={nodes.Helix004.geometry}
					material={materials.PaletteMaterial029}
					position={[-2.104, 2.017, -3.94]}
					rotation={[-1.6, -0.08, -1.572]}
				/>
				<mesh
					name="Cube040"
					geometry={nodes.Cube040.geometry}
					material={materials.PaletteMaterial012}
					position={[-1.925, 2.021, -3.946]}
					rotation={[-1.571, 1.546, -1.568]}
				/>
				<mesh
					name="04"
					geometry={nodes["04"].geometry}
					material={materials["04"]}
					position={[-1.928, 1.917, -3.943]}
					rotation={[-1.574, -0.039, 0.003]}
				/>
				<mesh
					name="Helix003"
					geometry={nodes.Helix003.geometry}
					material={materials.PaletteMaterial029}
					position={[-1.925, 2.021, -3.946]}
					rotation={[-1.601, -0.074, -1.572]}
				/>
				<mesh
					name="Cube041"
					geometry={nodes.Cube041.geometry}
					material={materials.PaletteMaterial012}
					position={[-1.761, 2.031, -3.947]}
					rotation={[-Math.PI / 2, 1.5, -1.563]}
				/>
				<mesh
					name="03"
					geometry={nodes["03"].geometry}
					material={materials["03"]}
					position={[-1.755, 1.927, -3.944]}
					rotation={[-1.571, -0.018, -0.002]}
				/>
				<mesh
					name="Helix002"
					geometry={nodes.Helix002.geometry}
					material={materials.PaletteMaterial029}
					position={[-1.761, 2.031, -3.947]}
					rotation={[-1.596, -0.112, -1.573]}
				/>
				<mesh
					name="Cube042"
					geometry={nodes.Cube042.geometry}
					material={materials.PaletteMaterial012}
					position={[-1.551, 2.055, -3.94]}
					rotation={[-1.571, 1.463, -1.559]}
				/>
				<mesh
					name="02"
					geometry={nodes["02"].geometry}
					material={materials["02"]}
					position={[-1.556, 1.952, -3.937]}
					rotation={[-1.57, 0.097, 0.011]}
				/>
				<mesh
					name="Helix001"
					geometry={nodes.Helix001.geometry}
					material={materials.PaletteMaterial029}
					position={[-1.551, 2.055, -3.94]}
					rotation={[-1.593, -0.143, -1.574]}
				/>
				<group
					name="Sphere"
					position={[-1.118, 2.193, -3.983]}
					rotation={[-Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Sphere004"
						geometry={nodes.Sphere004.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Sphere004_1"
						geometry={nodes.Sphere004_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="Sphere002"
					position={[-3.395, 2.18, -3.984]}
					rotation={[-Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Sphere004"
						geometry={nodes.Sphere004.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Sphere004_1"
						geometry={nodes.Sphere004_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Bed_low"
					geometry={nodes.Bed_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Cover_low"
					geometry={nodes.Cover_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Pillow1_low"
					geometry={nodes.Pillow1_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Pillow2_low"
					geometry={nodes.Pillow2_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Structure1_low"
					geometry={nodes.Structure1_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Structure1_low001"
					geometry={nodes.Structure1_low001.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Structure2_low"
					geometry={nodes.Structure2_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<mesh
					name="Structure3_low"
					geometry={nodes.Structure3_low.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.3, 0.1, -2.793]}
				/>
				<group
					name="Audio_Procesor"
					position={[-3.676, 0.661, 2.085]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube069"
						geometry={nodes.Cube069.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube069_1"
						geometry={nodes.Cube069_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="Camera_NUI"
					position={[-3.661, 0.661, 2.119]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube068"
						geometry={nodes.Cube068.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube068_1"
						geometry={nodes.Cube068_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Circle003"
					geometry={nodes.Circle003.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.633, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverBottom"
					geometry={nodes.CoverBottom.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.628, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverFront"
					geometry={nodes.CoverFront.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.628, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverSide"
					geometry={nodes.CoverSide.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.629, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverTop"
					geometry={nodes.CoverTop.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.628, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder027"
					geometry={nodes.Cylinder027.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.64, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="Cylinder028"
					position={[-3.642, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder047_1"
						geometry={nodes.Cylinder047_1.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cylinder047_2"
						geometry={nodes.Cylinder047_2.geometry}
						material={materials.PaletteMaterial026}
					/>
				</group>
				<mesh
					name="Fan"
					geometry={nodes.Fan.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.672, 0.661, 2.203]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="IR_Projector"
					position={[-3.645, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder044_1"
						geometry={nodes.Cylinder044_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder044_2"
						geometry={nodes.Cylinder044_2.geometry}
						material={materials.PaletteMaterial012}
					/>
				</group>
				<mesh
					name="IR_ProjectorCover"
					geometry={nodes.IR_ProjectorCover.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.628, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorCover"
					geometry={nodes.IR_SensorCover.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.628, 0.659, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_ProjectorGlass"
					geometry={nodes.IR_ProjectorGlass.geometry}
					material={materials.PaletteMaterial026}
					position={[-3.628, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorGlass"
					geometry={nodes.IR_SensorGlass.geometry}
					material={materials.PaletteMaterial026}
					position={[-3.628, 0.659, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="RGB_SensorGlass"
					geometry={nodes.RGB_SensorGlass.geometry}
					material={materials.PaletteMaterial026}
					position={[-3.628, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_ProjectorLens"
					geometry={nodes.IR_ProjectorLens.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.642, 0.659, 2.157]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorLens"
					geometry={nodes.IR_SensorLens.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.643, 0.659, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_Sensor"
					geometry={nodes.IR_Sensor.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.648, 0.659, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="IR_sensorLens"
					position={[-3.643, 0.659, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder042_1"
						geometry={nodes.Cylinder042_1.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cylinder042_2"
						geometry={nodes.Cylinder042_2.geometry}
						material={materials.PaletteMaterial026}
					/>
				</group>
				<mesh
					name="LED"
					geometry={nodes.LED.geometry}
					material={materials.PaletteMaterial031}
					position={[-3.628, 0.659, 2.129]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Metal_Frame"
					geometry={nodes.Metal_Frame.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.652, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Modem"
					geometry={nodes.Modem.geometry}
					material={materials.PaletteMaterial032}
					position={[-3.652, 0.659, 2.088]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="Motor_Controller"
					position={[-3.66, 0.661, 2.027]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube063"
						geometry={nodes.Cube063.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube063_1"
						geometry={nodes.Cube063_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="Procesor"
					position={[-3.668, 0.664, 2.141]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube062"
						geometry={nodes.Cube062.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cube062_1"
						geometry={nodes.Cube062_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="ProcesorIR"
					position={[-3.668, 0.674, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube061"
						geometry={nodes.Cube061.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cube061_1"
						geometry={nodes.Cube061_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="ProcesorRGB"
					position={[-3.668, 0.674, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube060"
						geometry={nodes.Cube060.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cube060_1"
						geometry={nodes.Cube060_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="RGB_Sensor"
					geometry={nodes.RGB_Sensor.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.648, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="RGB_SensorCover"
					geometry={nodes.RGB_SensorCover.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.628, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="RGB_SensorLens"
					position={[-3.644, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder039_1"
						geometry={nodes.Cylinder039_1.geometry}
						material={materials.PaletteMaterial012}
					/>
					<mesh
						name="Cylinder039_2"
						geometry={nodes.Cylinder039_2.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Side_AirIntake"
					geometry={nodes.Side_AirIntake.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.629, 0.661, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="SideWent"
					geometry={nodes.SideWent.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.666, 0.662, 2.221]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Sphere001"
					geometry={nodes.Sphere001.geometry}
					material={materials.PaletteMaterial026}
					position={[-3.64, 0.659, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Transfer_PlaneRGB"
					geometry={nodes.Transfer_PlaneRGB.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.657, 0.676, 2.101]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Transfer_TapeIR"
					geometry={nodes.Transfer_TapeIR.geometry}
					material={materials.PaletteMaterial001}
					position={[-3.657, 0.676, 2.073]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Went"
					geometry={nodes.Went.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.672, 0.661, 2.203]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Kinect_Leg"
					geometry={nodes.Kinect_Leg.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.66, 0.606, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Pillar"
					geometry={nodes.Pillar.geometry}
					material={materials.PaletteMaterial030}
					position={[-3.66, 0.64, 2.086]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Stand"
					geometry={nodes.Stand.geometry}
					material={materials.PaletteMaterial012}
					position={[-3.644, 0.606, 2.053]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="basketball"
					geometry={nodes.basketball.geometry}
					material={materials.Basketball}
					position={[-1.183, 0.1, -3.67]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="microphone"
					position={[-0.238, 0.924, -3.625]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane131"
						geometry={nodes.Plane131.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane131_1"
						geometry={nodes.Plane131_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane131_2"
						geometry={nodes.Plane131_2.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Plane131_3"
						geometry={nodes.Plane131_3.geometry}
						material={materials["Metal Wire Mesh"]}
					/>
					<mesh
						name="Plane131_4"
						geometry={nodes.Plane131_4.geometry}
						material={materials["Fabric 02"]}
					/>
					<mesh
						name="Plane131_5"
						geometry={nodes.Plane131_5.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="microphone_table_holder"
					position={[-0.238, 0.94, -3.625]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane130"
						geometry={nodes.Plane130.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane130_1"
						geometry={nodes.Plane130_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="pin001"
					geometry={nodes.pin001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.566, 0.203, -3.642]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
					scale={0.923}
				/>
				<mesh
					name="rake001"
					geometry={nodes.rake001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.562, 0.232, -3.945]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
					scale={0.923}
				/>
				<mesh
					name="shelfs001"
					geometry={nodes.shelfs001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.01, 0.208, -3.676]}
					rotation={[0, -Math.PI / 2, 0]}
					scale={0.923}
				/>
				<mesh
					name="side002"
					geometry={nodes.side002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.476, 0.235, -3.798]}
					rotation={[0, -Math.PI / 2, 0]}
					scale={0.923}
				/>
				<mesh
					name="vert001"
					geometry={nodes.vert001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.565, 0.77, -3.642]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.923}
				/>
				<mesh
					name="ground_real002"
					geometry={nodes.ground_real002.geometry}
					material={materials["Mud and grass.001"]}
					position={[-2.011, 0.243, -3.847]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={0.075}
				/>
				<mesh
					name="succulent_plant002"
					geometry={nodes.succulent_plant002.geometry}
					material={materials["succulent material.001"]}
					position={[-2.011, 0.315, -3.847]}
					rotation={[-Math.PI, 0, -Math.PI]}
					scale={1.405}
				/>
				<mesh
					name="Cylinder034"
					geometry={nodes.Cylinder034.geometry}
					material={nodes.Cylinder034.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder035"
					geometry={nodes.Cylinder035.geometry}
					material={nodes.Cylinder035.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder036"
					geometry={nodes.Cylinder036.geometry}
					material={nodes.Cylinder036.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder037"
					geometry={nodes.Cylinder037.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder038"
					geometry={nodes.Cylinder038.geometry}
					material={nodes.Cylinder038.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder039"
					geometry={nodes.Cylinder039.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder040"
					geometry={nodes.Cylinder040.geometry}
					material={nodes.Cylinder040.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder041"
					geometry={nodes.Cylinder041.geometry}
					material={nodes.Cylinder041.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder042"
					geometry={nodes.Cylinder042.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder043"
					geometry={nodes.Cylinder043.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder044"
					geometry={nodes.Cylinder044.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder045"
					geometry={nodes.Cylinder045.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder046"
					geometry={nodes.Cylinder046.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder047"
					geometry={nodes.Cylinder047.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder048"
					geometry={nodes.Cylinder048.geometry}
					material={nodes.Cylinder048.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder049"
					geometry={nodes.Cylinder049.geometry}
					material={nodes.Cylinder049.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Cylinder050"
					geometry={nodes.Cylinder050.geometry}
					material={nodes.Cylinder050.material}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="er001"
					geometry={nodes.er001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane039"
					geometry={nodes.Plane039.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane040"
					geometry={nodes.Plane040.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane041"
					geometry={nodes.Plane041.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane042"
					geometry={nodes.Plane042.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane043"
					geometry={nodes.Plane043.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane044"
					geometry={nodes.Plane044.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane045"
					geometry={nodes.Plane045.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane046"
					geometry={nodes.Plane046.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane047"
					geometry={nodes.Plane047.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane048"
					geometry={nodes.Plane048.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane049"
					geometry={nodes.Plane049.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane050"
					geometry={nodes.Plane050.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane051"
					geometry={nodes.Plane051.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane052"
					geometry={nodes.Plane052.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="Plane053"
					geometry={nodes.Plane053.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.224, 0.592, -3.789]}
					rotation={[0, Math.PI / 2, 0]}
					scale={1.76}
				/>
				<mesh
					name="AV40_Speaker_Left001"
					geometry={nodes.AV40_Speaker_Left001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_AC_select001"
					geometry={nodes.AV40_Speaker_Left_AC_select001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.17, 1.399, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers005"
					geometry={nodes.AV40_Speaker_Left_stickers005.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.172, 1.397, -3.872]}
					rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
					scale={0.004}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers007"
					geometry={nodes.AV40_Speaker_Left_stickers007.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.159, 1.397, -3.872]}
					rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
					scale={0.004}
				/>
				<mesh
					name="AV40_Speaker_Left_Bass_Switch001"
					geometry={nodes.AV40_Speaker_Left_Bass_Switch001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.157, 1.475, -3.874]}
				/>
				<group
					name="AV40_Speaker_Left_DC_PLUG_female001"
					position={[-2.212, 1.399, -3.869]}
				>
					<mesh
						name="Cube148"
						geometry={nodes.Cube148.geometry}
						material={materials.PaletteMaterial034}
					/>
					<mesh
						name="Cube148_1"
						geometry={nodes.Cube148_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Left_DC_PLUG_male001"
					position={[-2.212, 1.399, -3.869]}
				>
					<mesh
						name="Cube147"
						geometry={nodes.Cube147.geometry}
						material={materials.PaletteMaterial034}
					/>
					<mesh
						name="Cube147_1"
						geometry={nodes.Cube147_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Fuse001"
					geometry={nodes.AV40_Speaker_Left_Fuse001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.241, 1.397, -3.874]}
					rotation={[0, 0, 0.865]}
				/>
				<mesh
					name="AV40_Speaker_Left_Fuse_hole001"
					geometry={nodes.AV40_Speaker_Left_Fuse_hole001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.241, 1.397, -3.875]}
				/>
				<group
					name="AV40_Speaker_Left_Jack001"
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube144"
						geometry={nodes.Cube144.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube144_1"
						geometry={nodes.Cube144_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Line_Red_hole001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_hole001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.159, 1.513, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_hole001"
					geometry={nodes.AV40_Speaker_Left_Line_White_hole001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.159, 1.528, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_Red_metal001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_metal001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.159, 1.513, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_Metal001"
					geometry={nodes.AV40_Speaker_Left_Line_White_Metal001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.159, 1.528, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_Red_Plug001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_Plug001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.159, 1.513, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_plug001"
					geometry={nodes.AV40_Speaker_Left_Line_White_plug001.geometry}
					material={materials.PaletteMaterial035}
					position={[-2.159, 1.528, -3.874]}
				/>
				<mesh
					name="AV40_Speaker_Left_Power_hole001"
					geometry={nodes.AV40_Speaker_Left_Power_hole001.geometry}
					material={materials.PaletteMaterial034}
					position={[-2.241, 1.421, -3.868]}
				/>
				<group
					name="AV40_Speaker_Left_Power_switch001"
					position={[-2.241, 1.421, -3.868]}
				>
					<mesh
						name="Cube138"
						geometry={nodes.Cube138.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube138_1"
						geometry={nodes.Cube138_1.geometry}
						material={materials.PaletteMaterial035}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Serial_number001"
					geometry={nodes.AV40_Speaker_Left_Serial_number001.geometry}
					material={materials["Material.104"]}
					position={[-2.185, 1.441, -3.874]}
					scale={1.125}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers008"
					geometry={nodes.AV40_Speaker_Left_stickers008.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.139, 1.373, -3.691]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.003}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers009"
					geometry={nodes.AV40_Speaker_Left_stickers009.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.15, 1.373, -3.691]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.003}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers010"
					geometry={nodes.AV40_Speaker_Left_stickers010.geometry}
					material={materials.PaletteMaterial033}
					position={[-2.255, 1.372, -3.691]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.004}
				/>
				<group
					name="AV40_Speaker_Left_TRS_L001"
					position={[-2.159, 1.571, -3.874]}
				>
					<mesh
						name="Cube008"
						geometry={nodes.Cube008.geometry}
						material={materials.PaletteMaterial034}
					/>
					<mesh
						name="Cube008_1"
						geometry={nodes.Cube008_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Left_TRS_R001"
					position={[-2.159, 1.553, -3.874]}
				>
					<mesh
						name="Cube008"
						geometry={nodes.Cube008.geometry}
						material={materials.PaletteMaterial034}
					/>
					<mesh
						name="Cube008_1"
						geometry={nodes.Cube008_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Volume001"
					geometry={nodes.AV40_Speaker_Left_Volume001.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Back003"
					geometry={nodes.AV40_Speaker_Right_Back003.geometry}
					material={materials["noir_back_left.001"]}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Grid002"
					geometry={nodes.AV40_Speaker_Right_Grid002.geometry}
					material={materials["Metal wire mesh.003"]}
					position={[-2.199, 1.492, -3.697]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Grid003"
					geometry={nodes.AV40_Speaker_Right_Grid003.geometry}
					material={materials["Metal wire mesh.003"]}
					position={[-1.857, 1.492, -3.697]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="AV40_Speaker_Right_MAudio_Logo002"
					position={[-2.189, 1.373, -3.691]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.285}
				>
					<mesh
						name="Curve001"
						geometry={nodes.Curve001.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Curve001_1"
						geometry={nodes.Curve001_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_MAudio_Logo003"
					position={[-1.846, 1.373, -3.691]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.285}
				>
					<mesh
						name="Curve001"
						geometry={nodes.Curve001.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Curve001_1"
						geometry={nodes.Curve001_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right_Medium_Center002"
					geometry={nodes.AV40_Speaker_Right_Medium_Center002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.441, -3.706]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Center003"
					geometry={nodes.AV40_Speaker_Right_Medium_Center003.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.441, -3.706]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Membrane002"
					geometry={nodes.AV40_Speaker_Right_Medium_Membrane002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Membrane003"
					geometry={nodes.AV40_Speaker_Right_Medium_Membrane003.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="AV40_Speaker_Right_Plug003"
					position={[-2.238, 1.537, -3.871]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube002"
						geometry={nodes.Cube002.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube002_1"
						geometry={nodes.Cube002_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug002"
					position={[-1.857, 1.477, -3.871]}
				>
					<mesh
						name="Cube002"
						geometry={nodes.Cube002.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube002_1"
						geometry={nodes.Cube002_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug_Fix003"
					position={[-2.239, 1.537, -3.871]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube001"
						geometry={nodes.Cube001.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube001_1"
						geometry={nodes.Cube001_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug_Fix002"
					position={[-1.857, 1.476, -3.871]}
				>
					<mesh
						name="Cube001"
						geometry={nodes.Cube001.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cube001_1"
						geometry={nodes.Cube001_1.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right_Shinny_Front002"
					geometry={nodes.AV40_Speaker_Right_Shinny_Front002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Shinny_Front003"
					geometry={nodes.AV40_Speaker_Right_Shinny_Front003.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Twitter_Center002"
					geometry={nodes.AV40_Speaker_Right_Twitter_Center002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.543, -3.705]}
				/>
				<mesh
					name="AV40_Speaker_Right_Twitter_Center003"
					geometry={nodes.AV40_Speaker_Right_Twitter_Center003.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.543, -3.705]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer003"
					geometry={nodes.AV40_Speaker_Right_Woofer003.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.537, -3.886]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={[1.34, 1, 1.34]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer002"
					geometry={nodes.AV40_Speaker_Right_Woofer002.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.537, -3.886]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={[1.34, 1, 1.34]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer_Inside002"
					geometry={nodes.AV40_Speaker_Right_Woofer_Inside002.geometry}
					material={materials.PaletteMaterial001}
					position={[-2.199, 1.537, -3.787]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer_Inside003"
					geometry={nodes.AV40_Speaker_Right_Woofer_Inside003.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.537, -3.787]}
				/>
				<group
					name="AV40_Speaker_Volume_Light001"
					position={[-2.199, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube098"
						geometry={nodes.Cube098.geometry}
						material={materials.PaletteMaterial035}
					/>
					<mesh
						name="Cube098_1"
						geometry={nodes.Cube098_1.geometry}
						material={materials.PaletteMaterial031}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right001"
					geometry={nodes.AV40_Speaker_Right001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.857, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Back002"
					geometry={nodes.AV40_Speaker_Right_Back002.geometry}
					material={materials["noir_back_right.001"]}
					position={[-1.857, 1.361, -3.788]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="twig001"
					position={[-2.253, 0.211, -3.752]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig003"
						geometry={nodes.twig003.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig003_1"
						geometry={nodes.twig003_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<group
					name="twig002"
					position={[-2.256, 0.211, -3.743]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig004"
						geometry={nodes.twig004.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig004_1"
						geometry={nodes.twig004_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<group
					name="twig006"
					position={[-2.261, 0.211, -3.77]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig005"
						geometry={nodes.twig005.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig005_1"
						geometry={nodes.twig005_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<mesh
					name="twig_fluffy002"
					geometry={nodes.twig_fluffy002.geometry}
					material={materials["flower.002"]}
					position={[-2.253, 0.211, -3.752]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="lod2001"
					geometry={nodes.lod2001.geometry}
					material={materials["baseball.001"]}
					position={[-1.706, 0.629, -3.789]}
					rotation={[-Math.PI, 0.007, -Math.PI]}
					scale={0.037}
				/>
				<group
					name="Alarm_Clock002"
					position={[-1.885, 0.665, -3.74]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={[0.066, 0.023, 0.066]}
				>
					<mesh
						name="Cylinder091"
						geometry={nodes.Cylinder091.geometry}
						material={materials["Material.105"]}
					/>
					<mesh
						name="Cylinder091_1"
						geometry={nodes.Cylinder091_1.geometry}
						material={materials.PaletteMaterial001}
					/>
					<mesh
						name="Cylinder091_2"
						geometry={nodes.Cylinder091_2.geometry}
						material={materials.PaletteMaterial001}
					/>
				</group>
				<mesh
					name="Hour_Hand001"
					geometry={nodes.Hour_Hand001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.894, 0.67, -3.718]}
					rotation={[-Math.PI, 0, 2.093]}
					scale={[0.001, 0.005, 0]}
				/>
				<mesh
					name="Minute_Hand001"
					geometry={nodes.Minute_Hand001.geometry}
					material={materials.PaletteMaterial001}
					position={[-1.876, 0.671, -3.718]}
					rotation={[Math.PI, 0, -2.153]}
					scale={[0.001, 0.005, 0]}
				/>
				<instancedMesh
					args={[
						nodes.Phillips_Pan_Head_Screw033.geometry,
						materials["MI_screw_T.001"],
						34,
					]}
					name="Phillips_Pan_Head_Screw033"
					instanceMatrix={nodes.Phillips_Pan_Head_Screw033.instanceMatrix}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/roomsolutioncop2-v1-transformed.glb");
