/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/roomscaledgogo-v1.glb -T -j -M -K -k 
Files: public/roomscaledgogo-v1.glb [140.87MB] > roomscaledgogo-v1-transformed.glb [31.11MB] (78%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import { editable as e } from "@theatre/r3f";

export function RoomPortfolio(props) {
	const { nodes, materials } = useGLTF("/roomscaledgogo-v1-transformed.glb");
	const textureGlassMaterial = new MeshStandardMaterial({
		transparent: true,
		color: "#a7c7cb",
		opacity: 0.8,
	});
	return (
		<group {...props} dispose={null}>
			<e.group name="Scene" theatreKey="Scene">
				<group name="Plane015" position={[0, 0.1, 0]}>
					<mesh
						name="Plane044_1"
						geometry={nodes.Plane044_1.geometry}
						material={materials.Wall}
					/>
					<mesh
						name="Plane044_2"
						geometry={nodes.Plane044_2.geometry}
						material={materials.Floor}
					/>
					<mesh
						name="Plane044_3"
						geometry={nodes.Plane044_3.geometry}
						material={materials.Edges}
					/>
				</group>
				<mesh
					name="Edges"
					geometry={nodes.Edges.geometry}
					material={materials.Edges}
					position={[0, 0.1, 0]}
				/>
				<mesh
					name="Floor_Laptop_Desk_80x40x45"
					geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
					material={materials["Black Powder Coating"]}
					position={[0.729, 0.092, -3.62]}
				/>
				<mesh
					name="Text"
					geometry={nodes.Text.geometry}
					material={materials.outline}
					position={[0.677, 2.24, -1.988]}
					rotation={[Math.PI / 2, 0, Math.PI]}
				/>
				<group
					name="Plane013"
					position={[0.583, 1.917, -2.021]}
					rotation={[1.76, 0, Math.PI]}
				>
					<mesh
						name="Plane013_1"
						geometry={nodes.Plane013_1.geometry}
						material={materials.outline}
					/>
					<mesh
						name="Plane013_2"
						geometry={nodes.Plane013_2.geometry}
						material={materials["Material.001"]}
					/>
					<mesh
						name="Plane013_3"
						geometry={nodes.Plane013_3.geometry}
						material={materials["black skin"]}
					/>
					<mesh
						name="Plane013_4"
						geometry={nodes.Plane013_4.geometry}
						material={materials.Material}
					/>
					<mesh
						name="Plane013_5"
						geometry={nodes.Plane013_5.geometry}
						material={materials["black plactic"]}
					/>
					<mesh
						name="Plane013_6"
						geometry={nodes.Plane013_6.geometry}
						material={materials.metal}
					/>
				</group>
				<mesh
					name="Bean_Bag_chair"
					geometry={nodes.Bean_Bag_chair.geometry}
					material={materials["Valvet 01"]}
					position={[1.469, 0.092, -0.431]}
					rotation={[0, 0.332, 0]}
				/>
				<mesh
					name="Bean_Bag_chair001"
					geometry={nodes.Bean_Bag_chair001.geometry}
					material={materials["Valvet 01"]}
					position={[1.469, 0.092, 2.331]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group name="TV_Unit" position={[-4, 0, 1]}>
					<mesh
						name="Cube036_1"
						geometry={nodes.Cube036_1.geometry}
						material={materials.tvunit_white}
					/>
					<mesh
						name="Cube036_2"
						geometry={nodes.Cube036_2.geometry}
						material={materials.tvunit_handles}
					/>
					<mesh
						name="Cube036_3"
						geometry={nodes.Cube036_3.geometry}
						material={materials.tvunit_black}
					/>
					<mesh
						name="Cube036_4"
						geometry={nodes.Cube036_4.geometry}
						material={materials.box1}
					/>
					<mesh
						name="Cube036_5"
						geometry={nodes.Cube036_5.geometry}
						material={materials.box2}
					/>
					<mesh
						name="Cube036_6"
						geometry={nodes.Cube036_6.geometry}
						material={materials["tv mat"]}
					/>
					<mesh
						name="Cube036_7"
						geometry={nodes.Cube036_7.geometry}
						material={materials["Material.006"]}
					/>
					<mesh
						name="Cube036_8"
						geometry={nodes.Cube036_8.geometry}
						material={materials["book covers"]}
					/>
					<mesh
						name="Cube036_9"
						geometry={nodes.Cube036_9.geometry}
						material={materials.pic_frame}
					/>
					<mesh
						name="Cube036_10"
						geometry={nodes.Cube036_10.geometry}
						material={materials.pic_image}
					/>
				</group>
				<mesh
					name="Cylinder"
					geometry={nodes.Cylinder.geometry}
					material={nodes.Cylinder.material}
					position={[0, 0.687, 0]}
					scale={[1, 0.152, 1]}
				/>
				<mesh
					name="nba"
					geometry={nodes.nba.geometry}
					material={materials.tv}
					position={[-3.837, 1.645, 0.514]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={[1.065, 1, 1.015]}
				/>
				<mesh
					name="Table_Enterprise"
					geometry={nodes.Table_Enterprise.geometry}
					material={materials["Material.085"]}
					position={[-1.488, 0.092, 1.233]}
					rotation={[0, 1.571, 0]}
				/>
				<group
					name="Picture_frame-01"
					position={[-3.671, 0.725, 0.298]}
					rotation={[0, 1.571, 0]}
				>
					<mesh
						name="Picture_frame-01_1"
						geometry={nodes["Picture_frame-01_1"].geometry}
						material={materials["Moldura de madeira.001"]}
					/>
					<mesh
						name="Picture_frame-01_2"
						geometry={nodes["Picture_frame-01_2"].geometry}
						material={materials["29113998"]}
					/>
					<mesh
						name="Picture_frame-01_3"
						geometry={nodes["Picture_frame-01_3"].geometry}
						material={materials["Moldura textura.003"]}
					/>
				</group>
				<group
					name="Painting_with_frame"
					position={[-4.013, 2.971, -2.537]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube091"
						geometry={nodes.Cube091.geometry}
						material={materials.PORTA_TINTA}
					/>
					<mesh
						name="Cube091_1"
						geometry={nodes.Cube091_1.geometry}
						material={materials["Material.082"]}
					/>
					<mesh
						name="Cube091_2"
						geometry={nodes.Cube091_2.geometry}
						material={materials.Carvalho}
					/>
					<mesh
						name="Cube091_3"
						geometry={nodes.Cube091_3.geometry}
						material={materials.quadro_figura}
					/>
				</group>
				<group
					name="Painting_with_frame001"
					position={[1.437, 3.154, -4.019]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube092"
						geometry={nodes.Cube092.geometry}
						material={materials.PORTA_TINTA}
					/>
					<mesh
						name="Cube092_1"
						geometry={nodes.Cube092_1.geometry}
						material={materials["Material.082"]}
					/>
					<mesh
						name="Cube092_2"
						geometry={nodes.Cube092_2.geometry}
						material={materials.quadro2_figura}
					/>
				</group>
				<mesh
					name="Succulent_plant002"
					geometry={nodes.Succulent_plant002.geometry}
					material={materials["porcelain.001"]}
					position={[-1.635, 0.228, -3.825]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Indoor_potted_plant002"
					geometry={nodes.Indoor_potted_plant002.geometry}
					material={materials["ceramic_bumped_grey.001"]}
					position={[-1.938, 0.228, -3.706]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Forty-two_books001"
					geometry={nodes["Forty-two_books001"].geometry}
					material={materials["Books.002"]}
					position={[-2.124, 1.186, -3.821]}
					rotation={[0, 1.571, 0]}
				/>
				<group
					name="Monitor_MSI_Optix_MAG341CQ"
					position={[0.656, 0.938, -3.884]}
				>
					<mesh
						name="Cylinder007"
						geometry={nodes.Cylinder007.geometry}
						material={materials.MSI_Grau_Back}
					/>
					<mesh
						name="Cylinder007_1"
						geometry={nodes.Cylinder007_1.geometry}
						material={materials.MSI_Grau_Back}
					/>
					<mesh
						name="Cylinder007_2"
						geometry={nodes.Cylinder007_2.geometry}
						material={materials.Fuss_grau}
					/>
					<mesh
						name="Cylinder007_3"
						geometry={nodes.Cylinder007_3.geometry}
						material={materials.Fuss_rot}
					/>
					<mesh
						name="Cylinder007_4"
						geometry={nodes.Cylinder007_4.geometry}
						material={materials["Material.003"]}
					/>
					<mesh
						name="Cylinder007_5"
						geometry={nodes.Cylinder007_5.geometry}
						material={materials["Material.015"]}
					/>
					<mesh
						name="Cylinder007_6"
						geometry={nodes.Cylinder007_6.geometry}
						material={materials["Material.004"]}
					/>
					<mesh
						name="Cylinder007_7"
						geometry={nodes.Cylinder007_7.geometry}
						material={materials["Material.015"]}
					/>
					<mesh
						name="Cylinder007_8"
						geometry={nodes.Cylinder007_8.geometry}
						material={materials["Material.006"]}
					/>
					<mesh
						name="Cylinder007_9"
						geometry={nodes.Cylinder007_9.geometry}
						material={materials["Material.007"]}
					/>
					<mesh
						name="Cylinder007_10"
						geometry={nodes.Cylinder007_10.geometry}
						material={materials["29113998"]}
					/>
					<mesh
						name="Cylinder007_11"
						geometry={nodes.Cylinder007_11.geometry}
						material={materials["Gehäuse_grau.Stecker"]}
					/>
					<mesh
						name="Cylinder007_12"
						geometry={nodes.Cylinder007_12.geometry}
						material={materials["Material.016"]}
					/>
					<mesh
						name="Cylinder007_13"
						geometry={nodes.Cylinder007_13.geometry}
						material={materials.Screen}
					/>
				</group>
				<group
					name="microphone"
					position={[-0.39, 1.122, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane131"
						geometry={nodes.Plane131.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane131_1"
						geometry={nodes.Plane131_1.geometry}
						material={materials["Material.045"]}
					/>
					<mesh
						name="Plane131_2"
						geometry={nodes.Plane131_2.geometry}
						material={materials["plastic grey"]}
					/>
					<mesh
						name="Plane131_3"
						geometry={nodes.Plane131_3.geometry}
						material={materials["Metal Wire Mesh"]}
					/>
					<mesh
						name="Plane131_4"
						geometry={nodes.Plane131_4.geometry}
						material={materials["Fabric 02"]}
					/>
					<mesh
						name="Plane131_5"
						geometry={nodes.Plane131_5.geometry}
						material={materials["Material.046"]}
					/>
				</group>
				<group
					name="microphone_table_holder"
					position={[-0.39, 1.142, -3.631]}
					rotation={[0, Math.PI / 4, 0]}
				>
					<mesh
						name="Plane130"
						geometry={nodes.Plane130.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						name="Plane130_1"
						geometry={nodes.Plane130_1.geometry}
						material={materials["Material.045"]}
					/>
				</group>
				<e.group
					theatreKey="macScreengang"
					name="Cube021"
					position={[1.468, 0.94, -3.607]}
					rotation={[1.309, 0, 0]}
				>
					<mesh
						name="Cube016"
						geometry={nodes.Cube016.geometry}
						material={materials.body}
					/>
					<mesh
						name="Cube016_1"
						geometry={nodes.Cube016_1.geometry}
						material={materials["black.004"]}
					/>
					<mesh
						name="Cube016_2"
						geometry={nodes.Cube016_2.geometry}
						material={materials.screen}
					/>
					<mesh
						name="Cube016_3"
						geometry={nodes.Cube016_3.geometry}
						material={materials.dark}
					/>
					<mesh
						name="Cube016_4"
						geometry={nodes.Cube016_4.geometry}
						material={materials["glass.002"]}
					/>
					<mesh
						name="Cube016_5"
						geometry={nodes.Cube016_5.geometry}
						material={materials["Material.022"]}
					/>
					<mesh
						name="Cube016_6"
						geometry={nodes.Cube016_6.geometry}
						material={materials["Material.023"]}
					/>
					<mesh
						name="Cube016_7"
						geometry={nodes.Cube016_7.geometry}
						material={materials["glass.003"]}
					/>
					<mesh
						name="Cube016_8"
						geometry={nodes.Cube016_8.geometry}
						material={materials["Apple-logo"]}
					/>
					<mesh
						name="Cube016_9"
						geometry={nodes.Cube016_9.geometry}
						material={materials["black.001"]}
					/>
					<mesh
						name="Cube016_10"
						geometry={nodes.Cube016_10.geometry}
						material={materials.key}
					/>
					<mesh
						name="Cube016_11"
						geometry={nodes.Cube016_11.geometry}
						material={materials["key.002"]}
					/>
					<mesh
						name="Cube016_12"
						geometry={nodes.Cube016_12.geometry}
						material={materials["black.002"]}
					/>
					<mesh
						name="Cube016_13"
						geometry={nodes.Cube016_13.geometry}
						material={materials["black.003"]}
					/>
					<mesh
						name="Cube016_14"
						geometry={nodes.Cube016_14.geometry}
						material={materials["Material.021"]}
					/>
					<mesh
						name="Cube016_15"
						geometry={nodes.Cube016_15.geometry}
						material={materials.Dark}
					/>
					<mesh
						name="Cube016_16"
						geometry={nodes.Cube016_16.geometry}
						material={materials["Material.024"]}
					/>
				</e.group>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={materials["Pine Wood"]}
					position={[0.729, 0.092, -3.62]}
				/>
				<mesh
					name="Plane"
					geometry={nodes.Plane.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane001"
					geometry={nodes.Plane001.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane002"
					geometry={nodes.Plane002.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<e.mesh
					theatreKey="whiteLovag"
					name="Plane003"
					geometry={nodes.Plane003.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane004"
					geometry={nodes.Plane004.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane005"
					geometry={nodes.Plane005.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane006"
					geometry={nodes.Plane006.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane007"
					geometry={nodes.Plane007.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane010"
					geometry={nodes.Plane010.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<e.mesh
					theatreKey="rookWhite"
					name="Plane011"
					geometry={nodes.Plane011.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 1.127]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane016"
					geometry={nodes.Plane016.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane017"
					geometry={nodes.Plane017.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<e.mesh
					theatreKey="blackLovag"
					name="Plane018"
					geometry={nodes.Plane018.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane019"
					geometry={nodes.Plane019.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane020"
					geometry={nodes.Plane020.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane021"
					geometry={nodes.Plane021.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<e.mesh
					theatreKey="RookBlack"
					name="Plane025"
					geometry={nodes.Plane025.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.85]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Plane028"
					geometry={nodes.Plane028.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="Plane030"
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Plane008"
						geometry={nodes.Plane008.geometry}
						material={materials["Wood.001"]}
					/>
					<mesh
						name="Plane008_1"
						geometry={nodes.Plane008_1.geometry}
						material={materials["Wood white"]}
					/>
				</group>
				<mesh
					name="ладья"
					geometry={nodes.ладья.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья001"
					geometry={nodes.ладья001.geometry}
					material={materials["Wood white"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья002"
					geometry={nodes.ладья002.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="ладья003"
					geometry={nodes.ладья003.geometry}
					material={materials["Wood.001"]}
					position={[1.451, 0.75, 0.988]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group name="Bluetooth" position={[0.762, 0.971, -3.43]}>
					<mesh
						name="Cube028"
						geometry={nodes.Cube028.geometry}
						material={materials["Keychron K8 Pro - Other"]}
					/>
					<mesh
						name="Cube028_1"
						geometry={nodes.Cube028_1.geometry}
						material={materials["Keychron K8 Pro - Text"]}
					/>
					<mesh
						name="Cube028_2"
						geometry={nodes.Cube028_2.geometry}
						material={materials["Keychron K8 Pro - Switches"]}
					/>
					<mesh
						name="Cube028_3"
						geometry={nodes.Cube028_3.geometry}
						material={materials["Keychron K8 Pro - Plate"]}
					/>
					<mesh
						name="Cube028_4"
						geometry={nodes.Cube028_4.geometry}
						material={materials["Keychron K8 Pro - Black Keycaps"]}
					/>
					<mesh
						name="Cube028_5"
						geometry={nodes.Cube028_5.geometry}
						material={materials["Keychron K8 Pro - Blue Keycaps"]}
					/>
					<mesh
						name="Cube028_6"
						geometry={nodes.Cube028_6.geometry}
						material={materials["Keychron K8 Pro - Red Keycaps"]}
					/>
					<mesh
						name="Cube028_7"
						geometry={nodes.Cube028_7.geometry}
						material={materials["Keychron K8 Pro - Green Light"]}
					/>
					<mesh
						name="Cube028_8"
						geometry={nodes.Cube028_8.geometry}
						material={materials["Keychron K8 Pro - Plate"]}
					/>
					<mesh
						name="Cube028_9"
						geometry={nodes.Cube028_9.geometry}
						material={materials["Keychron K8 Pro - Rubber"]}
					/>
					<mesh
						name="Cube028_10"
						geometry={nodes.Cube028_10.geometry}
						material={materials["Keychron K8 Pro - USB Type C"]}
					/>
					<mesh
						name="Cube028_11"
						geometry={nodes.Cube028_11.geometry}
						material={materials["Keychron K8 Pro - USB Type C"]}
					/>
				</group>
				<mesh
					name="MouseThermaltakeBlack"
					geometry={nodes.MouseThermaltakeBlack.geometry}
					material={materials["Material.032"]}
					position={[0.993, 0.957, -3.483]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack001"
					geometry={nodes.MouseThermaltakeBlack001.geometry}
					material={materials["29113998"]}
					position={[0.974, 0.962, -3.435]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack002"
					geometry={nodes.MouseThermaltakeBlack002.geometry}
					material={materials["Material.036"]}
					position={[0.967, 0.956, -3.461]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="MouseThermaltakeBlack003"
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="MouseThermaltakeBlack003_1"
						geometry={nodes.MouseThermaltakeBlack003_1.geometry}
						material={materials["main body"]}
					/>
					<mesh
						name="MouseThermaltakeBlack003_2"
						geometry={nodes.MouseThermaltakeBlack003_2.geometry}
						material={materials["Material.030"]}
					/>
					<mesh
						name="MouseThermaltakeBlack003_3"
						geometry={nodes.MouseThermaltakeBlack003_3.geometry}
						material={materials["Material.036"]}
					/>
					<mesh
						name="MouseThermaltakeBlack003_4"
						geometry={nodes.MouseThermaltakeBlack003_4.geometry}
						material={materials["Material.035"]}
					/>
				</group>
				<mesh
					name="MouseThermaltakeBlack004"
					geometry={nodes.MouseThermaltakeBlack004.geometry}
					material={materials["Material.032"]}
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack005"
					geometry={nodes.MouseThermaltakeBlack005.geometry}
					material={materials["Material.033"]}
					position={[0.994, 0.938, -3.448]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack007"
					geometry={nodes.MouseThermaltakeBlack007.geometry}
					material={materials["Material.032"]}
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack008"
					geometry={nodes.MouseThermaltakeBlack008.geometry}
					material={materials["main body.001"]}
					position={[0.997, 0.957, -3.483]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack009"
					geometry={nodes.MouseThermaltakeBlack009.geometry}
					material={materials["main body"]}
					position={[0.994, 0.95, -3.448]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack010"
					geometry={nodes.MouseThermaltakeBlack010.geometry}
					material={materials["Material.031"]}
					position={[0.972, 0.961, -3.443]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack011"
					geometry={nodes.MouseThermaltakeBlack011.geometry}
					material={materials["main body"]}
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack012"
					geometry={nodes.MouseThermaltakeBlack012.geometry}
					material={materials["Material.025"]}
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack013"
					geometry={nodes.MouseThermaltakeBlack013.geometry}
					material={materials["Material.025"]}
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="MouseThermaltakeBlack014"
					geometry={nodes.MouseThermaltakeBlack014.geometry}
					material={materials["Material.028"]}
					position={[0.993, 0.957, -3.484]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="MouseThermaltakeBlack015"
					position={[0.986, 0.951, -3.463]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="MouseThermaltakeBlack015_1"
						geometry={nodes.MouseThermaltakeBlack015_1.geometry}
						material={materials["Material.025"]}
					/>
					<mesh
						name="MouseThermaltakeBlack015_2"
						geometry={nodes.MouseThermaltakeBlack015_2.geometry}
						material={materials["Material.030"]}
					/>
					<mesh
						name="MouseThermaltakeBlack015_3"
						geometry={nodes.MouseThermaltakeBlack015_3.geometry}
						material={materials["main body"]}
					/>
				</group>
				<mesh
					name="Vase"
					geometry={nodes.Vase.geometry}
					material={materials["Flower Vase_Color"]}
					position={[2.361, 0.092, -3.598]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<group
					name="Cube026"
					position={[1.95, 1.531, -3.997]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
				<group
					name="Cube027"
					position={[-3.995, 1.345, -1.343]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
				<group
					name="Cube032"
					position={[-4.021, 0.909, 2.564]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube129"
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						name="Cube129_1"
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
				<mesh
					name="CoffeeTable"
					geometry={nodes.CoffeeTable.geometry}
					material={materials["beech wood"]}
					position={[1.465, 0.092, 1.031]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Circle"
					geometry={nodes.Circle.geometry}
					material={materials["Semi-realistic Glass"]}
					position={[-1.361, 0.641, 1.69]}
					rotation={[0, 1.471, 0]}
				/>
				<mesh
					name="Cylinder008"
					geometry={nodes.Cylinder008.geometry}
					material={materials["Layered Glass"]}
					position={[-1.365, 0.686, 1.726]}
					rotation={[0, 1.471, -2.546]}
				/>
				<group
					name="Base"
					position={[-1.649, 0.668, 1.873]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="Cylinder053"
						geometry={nodes.Cylinder053.geometry}
						material={materials["Ashtray - Black Plastic"]}
					/>
					<mesh
						name="Cylinder053_1"
						geometry={nodes.Cylinder053_1.geometry}
						material={materials["Ashtray - Chrome"]}
					/>
					<mesh
						name="Cylinder053_2"
						geometry={nodes.Cylinder053_2.geometry}
						material={materials["Ashtray - Brass"]}
					/>
					<mesh
						name="Cylinder053_3"
						geometry={nodes.Cylinder053_3.geometry}
						material={materials["Ashtray - Steel brushed"]}
					/>
				</group>
				<group
					name="_MAIN_KEY001"
					position={[-1.263, 0.642, 1.146]}
					rotation={[-Math.PI, 0.698, -Math.PI]}
				>
					<mesh
						name="Cylinder005"
						geometry={nodes.Cylinder005.geometry}
						material={materials["ZenUV_Generic_Material.002"]}
					/>
					<mesh
						name="Cylinder005_1"
						geometry={nodes.Cylinder005_1.geometry}
						material={materials["XBOX ONE CONTROLLER"]}
					/>
					<mesh
						name="Cylinder005_2"
						geometry={nodes.Cylinder005_2.geometry}
						material={materials["TRIGGER BUTTONS "]}
					/>
					<mesh
						name="Cylinder005_3"
						geometry={nodes.Cylinder005_3.geometry}
						material={materials["29113998"]}
					/>
				</group>
				<group
					name="_MAIN_KEY002"
					position={[-1.263, 0.642, 1.37]}
					rotation={[-Math.PI, 0.262, -Math.PI]}
				>
					<mesh
						name="Cylinder005"
						geometry={nodes.Cylinder005.geometry}
						material={materials["ZenUV_Generic_Material.002"]}
					/>
					<mesh
						name="Cylinder005_1"
						geometry={nodes.Cylinder005_1.geometry}
						material={materials["XBOX ONE CONTROLLER"]}
					/>
					<mesh
						name="Cylinder005_2"
						geometry={nodes.Cylinder005_2.geometry}
						material={materials["TRIGGER BUTTONS "]}
					/>
					<mesh
						name="Cylinder005_3"
						geometry={nodes.Cylinder005_3.geometry}
						material={materials["29113998"]}
					/>
				</group>
				<group name="body" position={[-1.615, 0.706, 0.938]}>
					<mesh
						name="Cube100"
						geometry={nodes.Cube100.geometry}
						material={materials.veneer}
					/>
					<mesh
						name="Cube100_1"
						geometry={nodes.Cube100_1.geometry}
						material={materials["veneer (side)"]}
					/>
				</group>
				<mesh
					name="engine"
					geometry={nodes.engine.geometry}
					material={materials["black glossy"]}
					position={[-1.613, 0.717, 0.977]}
				/>
				<mesh
					name="thorn"
					geometry={nodes.thorn.geometry}
					material={materials["29113998"]}
					position={[-1.613, 0.732, 0.977]}
				/>
				<group name="tuning_handle_1" position={[-1.529, 0.732, 0.724]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["29113998"]}
					/>
				</group>
				<group name="tuning_handle_2" position={[-1.486, 0.732, 0.724]}>
					<mesh
						name="Cylinder057"
						geometry={nodes.Cylinder057.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						name="Cylinder057_1"
						geometry={nodes.Cylinder057_1.geometry}
						material={materials["29113998"]}
					/>
				</group>
				<mesh
					name="dust_cover"
					geometry={nodes.dust_cover.geometry}
					material={textureGlassMaterial}
					position={[-1.826, 0.712, 0.938]}
					rotation={[0, 0, 0.891]}
				/>
				<mesh
					name="fastening_2"
					geometry={nodes.fastening_2.geometry}
					material={materials["29113998"]}
					position={[-1.826, 0.712, 0.938]}
					rotation={[-Math.PI / 2, 0.68, Math.PI / 2]}
				/>
				<mesh
					name="legs"
					geometry={nodes.legs.geometry}
					material={materials["black glossy"]}
					position={[-1.615, 0.64, 0.938]}
				/>
				<mesh
					name="pickup001"
					geometry={nodes.pickup001.geometry}
					material={materials["black matte"]}
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<group
					name="pickup003"
					position={[-1.797, 0.766, 0.775]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cylinder059"
						geometry={nodes.Cylinder059.geometry}
						material={materials["29113998"]}
					/>
					<e.mesh
						theatreKey="Vinyl"
						name="Cylinder059_1"
						geometry={nodes.Cylinder059_1.geometry}
						material={materials["black matte"]}
					/>
					<e.mesh
						theatreKey="asd"
						name="Cylinder059_2"
						geometry={nodes.Cylinder059_2.geometry}
						material={materials["pink plastik"]}
					/>
				</group>
				<mesh
					name="piece"
					geometry={nodes.piece.geometry}
					material={materials["black glossy"]}
					position={[-1.716, 0.724, 0.755]}
				/>
				<mesh
					name="tuning_handle_3"
					geometry={nodes.tuning_handle_3.geometry}
					material={materials["black matte"]}
					position={[-1.652, 0.725, 0.755]}
				/>
				<group name="vinyl_plate" position={[-1.613, 0.733, 0.977]}>
					<e.mesh
						theatreKey="plate"
						name="Cylinder056"
						geometry={nodes.Cylinder056.geometry}
						material={materials.fabric}
					/>
					<mesh
						name="Cylinder056_1"
						geometry={nodes.Cylinder056_1.geometry}
						material={materials["Material.019"]}
					/>
				</group>
				<mesh
					name="BezierCurve"
					geometry={nodes.BezierCurve.geometry}
					material={materials["Material.081"]}
					position={[-1.899, 3.082, -3.987]}
					rotation={[0, 0, Math.PI]}
				/>
				<mesh
					name="Cube033"
					geometry={nodes.Cube033.geometry}
					material={materials["Rough pine board wall"]}
					position={[-3.08, 2.94, -3.984]}
					rotation={[-1.571, -1.388, 1.591]}
				/>
				<mesh
					name="01"
					geometry={nodes["01"].geometry}
					material={materials["01"]}
					position={[-3.101, 2.813, -3.992]}
					rotation={[-1.537, 0.104, -3.132]}
				/>
				<mesh
					name="Helix"
					geometry={nodes.Helix.geometry}
					material={materials["metal.001"]}
					position={[-3.08, 2.94, -3.984]}
					rotation={[-1.554, 0.208, 1.568]}
				/>
				<mesh
					name="Cube034"
					geometry={nodes.Cube034.geometry}
					material={materials["Rough pine board wall"]}
					position={[-1.094, 2.934, -3.987]}
					rotation={[1.571, -1.462, -1.583]}
				/>
				<mesh
					name="10"
					geometry={nodes["10"].geometry}
					material={materials["10"]}
					position={[-1.069, 2.807, -3.991]}
					rotation={[-1.571, -0.047, -3.136]}
				/>
				<mesh
					name="Helix009"
					geometry={nodes.Helix009.geometry}
					material={materials["metal.001"]}
					position={[-1.094, 2.934, -3.987]}
					rotation={[-1.546, -0.122, 1.595]}
				/>
				<mesh
					name="Cube035"
					geometry={nodes.Cube035.geometry}
					material={materials["Rough pine board wall"]}
					position={[-1.313, 2.904, -3.985]}
					rotation={[1.571, -1.512, -1.577]}
				/>
				<mesh
					name="09"
					geometry={nodes["09"].geometry}
					material={materials["09"]}
					position={[-1.308, 2.773, -3.988]}
					rotation={[-Math.PI / 2, 0.002, 3.141]}
				/>
				<mesh
					name="Helix008"
					geometry={nodes.Helix008.geometry}
					material={materials["metal.001"]}
					position={[-1.313, 2.904, -3.985]}
					rotation={[-1.542, -0.066, 1.607]}
				/>
				<mesh
					name="Cube036"
					geometry={nodes.Cube036.geometry}
					material={materials["Rough pine board wall"]}
					position={[-1.53, 2.883, -3.99]}
					rotation={[1.571, -1.495, -1.579]}
				/>
				<mesh
					name="08"
					geometry={nodes["08"].geometry}
					material={materials["08"]}
					position={[-1.531, 2.749, -3.994]}
					rotation={[-1.573, -0.145, -3.125]}
				/>
				<mesh
					name="Helix007"
					geometry={nodes.Helix007.geometry}
					material={materials["metal.001"]}
					position={[-1.53, 2.883, -3.99]}
					rotation={[-1.543, -0.086, 1.603]}
				/>
				<mesh
					name="Cube037"
					geometry={nodes.Cube037.geometry}
					material={materials["Rough pine board wall"]}
					position={[-1.755, 2.867, -3.991]}
					rotation={[1.571, -1.506, -1.578]}
				/>
				<mesh
					name="07"
					geometry={nodes["07"].geometry}
					material={materials["07"]}
					position={[-1.745, 2.738, -3.994]}
					rotation={[-1.571, -0.036, -3.137]}
				/>
				<mesh
					name="Helix006"
					geometry={nodes.Helix006.geometry}
					material={materials["metal.001"]}
					position={[-1.755, 2.867, -3.991]}
					rotation={[-1.542, -0.073, 1.606]}
				/>
				<mesh
					name="Cube038"
					geometry={nodes.Cube038.geometry}
					material={materials["Rough pine board wall"]}
					position={[-1.962, 2.857, -3.991]}
					rotation={[-Math.PI / 2, -1.552, 1.573]}
				/>
				<mesh
					name="06"
					geometry={nodes["06"].geometry}
					material={materials["06"]}
					position={[-1.962, 2.728, -3.995]}
					rotation={[-1.571, 0.019, 3.139]}
				/>
				<mesh
					name="Helix005"
					geometry={nodes.Helix005.geometry}
					material={materials["metal.001"]}
					position={[-1.962, 2.857, -3.991]}
					rotation={[-1.539, 0.069, 1.57]}
				/>
				<mesh
					name="Cube039"
					geometry={nodes.Cube039.geometry}
					material={materials["Rough pine board wall"]}
					position={[-2.173, 2.854, -3.992]}
					rotation={[-Math.PI / 2, -1.538, 1.575]}
				/>
				<mesh
					name="05"
					geometry={nodes["05"].geometry}
					material={materials["05"]}
					position={[-2.168, 2.725, -3.996]}
					rotation={[-1.571, -0.048, -3.136]}
				/>
				<mesh
					name="Helix004"
					geometry={nodes.Helix004.geometry}
					material={materials["metal.001"]}
					position={[-2.173, 2.854, -3.992]}
					rotation={[-1.541, 0.08, 1.569]}
				/>
				<mesh
					name="Cube040"
					geometry={nodes.Cube040.geometry}
					material={materials["Rough pine board wall"]}
					position={[-2.396, 2.859, -3.985]}
					rotation={[-1.571, -1.546, 1.574]}
				/>
				<mesh
					name="04"
					geometry={nodes["04"].geometry}
					material={materials["04"]}
					position={[-2.392, 2.73, -3.988]}
					rotation={[-1.568, 0.039, -3.138]}
				/>
				<mesh
					name="Helix003"
					geometry={nodes.Helix003.geometry}
					material={materials["metal.001"]}
					position={[-2.396, 2.859, -3.985]}
					rotation={[-1.54, 0.074, 1.57]}
				/>
				<mesh
					name="Cube041"
					geometry={nodes.Cube041.geometry}
					material={materials["Rough pine board wall"]}
					position={[-2.602, 2.871, -3.983]}
					rotation={[-1.571, -1.5, 1.579]}
				/>
				<mesh
					name="03"
					geometry={nodes["03"].geometry}
					material={materials["03"]}
					position={[-2.609, 2.742, -3.987]}
					rotation={[-1.571, 0.018, 3.139]}
				/>
				<mesh
					name="Helix002"
					geometry={nodes.Helix002.geometry}
					material={materials["metal.001"]}
					position={[-2.602, 2.871, -3.983]}
					rotation={[-1.545, 0.112, 1.568]}
				/>
				<mesh
					name="Cube042"
					geometry={nodes.Cube042.geometry}
					material={materials["Rough pine board wall"]}
					position={[-2.864, 2.902, -3.992]}
					rotation={[-1.571, -1.463, 1.583]}
				/>
				<mesh
					name="02"
					geometry={nodes["02"].geometry}
					material={materials["02"]}
					position={[-2.858, 2.773, -3.995]}
					rotation={[-1.572, -0.097, -3.131]}
				/>
				<mesh
					name="Helix001"
					geometry={nodes.Helix001.geometry}
					material={materials["metal.001"]}
					position={[-2.864, 2.902, -3.992]}
					rotation={[-1.549, 0.143, 1.568]}
				/>
				<group
					name="Sphere"
					position={[-3.405, 3.074, -3.938]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						name="Sphere004"
						geometry={nodes.Sphere004.geometry}
						material={materials["Material.079"]}
					/>
					<mesh
						name="Sphere004_1"
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Material.080"]}
					/>
				</group>
				<group
					name="Sphere002"
					position={[-0.559, 3.058, -3.937]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						name="Sphere004"
						geometry={nodes.Sphere004.geometry}
						material={materials["Material.079"]}
					/>
					<mesh
						name="Sphere004_1"
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Material.080"]}
					/>
				</group>
				<mesh
					name="Bed_low"
					geometry={nodes.Bed_low.geometry}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#BDCCD3" />
				</mesh>
				<mesh
					name="Cover_low"
					geometry={nodes.Cover_low.geometry}
					material={materials["Pillow and Cover"]}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#3C6A7F" />
				</mesh>
				<mesh
					name="Pillow1_low"
					geometry={nodes.Pillow1_low.geometry}
					material={materials["Pillow and Cover"]}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#3C6A7F" />
				</mesh>
				<mesh
					name="Pillow2_low"
					geometry={nodes.Pillow2_low.geometry}
					material={materials["Pillow and Cover"]}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#3C6A7F" />
				</mesh>
				<mesh
					name="Structure1_low"
					geometry={nodes.Structure1_low.geometry}
					material={materials["Material.006"]}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#A1662F" />
				</mesh>
				<mesh
					name="Structure1_low001"
					geometry={nodes.Structure1_low001.geometry}
					material={materials.Structure}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#A1662F" />
				</mesh>
				<mesh
					name="Structure2_low"
					geometry={nodes.Structure2_low.geometry}
					material={materials.Structure}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#A1662F" />
				</mesh>
				<mesh
					name="Structure3_low"
					geometry={nodes.Structure3_low.geometry}
					material={materials.Structure}
					position={[-3.282, 0.092, -2.665]}
				>
					<meshStandardMaterial color="#A1662F" />
				</mesh>
				<group
					name="Audio_Procesor"
					position={[-3.62, 0.794, 1.918]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube069"
						geometry={nodes.Cube069.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube069_1"
						geometry={nodes.Cube069_1.geometry}
						material={materials["Gold Metal.001"]}
					/>
				</group>
				<group
					name="Camera_NUI"
					position={[-3.602, 0.794, 1.961]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube068"
						geometry={nodes.Cube068.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube068_1"
						geometry={nodes.Cube068_1.geometry}
						material={materials["Gold Metal.001"]}
					/>
				</group>
				<mesh
					name="Circle003"
					geometry={nodes.Circle003.geometry}
					material={materials["Grey Matt Plactic"]}
					position={[-3.567, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverBottom"
					geometry={nodes.CoverBottom.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.56, 0.793, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverFront"
					geometry={nodes.CoverFront.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.56, 0.793, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverSide"
					geometry={nodes.CoverSide.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.561, 0.793, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="CoverTop"
					geometry={nodes.CoverTop.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.56, 0.793, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder027"
					geometry={nodes.Cylinder027.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.575, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="Cylinder028"
					position={[-3.578, 0.791, 2.009]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder047_1"
						geometry={nodes.Cylinder047_1.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cylinder047_2"
						geometry={nodes.Cylinder047_2.geometry}
						material={materials["Glass.001"]}
					/>
				</group>
				<mesh
					name="Fan"
					geometry={nodes.Fan.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.615, 0.794, 2.066]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="IR_Projector"
					position={[-3.582, 0.791, 2.008]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder044_1"
						geometry={nodes.Cylinder044_1.geometry}
						material={materials["Grey Matt Plactic"]}
					/>
					<mesh
						name="Cylinder044_2"
						geometry={nodes.Cylinder044_2.geometry}
						material={materials["Black Matt Plactic"]}
					/>
				</group>
				<mesh
					name="IR_ProjectorCover"
					geometry={nodes.IR_ProjectorCover.geometry}
					material={materials["Grey Matt Plactic"]}
					position={[-3.561, 0.791, 2.008]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorCover"
					geometry={nodes.IR_SensorCover.geometry}
					material={materials["Grey Matt Plactic"]}
					position={[-3.561, 0.791, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_ProjectorGlass"
					geometry={nodes.IR_ProjectorGlass.geometry}
					material={materials["Glass.001"]}
					position={[-3.561, 0.791, 2.008]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorGlass"
					geometry={nodes.IR_SensorGlass.geometry}
					material={materials["Glass.001"]}
					position={[-3.561, 0.791, 1.903]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="RGB_SensorGlass"
					geometry={nodes.RGB_SensorGlass.geometry}
					material={materials["Glass.001"]}
					position={[-3.561, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_ProjectorLens"
					geometry={nodes.IR_ProjectorLens.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.578, 0.791, 2.009]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_Sensor"
					geometry={nodes.IR_Sensor.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.586, 0.791, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="IR_SensorLens"
					geometry={nodes.IR_SensorLens.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.579, 0.791, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="IR_sensorLens"
					position={[-3.579, 0.791, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder042_1"
						geometry={nodes.Cylinder042_1.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cylinder042_2"
						geometry={nodes.Cylinder042_2.geometry}
						material={materials["Glass.001"]}
					/>
				</group>
				<mesh
					name="LED"
					geometry={nodes.LED.geometry}
					material={materials.LED}
					position={[-3.56, 0.791, 1.973]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Metal_Frame"
					geometry={nodes.Metal_Frame.geometry}
					material={materials["Matt Metal"]}
					position={[-3.59, 0.793, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Modem"
					geometry={nodes.Modem.geometry}
					material={materials.Adaptor}
					position={[-3.59, 0.791, 1.922]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="Motor_Controller"
					position={[-3.601, 0.794, 1.845]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube063"
						geometry={nodes.Cube063.geometry}
						material={materials["Electro Panel"]}
					/>
					<mesh
						name="Cube063_1"
						geometry={nodes.Cube063_1.geometry}
						material={materials["Gold Metal.001"]}
					/>
				</group>
				<group
					name="Procesor"
					position={[-3.61, 0.797, 1.989]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube062"
						geometry={nodes.Cube062.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cube062_1"
						geometry={nodes.Cube062_1.geometry}
						material={materials["Matt Metal"]}
					/>
				</group>
				<group
					name="ProcesorIR"
					position={[-3.61, 0.81, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube061"
						geometry={nodes.Cube061.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cube061_1"
						geometry={nodes.Cube061_1.geometry}
						material={materials["Matt Metal"]}
					/>
				</group>
				<group
					name="ProcesorRGB"
					position={[-3.61, 0.81, 1.938]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cube060"
						geometry={nodes.Cube060.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cube060_1"
						geometry={nodes.Cube060_1.geometry}
						material={materials["Matt Metal"]}
					/>
				</group>
				<mesh
					name="RGB_Sensor"
					geometry={nodes.RGB_Sensor.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.586, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="RGB_SensorCover"
					geometry={nodes.RGB_SensorCover.geometry}
					material={materials["Grey Matt Plactic"]}
					position={[-3.561, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<group
					name="RGB_SensorLens"
					position={[-3.58, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				>
					<mesh
						name="Cylinder039_1"
						geometry={nodes.Cylinder039_1.geometry}
						material={materials["Black Matt Plactic"]}
					/>
					<mesh
						name="Cylinder039_2"
						geometry={nodes.Cylinder039_2.geometry}
						material={materials["Grey Matt Plactic"]}
					/>
				</group>
				<mesh
					name="Side_AirIntake"
					geometry={nodes.Side_AirIntake.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.561, 0.794, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="SideWent"
					geometry={nodes.SideWent.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.608, 0.794, 2.088]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Sphere001"
					geometry={nodes.Sphere001.geometry}
					material={materials["Glass.001"]}
					position={[-3.575, 0.791, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Transfer_PlaneRGB"
					geometry={nodes.Transfer_PlaneRGB.geometry}
					material={materials["Gold Metal.001"]}
					position={[-3.596, 0.812, 1.939]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Transfer_TapeIR"
					geometry={nodes.Transfer_TapeIR.geometry}
					material={materials["Gold Metal.001"]}
					position={[-3.596, 0.812, 1.904]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Went"
					geometry={nodes.Went.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.615, 0.794, 2.066]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Kinect_Leg"
					geometry={nodes.Kinect_Leg.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.6, 0.725, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Pillar"
					geometry={nodes.Pillar.geometry}
					material={materials["Glossy Plastic "]}
					position={[-3.6, 0.767, 1.92]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Stand"
					geometry={nodes.Stand.geometry}
					material={materials["Black Matt Plactic"]}
					position={[-3.581, 0.725, 1.879]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="basketball"
					geometry={nodes.basketball.geometry}
					material={materials.Basketball}
					position={[-0.673, 0.092, -3.717]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="pin001"
					geometry={nodes.pin001.geometry}
					material={materials["29113998"]}
					position={[-1.079, 0.221, -3.569]}
					rotation={[Math.PI / 2, -1.571, 0]}
				/>
				<mesh
					name="rake001"
					geometry={nodes.rake001.geometry}
					material={materials["29113998"]}
					position={[-1.074, 0.257, -3.948]}
					rotation={[Math.PI / 2, -1.571, 0]}
				/>
				<mesh
					name="shelfs001"
					geometry={nodes.shelfs001.geometry}
					material={materials.Wood}
					position={[-1.634, 0.228, -3.612]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="side002"
					geometry={nodes.side002.geometry}
					material={materials.Wood}
					position={[-2.216, 0.261, -3.764]}
					rotation={[0, -Math.PI / 2, 0]}
				/>
				<mesh
					name="vert001"
					geometry={nodes.vert001.geometry}
					material={materials.Wood}
					position={[-1.078, 0.929, -3.569]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="ground_real002"
					geometry={nodes.ground_real002.geometry}
					material={materials["Mud and grass.001"]}
					position={[-1.635, 0.271, -3.825]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="succulent_plant002"
					geometry={nodes.succulent_plant002.geometry}
					material={materials["succulent material.001"]}
					position={[-1.635, 0.361, -3.825]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="Cylinder034"
					geometry={nodes.Cylinder034.geometry}
					material={nodes.Cylinder034.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder035"
					geometry={nodes.Cylinder035.geometry}
					material={nodes.Cylinder035.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder036"
					geometry={nodes.Cylinder036.geometry}
					material={nodes.Cylinder036.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder037"
					geometry={nodes.Cylinder037.geometry}
					material={materials["Material.006"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder038"
					geometry={nodes.Cylinder038.geometry}
					material={nodes.Cylinder038.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder039"
					geometry={nodes.Cylinder039.geometry}
					material={materials["Material.006"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder040"
					geometry={nodes.Cylinder040.geometry}
					material={nodes.Cylinder040.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder041"
					geometry={nodes.Cylinder041.geometry}
					material={nodes.Cylinder041.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder042"
					geometry={nodes.Cylinder042.geometry}
					material={materials["Material.096"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder043"
					geometry={nodes.Cylinder043.geometry}
					material={materials["Material.097"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder044"
					geometry={nodes.Cylinder044.geometry}
					material={materials["black.004"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder045"
					geometry={nodes.Cylinder045.geometry}
					material={materials["Material.099"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder046"
					geometry={nodes.Cylinder046.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder047"
					geometry={nodes.Cylinder047.geometry}
					material={materials["Material.101"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder048"
					geometry={nodes.Cylinder048.geometry}
					material={nodes.Cylinder048.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder049"
					geometry={nodes.Cylinder049.geometry}
					material={nodes.Cylinder049.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Cylinder050"
					geometry={nodes.Cylinder050.geometry}
					material={nodes.Cylinder050.material}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="er001"
					geometry={nodes.er001.geometry}
					material={materials["Material.088"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane039"
					geometry={nodes.Plane039.geometry}
					material={materials["Material.095"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane040"
					geometry={nodes.Plane040.geometry}
					material={materials["Material.095"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane041"
					geometry={nodes.Plane041.geometry}
					material={materials["Material.088"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane042"
					geometry={nodes.Plane042.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane043"
					geometry={nodes.Plane043.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane044"
					geometry={nodes.Plane044.geometry}
					material={materials["Material.090"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane045"
					geometry={nodes.Plane045.geometry}
					material={materials["Material.006"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane046"
					geometry={nodes.Plane046.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane047"
					geometry={nodes.Plane047.geometry}
					material={materials["Material.092"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane048"
					geometry={nodes.Plane048.geometry}
					material={materials["Material.006"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane049"
					geometry={nodes.Plane049.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane050"
					geometry={nodes.Plane050.geometry}
					material={materials["Material.088"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane051"
					geometry={nodes.Plane051.geometry}
					material={materials["Material.093"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane052"
					geometry={nodes.Plane052.geometry}
					material={materials["Material.088"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="Plane053"
					geometry={nodes.Plane053.geometry}
					material={materials["Material.100"]}
					position={[-1.902, 0.708, -3.753]}
					rotation={[0, Math.PI / 2, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left001"
					geometry={nodes.AV40_Speaker_Left001.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_AC_select001"
					geometry={nodes.AV40_Speaker_Left_AC_select001.geometry}
					material={materials["rouge_mat.001"]}
					position={[-1.835, 1.716, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers005"
					geometry={nodes.AV40_Speaker_Left_stickers005.geometry}
					material={materials["maudio_stickers.001"]}
					position={[-1.837, 1.713, -3.857]}
					rotation={[-Math.PI / 2, -1.571, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers007"
					geometry={nodes.AV40_Speaker_Left_stickers007.geometry}
					material={materials["maudio_stickers.001"]}
					position={[-1.821, 1.713, -3.857]}
					rotation={[-Math.PI / 2, -1.571, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_Bass_Switch001"
					geometry={nodes.AV40_Speaker_Left_Bass_Switch001.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.818, 1.81, -3.859]}
				/>
				<group
					name="AV40_Speaker_Left_DC_PLUG_female001"
					position={[-1.887, 1.716, -3.852]}
				>
					<mesh
						name="Cube148"
						geometry={nodes.Cube148.geometry}
						material={materials["gris_fonce_mat.001"]}
					/>
					<mesh
						name="Cube148_1"
						geometry={nodes.Cube148_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Left_DC_PLUG_male001"
					position={[-1.887, 1.716, -3.852]}
				>
					<mesh
						name="Cube147"
						geometry={nodes.Cube147.geometry}
						material={materials["gris_fonce_mat.001"]}
					/>
					<mesh
						name="Cube147_1"
						geometry={nodes.Cube147_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Fuse001"
					geometry={nodes.AV40_Speaker_Left_Fuse001.geometry}
					material={materials["gris_fonce_mat.001"]}
					position={[-1.923, 1.714, -3.86]}
					rotation={[0, 0, 0.865]}
				/>
				<mesh
					name="AV40_Speaker_Left_Fuse_hole001"
					geometry={nodes.AV40_Speaker_Left_Fuse_hole001.geometry}
					material={materials["gris_fonce_mat.001"]}
					position={[-1.923, 1.714, -3.86]}
				/>
				<group
					name="AV40_Speaker_Left_Jack001"
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube144"
						geometry={nodes.Cube144.geometry}
						material={materials["gris_mat.001"]}
					/>
					<mesh
						name="Cube144_1"
						geometry={nodes.Cube144_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Line_Red_hole001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_hole001.geometry}
					material={materials["gris_fonce_mat.001"]}
					position={[-1.82, 1.858, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_hole001"
					geometry={nodes.AV40_Speaker_Left_Line_White_hole001.geometry}
					material={materials["gris_fonce_mat.001"]}
					position={[-1.82, 1.877, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_Red_metal001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_metal001.geometry}
					material={materials["metal.003"]}
					position={[-1.82, 1.858, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_Metal001"
					geometry={nodes.AV40_Speaker_Left_Line_White_Metal001.geometry}
					material={materials["metal.003"]}
					position={[-1.82, 1.877, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_Red_Plug001"
					geometry={nodes.AV40_Speaker_Left_Line_Red_Plug001.geometry}
					material={materials["rouge_mat.001"]}
					position={[-1.82, 1.858, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Line_White_plug001"
					geometry={nodes.AV40_Speaker_Left_Line_White_plug001.geometry}
					material={materials["blanc.001"]}
					position={[-1.82, 1.877, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_Power_hole001"
					geometry={nodes.AV40_Speaker_Left_Power_hole001.geometry}
					material={materials["gris_fonce_mat.001"]}
					position={[-1.924, 1.743, -3.852]}
				/>
				<group
					name="AV40_Speaker_Left_Power_switch001"
					position={[-1.924, 1.743, -3.852]}
				>
					<mesh
						name="Cube138"
						geometry={nodes.Cube138.geometry}
						material={materials["noir_mat.001"]}
					/>
					<mesh
						name="Cube138_1"
						geometry={nodes.Cube138_1.geometry}
						material={materials["blanc.001"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Serial_number001"
					geometry={nodes.AV40_Speaker_Left_Serial_number001.geometry}
					material={materials["Material.104"]}
					position={[-1.853, 1.768, -3.859]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers008"
					geometry={nodes.AV40_Speaker_Left_stickers008.geometry}
					material={materials["maudio_stickers.001"]}
					position={[-1.796, 1.683, -3.631]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers009"
					geometry={nodes.AV40_Speaker_Left_stickers009.geometry}
					material={materials["maudio_stickers.001"]}
					position={[-1.809, 1.683, -3.631]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Left_stickers010"
					geometry={nodes.AV40_Speaker_Left_stickers010.geometry}
					material={materials["maudio_stickers.001"]}
					position={[-1.941, 1.682, -3.631]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="AV40_Speaker_Left_TRS_L001"
					position={[-1.82, 1.931, -3.859]}
				>
					<mesh
						name="Cube008"
						geometry={nodes.Cube008.geometry}
						material={materials["gris_fonce_mat.001"]}
					/>
					<mesh
						name="Cube008_1"
						geometry={nodes.Cube008_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Left_TRS_R001"
					position={[-1.82, 1.909, -3.859]}
				>
					<mesh
						name="Cube008"
						geometry={nodes.Cube008.geometry}
						material={materials["gris_fonce_mat.001"]}
					/>
					<mesh
						name="Cube008_1"
						geometry={nodes.Cube008_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Left_Volume001"
					geometry={nodes.AV40_Speaker_Left_Volume001.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Back003"
					geometry={nodes.AV40_Speaker_Right_Back003.geometry}
					material={materials["noir_back_left.001"]}
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Grid002"
					geometry={nodes.AV40_Speaker_Right_Grid002.geometry}
					material={materials["Metal wire mesh.003"]}
					position={[-1.871, 1.832, -3.638]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Grid003"
					geometry={nodes.AV40_Speaker_Right_Grid003.geometry}
					material={materials["Metal wire mesh.003"]}
					position={[-1.443, 1.832, -3.638]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="AV40_Speaker_Right_MAudio_Logo002"
					position={[-1.859, 1.683, -3.63]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Curve001"
						geometry={nodes.Curve001.geometry}
						material={materials["metal.003"]}
					/>
					<mesh
						name="Curve001_1"
						geometry={nodes.Curve001_1.geometry}
						material={materials["noir_mat.001"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_MAudio_Logo003"
					position={[-1.43, 1.683, -3.63]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Curve001"
						geometry={nodes.Curve001.geometry}
						material={materials["metal.003"]}
					/>
					<mesh
						name="Curve001_1"
						geometry={nodes.Curve001_1.geometry}
						material={materials["noir_mat.001"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right_Medium_Center002"
					geometry={nodes.AV40_Speaker_Right_Medium_Center002.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.871, 1.768, -3.649]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Center003"
					geometry={nodes.AV40_Speaker_Right_Medium_Center003.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.443, 1.768, -3.649]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Membrane002"
					geometry={nodes.AV40_Speaker_Right_Medium_Membrane002.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Medium_Membrane003"
					geometry={nodes.AV40_Speaker_Right_Medium_Membrane003.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.443, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					name="AV40_Speaker_Right_Plug003"
					position={[-1.919, 1.888, -3.856]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube010"
						geometry={nodes.Cube010.geometry}
						material={materials["noir_mat.001"]}
					/>
					<mesh
						name="Cube010_1"
						geometry={nodes.Cube010_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug002"
					position={[-1.443, 1.813, -3.856]}
				>
					<mesh
						name="Cube010"
						geometry={nodes.Cube010.geometry}
						material={materials["noir_mat.001"]}
					/>
					<mesh
						name="Cube010_1"
						geometry={nodes.Cube010_1.geometry}
						material={materials["metal.003"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug_Fix003"
					position={[-1.92, 1.888, -3.855]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Cube009"
						geometry={nodes.Cube009.geometry}
						material={materials["noir_mat.001"]}
					/>
					<mesh
						name="Cube009_1"
						geometry={nodes.Cube009_1.geometry}
						material={materials["rouge_mat.001"]}
					/>
				</group>
				<group
					name="AV40_Speaker_Right_Plug_Fix002"
					position={[-1.443, 1.812, -3.855]}
				>
					<mesh
						name="Cube001"
						geometry={nodes.Cube001.geometry}
						material={materials["noir_mat.001"]}
					/>
					<mesh
						name="Cube001_1"
						geometry={nodes.Cube001_1.geometry}
						material={materials["rouge_mat.001"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right_Shinny_Front002"
					geometry={nodes.AV40_Speaker_Right_Shinny_Front002.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Shinny_Front003"
					geometry={nodes.AV40_Speaker_Right_Shinny_Front003.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.443, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Twitter_Center002"
					geometry={nodes.AV40_Speaker_Right_Twitter_Center002.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.871, 1.896, -3.647]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer003"
					geometry={nodes.AV40_Speaker_Right_Woofer003.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.871, 1.889, -3.874]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer002"
					geometry={nodes.AV40_Speaker_Right_Woofer002.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.443, 1.889, -3.874]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer_Inside002"
					geometry={nodes.AV40_Speaker_Right_Woofer_Inside002.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.871, 1.889, -3.751]}
				/>
				<mesh
					name="AV40_Speaker_Right_Woofer_Inside003"
					geometry={nodes.AV40_Speaker_Right_Woofer_Inside003.geometry}
					material={materials["noir_brillant.001"]}
					position={[-1.443, 1.889, -3.751]}
				/>
				<group
					name="AV40_Speaker_Volume_Light001"
					position={[-1.871, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cube098"
						geometry={nodes.Cube098.geometry}
						material={materials["blanc.001"]}
					/>
					<mesh
						name="Cube098_1"
						geometry={nodes.Cube098_1.geometry}
						material={materials["Material.103"]}
					/>
				</group>
				<mesh
					name="AV40_Speaker_Right001"
					geometry={nodes.AV40_Speaker_Right001.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.443, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Back002"
					geometry={nodes.AV40_Speaker_Right_Back002.geometry}
					material={materials["noir_back_right.001"]}
					position={[-1.443, 1.668, -3.751]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="AV40_Speaker_Right_Twitter_Center003"
					geometry={nodes.AV40_Speaker_Right_Twitter_Center003.geometry}
					material={materials["noir_mat.001"]}
					position={[-1.443, 1.896, -3.647]}
				/>
				<group
					name="twig001"
					position={[-1.938, 0.231, -3.706]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig003"
						geometry={nodes.twig003.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig003_1"
						geometry={nodes.twig003_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<group
					name="twig002"
					position={[-1.941, 0.231, -3.696]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig004"
						geometry={nodes.twig004.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig004_1"
						geometry={nodes.twig004_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<group
					name="twig006"
					position={[-1.949, 0.231, -3.73]}
					rotation={[-Math.PI, 0, -Math.PI]}
				>
					<mesh
						name="twig005"
						geometry={nodes.twig005.geometry}
						material={materials["leaf_root.001"]}
					/>
					<mesh
						name="twig005_1"
						geometry={nodes.twig005_1.geometry}
						material={materials["leaf.001"]}
					/>
				</group>
				<mesh
					name="twig_fluffy002"
					geometry={nodes.twig_fluffy002.geometry}
					material={materials["flower.002"]}
					position={[-1.938, 0.231, -3.706]}
					rotation={[-Math.PI, 0, -Math.PI]}
				/>
				<mesh
					name="lod2001"
					geometry={nodes.lod2001.geometry}
					material={materials["baseball.001"]}
					position={[-1.254, 0.754, -3.752]}
					rotation={[-Math.PI, 0.007, -Math.PI]}
				/>
				<group
					name="Alarm_Clock002"
					position={[-1.478, 0.799, -3.692]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						name="Cylinder091"
						geometry={nodes.Cylinder091.geometry}
						material={materials["Material.105"]}
					/>
					<mesh
						name="Cylinder091_1"
						geometry={nodes.Cylinder091_1.geometry}
						material={materials["Clock Black.001"]}
					/>
					<mesh
						name="Cylinder091_2"
						geometry={nodes.Cylinder091_2.geometry}
						material={materials["Clock Steel.001"]}
					/>
				</group>
				<mesh
					name="Hour_Hand001"
					geometry={nodes.Hour_Hand001.geometry}
					material={materials["Clock Black.001"]}
					position={[-1.489, 0.805, -3.665]}
					rotation={[-Math.PI, 0, 2.093]}
				/>
				<mesh
					name="Minute_Hand001"
					geometry={nodes.Minute_Hand001.geometry}
					material={materials["Clock Black.001"]}
					position={[-1.467, 0.805, -3.665]}
					rotation={[Math.PI, 0, -2.153]}
				/>
				<instancedMesh
					args={[
						nodes.Phillips_Pan_Head_Screw033.geometry,
						materials["MI_screw_T.001"],
						10,
					]}
					name="Phillips_Pan_Head_Screw033"
					instanceMatrix={nodes.Phillips_Pan_Head_Screw033.instanceMatrix}
				/>
				<instancedMesh
					args={[
						nodes.Phillips_Pan_Head_Screw034.geometry,
						materials["MI_screw_T.001"],
						24,
					]}
					name="Phillips_Pan_Head_Screw034"
					instanceMatrix={nodes.Phillips_Pan_Head_Screw034.instanceMatrix}
				/>
			</e.group>
		</group>
	);
}

useGLTF.preload("/roomscaledgogo-v1-transformed.glb");
