/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/testroom-v1.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props) {
	const { nodes, materials } = useGLTF("/testroom-v1.glb");
	const textureGlassMaterial = new THREE.MeshStandardMaterial({
		transparent: true,
		color: "lightgrey",
		opacity: 0.8,
	});

	return (
		<group {...props} dispose={null}>
			<group position={[0.598, 0.777, -3.827]}>
				<mesh
					geometry={nodes.Cylinder007_1.geometry}
					material={materials.MSI_Grau_Back}
				/>
				<mesh
					geometry={nodes.Cylinder007_2.geometry}
					material={materials.MSI_Grau_Back}
				/>
				<mesh
					geometry={nodes.Cylinder007_3.geometry}
					material={materials.Fuss_grau}
				/>
				<mesh
					geometry={nodes.Cylinder007_4.geometry}
					material={materials.Fuss_rot}
				/>
				<mesh
					geometry={nodes.Cylinder007_5.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_6.geometry}
					material={materials["Material.015"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_7.geometry}
					material={materials["Material.004"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_8.geometry}
					material={materials["Material.015"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_9.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_10.geometry}
					material={materials["Material.007"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_11.geometry}
					material={materials["29113998"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_12.geometry}
					material={materials["Gehäuse_grau.Stecker"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_13.geometry}
					material={materials["Material.016"]}
				/>
				<mesh
					geometry={nodes.Cylinder007_14.geometry}
					material={materials.Screen}
				/>
			</group>
			<group position={[1.248, 0.771, -3.461]}>
				<group position={[0, 0.014, -0.146]} rotation={[-0.263, 0, 0]}>
					<group position={[0, -0.007, 0]} rotation={[1.572, 0, 0]}>
						<mesh
							geometry={nodes.Cube016.geometry}
							material={materials.body}
						/>
						<mesh
							geometry={nodes.Cube016_1.geometry}
							material={materials["black.004"]}
						/>
						<mesh
							geometry={nodes.Cube016_2.geometry}
							material={materials.screen}
						/>
						<mesh
							geometry={nodes.Cube016_3.geometry}
							material={materials.dark}
						/>
						<mesh
							geometry={nodes.Cube016_4.geometry}
							material={materials["glass.002"]}
						/>
						<mesh
							geometry={nodes.Cube016_5.geometry}
							material={materials["Material.022"]}
						/>
						<mesh
							geometry={nodes.Cube016_6.geometry}
							material={materials["Material.023"]}
						/>
						<mesh
							geometry={nodes.Cube016_7.geometry}
							material={materials["glass.003"]}
						/>
						<mesh
							geometry={nodes.Cube016_8.geometry}
							material={materials["Apple-logo"]}
						/>
						<mesh
							geometry={nodes.Cube016_9.geometry}
							material={materials["black.001"]}
						/>
						<mesh
							geometry={nodes.Cube016_10.geometry}
							material={materials.key}
						/>
						<mesh
							geometry={nodes.Cube016_11.geometry}
							material={materials["key.002"]}
						/>
						<mesh
							geometry={nodes.Cube016_12.geometry}
							material={materials["black.002"]}
						/>
						<mesh
							geometry={nodes.Cube016_13.geometry}
							material={materials["black.003"]}
						/>
						<mesh
							geometry={nodes.Cube016_14.geometry}
							material={materials["Material.021"]}
						/>
						<mesh
							geometry={nodes.Cube016_15.geometry}
							material={materials.Dark}
						/>
						<mesh
							geometry={nodes.Cube016_16.geometry}
							material={materials["Material.024"]}
						/>
					</group>
					<mesh
						geometry={nodes.Text001.geometry}
						material={materials["Material.019"]}
						position={[0.001, 0.009, 0]}
						rotation={[1.571, 0, 0]}
					/>
				</group>
			</group>
			<group
				position={[0.544, 0.777, -3.452]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group
					position={[-0.139, 0.027, 0.012]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<mesh
						geometry={nodes.Cube028_1.geometry}
						material={materials["Keychron K8 Pro - Other"]}
					/>
					<mesh
						geometry={nodes.Cube028_2.geometry}
						material={materials["Keychron K8 Pro - Text"]}
					/>
					<mesh
						geometry={nodes.Cube028_3.geometry}
						material={materials["Keychron K8 Pro - Switches"]}
					/>
					<mesh
						geometry={nodes.Cube028_4.geometry}
						material={materials["Keychron K8 Pro - Plate"]}
					/>
					<mesh
						geometry={nodes.Cube028_5.geometry}
						material={materials["Keychron K8 Pro - Black Keycaps"]}
					/>
					<mesh
						geometry={nodes.Cube028_6.geometry}
						material={materials["Keychron K8 Pro - Blue Keycaps"]}
					/>
					<mesh
						geometry={nodes.Cube028_7.geometry}
						material={materials["Keychron K8 Pro - Red Keycaps"]}
					/>
					<mesh
						geometry={nodes.Cube028_8.geometry}
						material={materials["Keychron K8 Pro - Green Light"]}
					/>
					<mesh
						geometry={nodes.Cube028_9.geometry}
						material={materials["Keychron K8 Pro - Plate"]}
					/>
					<mesh
						geometry={nodes.Cube028_10.geometry}
						material={materials["Keychron K8 Pro - Rubber"]}
					/>
					<mesh
						geometry={nodes.Cube028_11.geometry}
						material={materials["Keychron K8 Pro - USB Type C"]}
					/>
					<mesh
						geometry={nodes.Cube028_12.geometry}
						material={materials["Keychron K8 Pro - USB Type C"]}
					/>
				</group>
			</group>
			<group
				position={[-3.947, 2.054, -1.839]}
				rotation={[0, Math.PI / 2, 0]}
			>
				<mesh
					geometry={nodes.win_doubleShort_1.geometry}
					material={materials.win_aluminium_frame}
				/>
				<mesh
					geometry={nodes.win_doubleShort_2.geometry}
					material={materials.win_rubber}
				/>
				<mesh
					geometry={nodes.win_doubleShort_3.geometry}
					material={materials.win_RAL7024}
				/>
				<mesh
					geometry={nodes.win_doubleShort_4.geometry}
					material={materials.win_glass}
				/>
				<mesh
					geometry={nodes.win_doubleShort_5.geometry}
					material={materials.win_blinds}
				/>
			</group>
			<group position={[-1.29, 2.054, -2.57]} rotation={[0, Math.PI / 2, 0]}>
				<group position={[1.406, 0, 3.251]} rotation={[0, -Math.PI / 2, 0]}>
					<mesh
						geometry={nodes.win_doubleShort_1.geometry}
						material={materials.win_aluminium_frame}
					/>
					<mesh
						geometry={nodes.win_doubleShort_2.geometry}
						material={materials.win_rubber}
					/>
					<mesh
						geometry={nodes.win_doubleShort_3.geometry}
						material={materials.win_RAL7024}
					/>
					<mesh
						geometry={nodes.win_doubleShort_4.geometry}
						material={materials.win_glass}
					/>
					<mesh
						geometry={nodes.win_doubleShort_5.geometry}
						material={materials.win_blinds}
					/>
				</group>
			</group>
			<group
				position={[-1.567, 0.1, -3.661]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group
					position={[-0.444, 0.104, -0.156]}
					rotation={[-Math.PI / 2, Math.PI / 2, 0]}
				>
					<mesh
						geometry={nodes.pin_1.geometry}
						material={materials["29113998"]}
					/>
					<mesh
						geometry={nodes.pin_2.geometry}
						material={materials["MDF Antiqua - Guaraarapes"]}
					/>
				</group>
			</group>
			<group
				position={[2.205, 0.1, -3.519]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Vase.geometry}
					material={materials["Flower Vase_Color"]}
					position={[-0.27, 0, 0]}
				/>
			</group>
			<group
				position={[-0.534, 0.1, -3.781]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group position={[0, 0.008, 0]}>
					<mesh
						geometry={nodes.Cube031.geometry}
						material={materials["Metal wire mesh.001"]}
					/>
					<mesh
						geometry={nodes.Cube031_1.geometry}
						material={materials["paper.001"]}
					/>
					<mesh
						geometry={nodes.Cube031_2.geometry}
						material={materials["Metal wire mesh"]}
					/>
				</group>
			</group>
			<group position={[0.868, 0.777, -3.463]}>
				<mesh
					geometry={nodes.MouseThermaltakeBlack.geometry}
					material={materials["Material.032"]}
					position={[0, 0.015, -0.027]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack001.geometry}
					material={materials["29113998"]}
					position={[-0.015, 0.019, 0.012]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack002.geometry}
					material={materials["Material.036"]}
					position={[-0.021, 0.015, -0.008]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						geometry={nodes.MouseThermaltakeBlack003_1.geometry}
						material={materials["main body"]}
					/>
					<mesh
						geometry={nodes.MouseThermaltakeBlack003_2.geometry}
						material={materials["Material.030"]}
					/>
					<mesh
						geometry={nodes.MouseThermaltakeBlack003_3.geometry}
						material={materials["Material.036"]}
					/>
					<mesh
						geometry={nodes.MouseThermaltakeBlack003_4.geometry}
						material={materials["Material.035"]}
					/>
				</group>
				<mesh
					geometry={nodes.MouseThermaltakeBlack004.geometry}
					material={materials["Material.032"]}
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack005.geometry}
					material={materials["Material.033"]}
					position={[0.001, 0, 0.002]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack007.geometry}
					material={materials["Material.032"]}
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack008.geometry}
					material={materials["main body.001"]}
					position={[0.003, 0.015, -0.027]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack009.geometry}
					material={materials["main body"]}
					position={[0.001, 0.01, 0.002]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack010.geometry}
					material={materials["Material.031"]}
					position={[-0.017, 0.019, 0.006]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack011.geometry}
					material={materials["main body"]}
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack012.geometry}
					material={materials["Material.025"]}
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack013.geometry}
					material={materials["Material.025"]}
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.MouseThermaltakeBlack014.geometry}
					material={materials["Material.028"]}
					position={[0, 0.015, -0.027]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<group
					position={[-0.006, 0.011, -0.01]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						geometry={nodes.MouseThermaltakeBlack015_1.geometry}
						material={materials["Material.025"]}
					/>
					<mesh
						geometry={nodes.MouseThermaltakeBlack015_2.geometry}
						material={materials["Material.030"]}
					/>
					<mesh
						geometry={nodes.MouseThermaltakeBlack015_3.geometry}
						material={materials["main body"]}
					/>
				</group>
			</group>
			<group position={[1.777, 0.877, -4]} rotation={[Math.PI / 2, 0, 0]}>
				<group
					position={[0, 0.004, 0]}
					rotation={[Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
			</group>
			<group
				position={[-4, 1.103, -2.026]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			>
				<group
					position={[0, 0.004, 0]}
					rotation={[Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
			</group>
			<group
				position={[-4, 0.753, 2.602]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			>
				<group
					position={[0, 0.004, 0]}
					rotation={[Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						geometry={nodes.Cube129.geometry}
						material={materials["Outlet_White Plastic 2.004"]}
					/>
					<mesh
						geometry={nodes.Cube129_1.geometry}
						material={materials["Material.038"]}
					/>
				</group>
			</group>
			<group
				position={[2.523, 0.63, 1.45]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Black_Bishop_C8.geometry}
					material={materials["Black.001"]}
					position={[-0.083, 0.018, -0.193]}
				/>
				<mesh
					geometry={nodes.Black_Bishop_F8.geometry}
					material={materials["Black.001"]}
					position={[0.083, 0.018, -0.193]}
				/>
				<mesh
					geometry={nodes.Black_Horse_B8.geometry}
					material={materials.BlackHorse}
					position={[-0.138, 0.018, -0.193]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh
					geometry={nodes.Black_Horse_G8.geometry}
					material={materials.BlackHorse}
					position={[0.138, 0.018, -0.193]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh
					geometry={nodes.White_Horse_B1.geometry}
					material={materials.WhiteHorse}
					position={[-0.138, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_Horse_G1.geometry}
					material={materials.WhiteHorse}
					position={[0.138, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.Black_King.geometry}
					material={materials["Black.001"]}
					position={[0.028, 0.018, -0.193]}
				/>
				<mesh
					geometry={nodes.Black_Pawns.geometry}
					material={materials["Black.001"]}
					position={[-0.193, 0.018, -0.138]}
				/>
				<mesh
					geometry={nodes.White_Pawns.geometry}
					material={materials.LightWood}
					position={[-0.193, 0.018, 0.138]}
				/>
				<mesh
					geometry={nodes.Black_Queen.geometry}
					material={materials["Black.001"]}
					position={[-0.028, 0.018, -0.193]}
				/>
				<mesh
					geometry={nodes.Black_Rook_A8.geometry}
					material={materials["Black.001"]}
					position={[-0.193, 0.018, -0.193]}
				/>
				<mesh
					geometry={nodes.Black_Rook_H8.geometry}
					material={materials["Black.001"]}
					position={[0.193, 0.018, -0.193]}
				/>
				<group position={[0, 0.018, 0]}>
					<mesh
						geometry={nodes.Plane.geometry}
						material={materials.White}
					/>
					<mesh
						geometry={nodes.Plane_1.geometry}
						material={materials.DarkWood}
					/>
				</group>
				<mesh
					geometry={nodes.White_Bishop_C1.geometry}
					material={materials.LightWood}
					position={[-0.083, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_Bishop_F1.geometry}
					material={materials.LightWood}
					position={[0.083, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_king.geometry}
					material={materials.LightWood}
					position={[0.028, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_Queen.geometry}
					material={materials.LightWood}
					position={[-0.028, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_Rook_A1.geometry}
					material={materials.LightWood}
					position={[-0.193, 0.018, 0.193]}
				/>
				<mesh
					geometry={nodes.White_Rook_H1.geometry}
					material={materials.LightWood}
					position={[0.193, 0.018, 0.193]}
				/>
			</group>
			<group position={[-1.392, 0.1, 0.888]} rotation={[0, -Math.PI / 2, 0]}>
				<mesh
					geometry={nodes.Cube028.geometry}
					material={materials["Fabric 05.004"]}
					position={[-0.525, 0.415, -0.589]}
					rotation={[Math.PI, 1, 2.41]}
				/>
				<mesh
					geometry={nodes.Cube029.geometry}
					material={materials["Fabric 05.004"]}
					position={[0.794, 0.42, -0.22]}
					rotation={[0, 0.397, -0.732]}
				/>
				<mesh
					geometry={nodes.Plane016.geometry}
					material={materials["Material.039"]}
					position={[1.021, 0.202, 0.104]}
				/>
				<group position={[0.846, 0.045, -0.255]} rotation={[0, 0.412, 0]}>
					<mesh
						geometry={nodes.Plane041.geometry}
						material={materials["Fabric 05.004"]}
					/>
					<mesh
						geometry={nodes.Plane041_1.geometry}
						material={materials["Material.040"]}
					/>
				</group>
				<mesh
					geometry={nodes.Plane018.geometry}
					material={materials["Material.041"]}
					position={[0.879, 0.315, 0.219]}
				/>
				<group position={[0.916, 0.045, 0.219]}>
					<mesh
						geometry={nodes.Plane045.geometry}
						material={materials["Fabric 05.004"]}
					/>
					<mesh
						geometry={nodes.Plane045_1.geometry}
						material={materials["Material.040"]}
					/>
				</group>
			</group>
			<group
				position={[-2.313, 0.539, 0.482]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Back_Glass001.geometry}
					material={materials["Phone Color Logo Blue"]}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Back_Lenses001.geometry}
					material={materials["Lenses Glass"]}
					position={[0.011, 0.001, -0.049]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Bottom_Screws001.geometry}
					material={materials.Metal}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Camera_Bump001.geometry}
					material={materials["Phone Color Logo Blue"]}
					position={[0.017, 0.003, -0.054]}
					rotation={[0.021, 0, 0]}
				/>
				<group position={[0.018, 0.001, -0.055]} rotation={[0.021, 0, 0]}>
					<mesh
						geometry={nodes.Circle010.geometry}
						material={materials["Phone Color Logo Blue"]}
					/>
					<mesh
						geometry={nodes.Circle010_1.geometry}
						material={materials["Glossy Black"]}
					/>
				</group>
				<mesh
					geometry={nodes.Cameras_Glass003.geometry}
					material={materials["Glossy Black Cameras"]}
					position={[0.018, 0.001, -0.055]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Cameras_Glass004.geometry}
					material={materials.Glass}
					position={[0.018, 0.001, -0.055]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Cameras_Glass005.geometry}
					material={materials.Glass}
					position={[0.018, 0.001, -0.055]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Earpiece001.geometry}
					material={materials["Black Metal"]}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Flash_Glass001.geometry}
					material={materials.Flash}
					position={[0.01, 0.002, -0.063]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Front_Camera_Lenses001.geometry}
					material={materials["Lenses Glass"]}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<group position={[0, 0.005, 0]} rotation={[0.021, 0, 0]}>
					<mesh
						geometry={nodes.Cube042_1.geometry}
						material={materials.Metal}
					/>
					<mesh
						geometry={nodes.Cube042_2.geometry}
						material={materials["Gold Metal"]}
					/>
				</group>
				<mesh
					geometry={nodes.Object002.geometry}
					material={materials["Grill.002"]}
					position={[0.017, 0.003, -0.054]}
					rotation={[0.021, 0, 0]}
				/>
				<group position={[0, 0.005, 0]} rotation={[0.021, 0, 0]}>
					<mesh
						geometry={nodes.Cube041_1.geometry}
						material={materials["Phone Color Logo Blue"]}
					/>
					<mesh
						geometry={nodes.Cube041_2.geometry}
						material={materials["Glossy Black"]}
					/>
					<mesh
						geometry={nodes.Cube041_3.geometry}
						material={materials.Display}
					/>
					<mesh
						geometry={nodes.Cube041_4.geometry}
						material={materials["Phone Color Logo Blue"]}
					/>
				</group>
				<mesh
					geometry={nodes.Screen_Glass001.geometry}
					material={materials.Glass}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Side_Buttons001.geometry}
					material={materials["Phone Color Logo Blue"]}
					position={[-0.002, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.SIM_Card_Tray001.geometry}
					material={materials["Phone Color Logo Blue"]}
					position={[0, 0.005, 0]}
					rotation={[0.021, 0, 0]}
				/>
				<mesh
					geometry={nodes.Speakers_Grill001.geometry}
					material={materials.Grill}
					position={[0.002, 0.004, 0.073]}
					rotation={[0.021, 0, 0]}
				/>
			</group>
			<group
				position={[-2.414, 0.539, 1.212]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Circle.geometry}
					material={materials["29113998"]}
					rotation={[Math.PI, -1.471, Math.PI]}
				/>
				<mesh
					geometry={nodes.Cylinder007.geometry}
					material={materials["Material.042"]}
					position={[0.003, 0.036, -0.029]}
					rotation={[Math.PI, -1.471, 0.595]}
				/>
				<mesh
					geometry={nodes.Cylinder008.geometry}
					material={materials["Layered Glass"]}
					position={[0.003, 0.036, -0.029]}
					rotation={[Math.PI, -1.471, 0.595]}
				/>
			</group>
			<group
				position={[-2.645, 0.539, 1.359]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group position={[0, 0.022, 0]}>
					<mesh
						geometry={nodes.Cylinder053.geometry}
						material={materials["Ashtray - Black Plastic"]}
					/>
					<mesh
						geometry={nodes.Cylinder053_1.geometry}
						material={materials["Ashtray - Chrome"]}
					/>
					<mesh
						geometry={nodes.Cylinder053_2.geometry}
						material={materials["Ashtray - Brass"]}
					/>
					<mesh
						geometry={nodes.Cylinder053_3.geometry}
						material={materials["Ashtray - Steel brushed"]}
					/>
				</group>
			</group>
			<group
				position={[-2.336, 0.539, 0.956]}
				rotation={[-Math.PI, 0.262, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cylinder072.geometry}
					material={materials["ZenUV_Generic_Material.002"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_1.geometry}
					material={materials["XBOX ONE CONTROLLER"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_2.geometry}
					material={materials["Material.074"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_3.geometry}
					material={materials["TRIGGER BUTTONS "]}
				/>
				<mesh
					geometry={nodes.Cylinder072_4.geometry}
					material={materials["Material_Base.002"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_5.geometry}
					material={materials["ZenUV_Generic_Material.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_6.geometry}
					material={materials["dotted withe.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_7.geometry}
					material={materials["ZenUV_Generic_Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_8.geometry}
					material={materials["ZenUV_Generic_Material.004"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_9.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_10.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_11.geometry}
					material={materials["29113998"]}
				/>
				<mesh
					geometry={nodes.Cylinder072_12.geometry}
					material={materials["Material.075"]}
				/>
			</group>
			<group
				position={[-2.316, 0.539, 0.774]}
				rotation={[-Math.PI, 0.698, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cylinder038.geometry}
					material={materials["ZenUV_Generic_Material.002"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_1.geometry}
					material={materials["XBOX ONE CONTROLLER"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_2.geometry}
					material={materials["Material.074"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_3.geometry}
					material={materials["TRIGGER BUTTONS "]}
				/>
				<mesh
					geometry={nodes.Cylinder038_4.geometry}
					material={materials["Material_Base.002"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_5.geometry}
					material={materials["ZenUV_Generic_Material.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_6.geometry}
					material={materials["dotted withe.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_7.geometry}
					material={materials["ZenUV_Generic_Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_8.geometry}
					material={materials["ZenUV_Generic_Material.004"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_9.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_10.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_11.geometry}
					material={materials["29113998"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_12.geometry}
					material={materials["Material.075"]}
				/>
			</group>
			<group position={[-2.618, 0.539, 0.611]}>
				<group position={[-0.169, 0.057, 0]} rotation={[0, 0, 0.891]}>
					<mesh
						geometry={nodes.dust_cover.geometry}
						material={textureGlassMaterial}
					/>

					<mesh
						geometry={nodes.fastening_2.geometry}
						material={materials["grungy metal"]}
						rotation={[0, 1.571, 0]}
					/>
				</group>
				<group position={[0, 0.053, 0]}>
					<mesh
						geometry={nodes.Cube100.geometry}
						material={materials.veneer}
					/>
					<mesh
						geometry={nodes.Cube100_1.geometry}
						material={materials["veneer (side)"]}
					/>
					<mesh
						geometry={nodes.engine.geometry}
						material={materials["black glossy"]}
						position={[0.002, 0.008, 0.031]}
					/>
					<mesh
						geometry={nodes.thorn.geometry}
						material={materials["grungy metal"]}
						position={[0.002, 0.021, 0.031]}
					/>
					<group position={[0.069, 0.021, -0.171]}>
						<mesh
							geometry={nodes.Cylinder057.geometry}
							material={materials["black matte"]}
						/>
						<mesh
							geometry={nodes.Cylinder057_1.geometry}
							material={materials["grungy metal"]}
						/>
					</group>
					<group position={[0.104, 0.021, -0.171]}>
						<mesh
							geometry={nodes.Cylinder057.geometry}
							material={materials["black matte"]}
						/>
						<mesh
							geometry={nodes.Cylinder057_1.geometry}
							material={materials["grungy metal"]}
						/>
					</group>
				</group>
				<mesh
					geometry={nodes.legs.geometry}
					material={materials["black glossy"]}
				/>
				<mesh
					geometry={nodes.pickup001.geometry}
					material={materials["black matte"]}
					position={[-0.145, 0.1, -0.13]}
					rotation={[0, 0, -Math.PI / 2]}
				/>
				<group
					position={[-0.145, 0.1, -0.13]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						geometry={nodes.Cylinder059.geometry}
						material={materials["grungy metal"]}
					/>
					<mesh
						geometry={nodes.Cylinder059_1.geometry}
						material={materials["black matte"]}
					/>
					<mesh
						geometry={nodes.Cylinder059_2.geometry}
						material={materials["pink plastik"]}
					/>
				</group>
				<mesh
					geometry={nodes.piece.geometry}
					material={materials["black glossy"]}
					position={[-0.081, 0.067, -0.147]}
				>
					<mesh
						geometry={nodes.tuning_handle_3.geometry}
						material={materials["black matte"]}
						position={[0.052, 0.001, 0]}
					/>
				</mesh>
				<group position={[0.002, 0.074, 0.031]}>
					<mesh
						geometry={nodes.Cylinder056.geometry}
						material={materials.fabric}
					/>
					<mesh
						geometry={nodes.Cylinder056_1.geometry}
						material={materials["grungy metal"]}
					/>
				</group>
			</group>
			<group position={[-1.592, 1.362, -3.595]}>
				<mesh
					geometry={nodes.AV40_Speaker_Left.geometry}
					material={materials.noir_mat}
					position={[-0.165, 0, -0.056]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						geometry={nodes.AV40_Speaker_Left_AC_select.geometry}
						material={materials.rouge_mat}
						position={[0.029, -0.086, -0.038]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.AV40_Speaker_Left_stickers004.geometry}
							material={materials["Layered Glass"]}
							position={[0.011, -0.002, 0.002]}
							rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
						/>
						<mesh
							geometry={nodes.AV40_Speaker_Left_stickers006.geometry}
							material={materials["Layered Glass"]}
							position={[-0.002, -0.002, 0.002]}
							rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
						/>
					</mesh>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Bass_Switch.geometry}
						material={materials.noir_mat}
						position={[0.042, -0.086, -0.114]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<group
						position={[-0.012, -0.081, -0.038]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube123.geometry}
							material={materials.gris_fonce_mat}
						/>
						<mesh
							geometry={nodes.Cube123_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<group
						position={[-0.012, -0.081, -0.038]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube122.geometry}
							material={materials.gris_fonce_mat}
						/>
						<mesh
							geometry={nodes.Cube122_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Fuse.geometry}
						material={materials.gris_fonce_mat}
						position={[-0.042, -0.087, -0.037]}
						rotation={[-Math.PI / 2, 0, 0.865]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Fuse_hole.geometry}
						material={materials.gris_fonce_mat}
						position={[-0.042, -0.087, -0.037]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_Red_hole.geometry}
						material={materials.gris_fonce_mat}
						position={[0.041, -0.086, -0.152]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_White_hole.geometry}
						material={materials.gris_fonce_mat}
						position={[0.041, -0.086, -0.167]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_Red_metal.geometry}
						material={materials["metal.002"]}
						position={[0.041, -0.086, -0.152]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_White_Metal.geometry}
						material={materials["metal.002"]}
						position={[0.041, -0.086, -0.167]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_Red_Plug.geometry}
						material={materials.rouge_mat}
						position={[0.041, -0.086, -0.152]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Line_White_plug.geometry}
						material={materials.blanc}
						position={[0.041, -0.086, -0.167]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Power_hole.geometry}
						material={materials.gris_fonce_mat}
						position={[-0.042, -0.081, -0.06]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<group
						position={[-0.042, -0.081, -0.06]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube113.geometry}
							material={materials.noir_mat}
						/>
						<mesh
							geometry={nodes.Cube113_1.geometry}
							material={materials.blanc}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Serial_number.geometry}
						material={materials["Material.086"]}
						position={[0.014, -0.086, -0.08]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_stickers001.geometry}
						material={materials["Layered Glass"]}
						position={[-0.056, 0.096, -0.011]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_stickers002.geometry}
						material={materials["Layered Glass"]}
						position={[0.05, 0.096, -0.012]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Left_stickers003.geometry}
						material={materials["Layered Glass"]}
						position={[0.06, 0.096, -0.012]}
					/>
					<group
						position={[0.041, -0.086, -0.211]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube112.geometry}
							material={materials.gris_fonce_mat}
						/>
						<mesh
							geometry={nodes.Cube112_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<group
						position={[0.041, -0.086, -0.192]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube112.geometry}
							material={materials.gris_fonce_mat}
						/>
						<mesh
							geometry={nodes.Cube112_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Left_Volume.geometry}
						material={materials.noir_mat}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back.geometry}
						material={materials.noir_back_left}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw.geometry}
						material={materials.MI_screw_T}
						position={[-0.038, -0.087, -0.158]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw011.geometry}
						material={materials.MI_screw_T}
						position={[0.014, -0.087, -0.146]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw013.geometry}
						material={materials.MI_screw_T}
						position={[-0.038, -0.087, -0.193]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw029.geometry}
						material={materials.MI_screw_T}
						position={[0.035, -0.087, -0.137]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw030.geometry}
						material={materials.MI_screw_T}
						position={[0.037, -0.087, -0.069]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw031.geometry}
						material={materials.MI_screw_T}
						position={[-0.011, -0.087, -0.069]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw032.geometry}
						material={materials.MI_screw_T}
						position={[0.012, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw033.geometry}
						material={materials.MI_screw_T}
						position={[0.048, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, Math.PI / 2]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw001.geometry}
						material={materials.MI_screw_T}
						position={[-0.039, -0.087, -0.208]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw002.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.19]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw003.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.114]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw004.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw005.geometry}
						material={materials.MI_screw_T}
						position={[-0.039, -0.087, -0.018]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw006.geometry}
						material={materials.MI_screw_T}
						position={[0.04, -0.087, -0.208]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw007.geometry}
						material={materials.MI_screw_T}
						position={[0.04, -0.087, -0.018]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw008.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.19]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw009.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.114]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw010.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw012.geometry}
						material={materials.MI_screw_T}
						position={[-0.019, -0.087, -0.08]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw028.geometry}
						material={materials.MI_screw_T}
						position={[-0.018, -0.087, -0.146]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Grid001.geometry}
						material={materials["Metal wire mesh.002"]}
						position={[0, 0.09, -0.132]}
					/>
					<group position={[0.01, 0.097, -0.012]}>
						<mesh
							geometry={nodes.Curve003.geometry}
							material={materials["metal.002"]}
						/>
						<mesh
							geometry={nodes.Curve003_1.geometry}
							material={materials.noir_mat}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Medium_Center001.geometry}
						material={materials.noir_mat}
						position={[0, 0.082, -0.08]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={
							nodes.AV40_Speaker_Right_Medium_Membrane001.geometry
						}
						material={materials.noir_mat}
					/>
					<group
						position={[-0.039, -0.084, -0.176]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cube105.geometry}
							material={materials.noir_mat}
						/>
						<mesh
							geometry={nodes.Cube105_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<group
						position={[-0.039, -0.083, -0.176]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cube104.geometry}
							material={materials.noir_mat}
						/>
						<mesh
							geometry={nodes.Cube104_1.geometry}
							material={materials.rouge_mat}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Shinny_Front001.geometry}
						material={materials.noir_brillant}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Twitter_Center001.geometry}
						material={materials.noir_mat}
						position={[0, 0.083, -0.183]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Woofer.geometry}
						material={materials.noir_brillant}
						position={[0, -0.099, -0.177]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Woofer_Inside001.geometry}
						material={materials.noir_brillant}
						position={[0, 0, -0.177]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.Cube119.geometry}
						material={materials.gris_mat}
					/>
					<mesh
						geometry={nodes.Cube119_1.geometry}
						material={materials["metal.002"]}
					/>
					<mesh
						geometry={nodes.Cube101.geometry}
						material={materials.blanc}
					/>
					<mesh
						geometry={nodes.Cube101_1.geometry}
						material={materials["Material.084"]}
					/>
				</mesh>
				<mesh
					geometry={nodes.AV40_Speaker_Right.geometry}
					material={materials.noir_mat}
					position={[0.178, 0, -0.056]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw026.geometry}
						material={materials.MI_screw_T}
						position={[0.018, -0.087, -0.117]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw027.geometry}
						material={materials.MI_screw_T}
						position={[-0.017, -0.087, -0.117]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw014.geometry}
						material={materials.MI_screw_T}
						position={[-0.039, -0.087, -0.208]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw015.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.19]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw016.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.114]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw017.geometry}
						material={materials.MI_screw_T}
						position={[-0.06, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw018.geometry}
						material={materials.MI_screw_T}
						position={[-0.039, -0.087, -0.018]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw019.geometry}
						material={materials.MI_screw_T}
						position={[0.04, -0.087, -0.208]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw020.geometry}
						material={materials.MI_screw_T}
						position={[0.04, -0.087, -0.018]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw021.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.19]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw022.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.114]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw023.geometry}
						material={materials.MI_screw_T}
						position={[0.061, -0.087, -0.036]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw024.geometry}
						material={materials.MI_screw_T}
						position={[0.018, -0.087, -0.085]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back_Screw025.geometry}
						material={materials.MI_screw_T}
						position={[-0.018, -0.087, -0.085]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Grid.geometry}
						material={materials["Metal wire mesh.002"]}
						position={[0, 0.09, -0.132]}
					/>
					<group position={[0.01, 0.097, -0.012]}>
						<mesh
							geometry={nodes.Curve003.geometry}
							material={materials["metal.002"]}
						/>
						<mesh
							geometry={nodes.Curve003_1.geometry}
							material={materials.noir_mat}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Medium_Center.geometry}
						material={materials.noir_mat}
						position={[0, 0.082, -0.08]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Medium_Membrane.geometry}
						material={materials.noir_mat}
					/>
					<group
						position={[0, -0.084, -0.116]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube105.geometry}
							material={materials.noir_mat}
						/>
						<mesh
							geometry={nodes.Cube105_1.geometry}
							material={materials["metal.002"]}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Woofer001.geometry}
						material={materials.noir_brillant}
						position={[0, -0.099, -0.177]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Woofer_Inside.geometry}
						material={materials.noir_brillant}
						position={[0, 0, -0.177]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Back001.geometry}
						material={materials.noir_back_right}
					/>
					<group
						position={[0, -0.083, -0.116]}
						rotation={[-Math.PI / 2, 0, 0]}
					>
						<mesh
							geometry={nodes.Cube133.geometry}
							material={materials.noir_mat}
						/>
						<mesh
							geometry={nodes.Cube133_1.geometry}
							material={materials.rouge_mat}
						/>
					</group>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Shinny_Front.geometry}
						material={materials.noir_brillant}
					/>
					<mesh
						geometry={nodes.AV40_Speaker_Right_Twitter_Center.geometry}
						material={materials.noir_mat}
						position={[0, 0.083, -0.183]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
				</mesh>
			</group>
			<group
				position={[-2.323, 2.199, -3.976]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.BezierCurve.geometry}
					material={materials["Material.081"]}
					position={[0, 0, -0.032]}
					rotation={[0, 0, Math.PI]}
				/>
				<mesh
					geometry={nodes.Cube033.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.944, -0.114, -0.03]}
					rotation={[-1.571, -1.388, 1.591]}
				>
					<mesh
						geometry={nodes["01"].geometry}
						material={materials["01"]}
						position={[0.008, 0.103, -0.001]}
						rotation={[1.492, -0.054, 1.582]}
					/>
					<mesh
						geometry={nodes.Helix.geometry}
						material={materials["metal.001"]}
						rotation={[1.596, -0.037, 0.002]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube034.geometry}
					material={materials["Rough pine board wall"]}
					position={[0.644, -0.118, -0.032]}
					rotation={[1.571, -1.462, -1.583]}
				>
					<mesh
						geometry={nodes["10"].geometry}
						material={materials["10"]}
						position={[0.002, 0.104, -0.009]}
						rotation={[1.632, 0.013, 1.575]}
					/>
					<mesh
						geometry={nodes.Helix009.geometry}
						material={materials["metal.001"]}
						rotation={[1.557, -0.012, 0.021]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube035.geometry}
					material={materials["Rough pine board wall"]}
					position={[0.469, -0.142, -0.03]}
					rotation={[1.571, -1.512, -1.577]}
				>
					<mesh
						geometry={nodes["09"].geometry}
						material={materials["09"]}
						position={[0.002, 0.105, 0.002]}
						rotation={[1.631, 0.007, 1.57]}
					/>
					<mesh
						geometry={nodes.Helix008.geometry}
						material={materials["metal.001"]}
						rotation={[1.563, -0.022, 0.035]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube036.geometry}
					material={materials["Rough pine board wall"]}
					position={[0.295, -0.16, -0.034]}
					rotation={[1.571, -1.495, -1.579]}
				>
					<mesh
						geometry={nodes["08"].geometry}
						material={materials["08"]}
						position={[0.002, 0.106, 0.009]}
						rotation={[1.501, 0.011, 1.588]}
					/>
					<mesh
						geometry={nodes.Helix007.geometry}
						material={materials["metal.001"]}
						rotation={[1.561, -0.019, 0.03]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube037.geometry}
					material={materials["Rough pine board wall"]}
					position={[0.115, -0.172, -0.035]}
					rotation={[1.571, -1.506, -1.578]}
				>
					<mesh
						geometry={nodes["07"].geometry}
						material={materials["07"]}
						position={[0.002, 0.104, -0.002]}
						rotation={[1.599, 0.008, 1.575]}
					/>
					<mesh
						geometry={nodes.Helix006.geometry}
						material={materials["metal.001"]}
						rotation={[1.562, -0.021, 0.033]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube038.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.05, -0.18, -0.035]}
					rotation={[-1.571, -1.552, 1.573]}
				>
					<mesh
						geometry={nodes["06"].geometry}
						material={materials["06"]}
						position={[0.003, 0.104, -0.001]}
						rotation={[Math.PI / 2, -0.002, 1.569]}
					/>
					<mesh
						geometry={nodes.Helix005.geometry}
						material={materials["metal.001"]}
						rotation={[1.621, -0.033, 0.001]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube039.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.219, -0.182, -0.036]}
					rotation={[-1.571, -1.538, 1.575]}
				>
					<mesh
						geometry={nodes["05"].geometry}
						material={materials["05"]}
						position={[0.003, 0.103, -0.007]}
						rotation={[1.49, -0.003, 1.576]}
					/>
					<mesh
						geometry={nodes.Helix004.geometry}
						material={materials["metal.001"]}
						rotation={[1.618, -0.033, 0.001]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube040.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.398, -0.178, -0.03]}
					rotation={[-Math.PI / 2, -1.546, 1.574]}
				>
					<mesh
						geometry={nodes["04"].geometry}
						material={materials["04"]}
						position={[0.003, 0.104, -0.006]}
						rotation={[1.585, -0.006, 1.574]}
					/>
					<mesh
						geometry={nodes.Helix003.geometry}
						material={materials["metal.001"]}
						rotation={[1.62, -0.033, 0.001]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube041.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.562, -0.169, -0.029]}
					rotation={[-1.571, -1.5, 1.579]}
				>
					<mesh
						geometry={nodes["03"].geometry}
						material={materials["03"]}
						position={[0.004, 0.104, -0.002]}
						rotation={[1.518, -0.008, 1.568]}
					/>
					<mesh
						geometry={nodes.Helix002.geometry}
						material={materials["metal.001"]}
						rotation={[1.612, -0.033, 0.001]}
					/>
				</mesh>
				<mesh
					geometry={nodes.Cube042.geometry}
					material={materials["Rough pine board wall"]}
					position={[-0.772, -0.144, -0.036]}
					rotation={[-1.571, -1.463, 1.583]}
				>
					<mesh
						geometry={nodes["02"].geometry}
						material={materials["02"]}
						position={[0.004, 0.102, -0.016]}
						rotation={[1.366, -0.011, 1.579]}
					/>
					<mesh
						geometry={nodes.Helix001.geometry}
						material={materials["metal.001"]}
						rotation={[1.606, -0.034, 0.001]}
					/>
				</mesh>
				<group
					position={[-1.205, -0.006, 0.007]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						geometry={nodes.Sphere004.geometry}
						material={materials["Material.079"]}
					/>
					<mesh
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Material.080"]}
					/>
				</group>
				<group
					position={[1.072, -0.019, 0.009]}
					rotation={[-Math.PI / 2, 0, -Math.PI]}
				>
					<mesh
						geometry={nodes.Sphere004.geometry}
						material={materials["Material.079"]}
					/>
					<mesh
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Material.080"]}
					/>
				</group>
			</group>
			<group position={[-3.3, 0.1, -2.793]}>
				<mesh geometry={nodes.Bed_low.geometry} material={materials.Base} />
				<mesh
					geometry={nodes.Cover_low.geometry}
					material={materials["Pillow and Cover"]}
				/>
				<mesh
					geometry={nodes.Pillow1_low.geometry}
					material={materials["Pillow and Cover"]}
				/>
				<mesh
					geometry={nodes.Pillow2_low.geometry}
					material={materials["Pillow and Cover"]}
				/>
				<mesh
					geometry={nodes.Structure1_low.geometry}
					material={materials.Base}
				/>
				<mesh
					geometry={nodes.Structure1_low001.geometry}
					material={materials.Structure}
				/>
				<mesh
					geometry={nodes.Structure2_low.geometry}
					material={materials.Structure}
				/>
				<mesh
					geometry={nodes.Structure3_low.geometry}
					material={materials.Structure}
				/>
			</group>
			<group
				position={[-3.66, 0.606, 2.086]}
				rotation={[0, -Math.PI / 2, 0]}
			>
				<group position={[0, 0.045, 0]}>
					<group position={[-0.002, 0.01, 0.016]}>
						<mesh
							geometry={nodes.Cube069.geometry}
							material={materials["Electro Panel"]}
						/>
						<mesh
							geometry={nodes.Cube069_1.geometry}
							material={materials["Gold Metal.001"]}
						/>
					</group>
					<group position={[0.032, 0.01, 0.001]}>
						<mesh
							geometry={nodes.Cube068.geometry}
							material={materials["Electro Panel"]}
						/>
						<mesh
							geometry={nodes.Cube068_1.geometry}
							material={materials["Gold Metal.001"]}
						/>
					</group>
					<mesh
						geometry={nodes.Circle003.geometry}
						material={materials["Grey Matt Plactic"]}
						position={[0.015, 0.008, -0.027]}
					/>
					<mesh
						geometry={nodes.CoverBottom.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.01, -0.032]}
					/>
					<mesh
						geometry={nodes.CoverFront.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.01, -0.032]}
					/>
					<mesh
						geometry={nodes.CoverSide.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.01, -0.031]}
					/>
					<mesh
						geometry={nodes.CoverTop.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.01, -0.032]}
					/>
					<mesh
						geometry={nodes.Cylinder027.geometry}
						material={materials["Black Matt Plactic"]}
						position={[0.015, 0.008, -0.02]}
					/>
					<group position={[0.071, 0.008, -0.017]}>
						<mesh
							geometry={nodes.Cylinder047.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cylinder047_1.geometry}
							material={materials["Glass.001"]}
						/>
					</group>
					<mesh
						geometry={nodes.Fan.geometry}
						material={materials["Glossy Plastic "]}
						position={[0.116, 0.01, 0.012]}
					/>
					<group position={[0.07, 0.008, -0.014]}>
						<mesh
							geometry={nodes.Cylinder044.geometry}
							material={materials["Grey Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cylinder044_1.geometry}
							material={materials["Black Matt Plactic"]}
						/>
					</group>
					<mesh
						geometry={nodes.IR_ProjectorCover.geometry}
						material={materials["Grey Matt Plactic"]}
						position={[0.07, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.IR_SensorCover.geometry}
						material={materials["Grey Matt Plactic"]}
						position={[-0.013, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.IR_ProjectorGlass.geometry}
						material={materials["Glass.001"]}
						position={[0.07, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.IR_SensorGlass.geometry}
						material={materials["Glass.001"]}
						position={[-0.013, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.RGB_SensorGlass.geometry}
						material={materials["Glass.001"]}
						position={[0.015, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.IR_ProjectorLens.geometry}
						material={materials["Black Matt Plactic"]}
						position={[0.071, 0.008, -0.017]}
					/>
					<mesh
						geometry={nodes.IR_Sensor.geometry}
						material={materials["Black Matt Plactic"]}
						position={[-0.013, 0.008, -0.012]}
					/>
					<mesh
						geometry={nodes.IR_SensorLens.geometry}
						material={materials["Black Matt Plactic"]}
						position={[-0.013, 0.008, -0.017]}
					/>
					<group position={[-0.013, 0.008, -0.017]}>
						<mesh
							geometry={nodes.Cylinder042.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cylinder042_1.geometry}
							material={materials["Glass.001"]}
						/>
					</group>
					<mesh
						geometry={nodes.LED.geometry}
						material={materials.LED}
						position={[0.042, 0.008, -0.032]}
					/>
					<mesh
						geometry={nodes.Metal_Frame.geometry}
						material={materials["Matt Metal"]}
						position={[0, 0.01, -0.008]}
					/>
					<mesh
						geometry={nodes.Modem.geometry}
						material={materials.Adaptor}
						position={[0.002, 0.008, -0.008]}
					/>
					<group position={[-0.06, 0.01, 0]}>
						<mesh
							geometry={nodes.Cube063.geometry}
							material={materials["Electro Panel"]}
						/>
						<mesh
							geometry={nodes.Cube063_1.geometry}
							material={materials["Gold Metal.001"]}
						/>
					</group>
					<group position={[0.055, 0.013, 0.008]}>
						<mesh
							geometry={nodes.Cube062.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cube062_1.geometry}
							material={materials["Matt Metal"]}
						/>
					</group>
					<group position={[-0.013, 0.023, 0.008]}>
						<mesh
							geometry={nodes.Cube061.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cube061_1.geometry}
							material={materials["Matt Metal"]}
						/>
					</group>
					<group position={[0.015, 0.023, 0.008]}>
						<mesh
							geometry={nodes.Cube060.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cube060_1.geometry}
							material={materials["Matt Metal"]}
						/>
					</group>
					<mesh
						geometry={nodes.RGB_Sensor.geometry}
						material={materials["Black Matt Plactic"]}
						position={[0.015, 0.008, -0.012]}
					/>
					<mesh
						geometry={nodes.RGB_SensorCover.geometry}
						material={materials["Grey Matt Plactic"]}
						position={[0.015, 0.008, -0.032]}
					/>
					<group position={[0.015, 0.008, -0.016]}>
						<mesh
							geometry={nodes.Cylinder039.geometry}
							material={materials["Black Matt Plactic"]}
						/>
						<mesh
							geometry={nodes.Cylinder039_1.geometry}
							material={materials["Grey Matt Plactic"]}
						/>
					</group>
					<mesh
						geometry={nodes.Side_AirIntake.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.01, -0.031]}
					/>
					<mesh
						geometry={nodes.SideWent.geometry}
						material={materials["Black Matt Plactic"]}
						position={[0.135, 0.01, 0.006]}
					/>
					<mesh
						geometry={nodes.Sphere001.geometry}
						material={materials["Glass.001"]}
						position={[0.015, 0.008, -0.02]}
					/>
					<mesh
						geometry={nodes.Transfer_PlaneRGB.geometry}
						material={materials["Gold Metal.001"]}
						position={[0.015, 0.025, -0.003]}
					/>
					<mesh
						geometry={nodes.Transfer_TapeIR.geometry}
						material={materials["Gold Metal.001"]}
						position={[-0.013, 0.025, -0.003]}
					/>
					<mesh
						geometry={nodes.Went.geometry}
						material={materials["Black Matt Plactic"]}
						position={[0.116, 0.01, 0.012]}
					/>
				</group>
				<mesh
					geometry={nodes.Kinect_Leg.geometry}
					material={materials["Glossy Plastic "]}
				>
					<mesh
						geometry={nodes.Pillar.geometry}
						material={materials["Glossy Plastic "]}
						position={[0, 0.033, 0]}
					/>
					<mesh
						geometry={nodes.Stand.geometry}
						material={materials["Black Matt Plactic"]}
						position={[-0.033, 0, -0.016]}
					/>
				</mesh>
			</group>
			<group
				position={[-1.444, 0.593, -3.606]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group
					position={[-0.001, 0.073, -0.002]}
					rotation={[Math.PI / 2, 0, Math.PI]}
				>
					<mesh
						geometry={nodes.Cylinder032.geometry}
						material={materials["Material.073"]}
					/>
					<mesh
						geometry={nodes.Cylinder032_1.geometry}
						material={materials["Clock Black"]}
					/>
					<mesh
						geometry={nodes.Cylinder032_2.geometry}
						material={materials["Clock Steel"]}
					/>
					<group
						position={[0.001, 0.002, 0]}
						rotation={[-Math.PI / 2, 0, 0.02]}
					>
						<mesh
							geometry={nodes.Hour_Hand.geometry}
							material={materials["Clock Black"]}
							position={[-0.009, 0.006, 0.02]}
							rotation={[-Math.PI, 0, 2.113]}
						/>
					</group>
					<group
						position={[0.001, 0.002, 0]}
						rotation={[-Math.PI / 2, 0, 0.028]}
					>
						<mesh
							geometry={nodes.Minute_Hand.geometry}
							material={materials["Clock Black"]}
							position={[0.009, 0.005, 0.02]}
							rotation={[Math.PI, 0, -2.125]}
						/>
					</group>
				</group>
			</group>
			<group position={[-1.782, 0.593, -3.652]} rotation={[0, 1.571, 0]}>
				<mesh
					geometry={nodes.Cylinder020.geometry}
					material={materials["Material.057"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_1.geometry}
					material={materials["Material.058"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_2.geometry}
					material={materials["Material.059"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_3.geometry}
					material={materials["Material.058"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_4.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_5.geometry}
					material={materials["Material.062"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_6.geometry}
					material={materials["Material.063"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_7.geometry}
					material={materials["Material.064"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_8.geometry}
					material={materials["Material.064"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_9.geometry}
					material={materials["Material.066"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_10.geometry}
					material={materials["Material.067"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_11.geometry}
					material={materials["black.004"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_12.geometry}
					material={materials["Material.069"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_13.geometry}
					material={materials["Material.057"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_14.geometry}
					material={materials["Material.071"]}
				/>
				<mesh
					geometry={nodes.Cylinder020_15.geometry}
					material={materials["Material.006"]}
				/>
			</group>
			<group
				position={[-1.263, 0.593, -3.652]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.lod2.geometry}
					material={materials.baseball}
					position={[0, 0.037, 0]}
					rotation={[0, -0.007, 0]}
				/>
			</group>
			<group
				position={[-0.134, 1.281, -3.521]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.NurbsPath001.geometry}
					material={materials["Material.056"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_1.geometry}
					material={materials["Material.047"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_2.geometry}
					material={materials["black.004"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_3.geometry}
					material={materials["Material.049"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_4.geometry}
					material={materials["Material.050"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_5.geometry}
					material={materials["Material.051"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_6.geometry}
					material={materials["Material.052"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_7.geometry}
					material={materials["Material.053"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_8.geometry}
					material={materials["Material.054"]}
				/>
				<mesh
					geometry={nodes.NurbsPath001_9.geometry}
					material={materials["Material.055"]}
				/>
			</group>
			<group
				position={[-0.247, 0.777, -3.633]}
				rotation={[0, Math.PI / 4, 0]}
			>
				<group position={[0, 0.205, -0.01]}>
					<group position={[0, -0.058, 0.022]}>
						<mesh
							geometry={nodes.Plane131.geometry}
							material={materials["Material.043"]}
						/>
						<mesh
							geometry={nodes.Plane131_1.geometry}
							material={materials["Material.045"]}
						/>
						<mesh
							geometry={nodes.Plane131_2.geometry}
							material={materials["plastic grey"]}
						/>
						<mesh
							geometry={nodes.Plane131_3.geometry}
							material={materials["Metal Wire Mesh"]}
						/>
						<mesh
							geometry={nodes.Plane131_4.geometry}
							material={materials["Fabric 02"]}
						/>
						<mesh
							geometry={nodes.Plane131_5.geometry}
							material={materials["Material.046"]}
						/>
					</group>
				</group>
				<group position={[0, 0.163, 0.013]}>
					<mesh
						geometry={nodes.Plane130.geometry}
						material={materials["Material.043"]}
					/>
					<mesh
						geometry={nodes.Plane130_1.geometry}
						material={materials["Material.045"]}
					/>
				</group>
			</group>
			<group position={[-0.201, 0.815, -3.792]} rotation={[0, -0.611, 0]}>
				<group position={[0, -0.014, -0.025]}>
					<mesh
						geometry={nodes.Cube048.geometry}
						material={materials["iPad Charger PVC"]}
					/>
					<mesh
						geometry={nodes.Cube048_1.geometry}
						material={materials["iPad Charger Metal Conductor"]}
					/>
					<group position={[0, 0, -0.515]}>
						<mesh
							geometry={nodes.Cylinder011.geometry}
							material={materials["Material.006"]}
						/>
						<mesh
							geometry={nodes.Cylinder011_1.geometry}
							material={materials["iPad Charger Metal Conductor"]}
						/>
						<mesh
							geometry={nodes.Cylinder011_2.geometry}
							material={materials["Metal Conductor Gold"]}
						/>
					</group>
					<mesh
						geometry={nodes.Wire_USB.geometry}
						material={materials["iPad Charger PVC"]}
						position={[0, 0.008, -0.039]}
					>
						<mesh
							geometry={nodes.Wire.geometry}
							material={nodes.Wire.material}
							position={[0, 0, -0.009]}
							rotation={[0, 0, Math.PI]}
						/>
					</mesh>
				</group>
			</group>
			<group position={[0, 0.1, 0]}>
				<mesh
					geometry={nodes.Plane044.geometry}
					material={materials.Wall}
				/>
				<mesh
					geometry={nodes.Plane044_1.geometry}
					material={materials.Floor}
				/>
				<mesh
					geometry={nodes.Plane044_2.geometry}
					material={materials.Edges}
				/>
			</group>
			<mesh
				geometry={nodes.Edges.geometry}
				material={materials.Edges}
				position={[0, 0.1, 0]}
			/>
			<mesh
				geometry={nodes.Floor_Laptop_Desk_80x40x45.geometry}
				material={materials["Black Powder Coating"]}
				position={[0.657, 0.1, -3.616]}
			>
				<mesh
					geometry={nodes.Plane014.geometry}
					material={materials["Pine Wood"]}
				/>
			</mesh>
			<mesh
				geometry={nodes.Text.geometry}
				material={materials.outline}
				position={[0.616, 1.818, -2.31]}
				rotation={[Math.PI / 2, 0, Math.PI]}
			/>
			<group position={[0.54, 1.56, -2.336]} rotation={[1.76, 0, Math.PI]}>
				<mesh
					geometry={nodes.Plane013_1.geometry}
					material={materials.outline}
				/>
				<mesh
					geometry={nodes.Plane013_2.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					geometry={nodes.Plane013_3.geometry}
					material={materials["black skin"]}
				/>
				<mesh
					geometry={nodes.Plane013_4.geometry}
					material={materials.Material}
				/>
				<mesh
					geometry={nodes.Plane013_5.geometry}
					material={materials["black plactic"]}
				/>
				<mesh
					geometry={nodes.Plane013_6.geometry}
					material={materials.metal}
				/>
			</group>
			<mesh
				geometry={nodes["Forty-two_books"].geometry}
				material={materials["Books.01"]}
				position={[-1.959, 0.976, -3.707]}
				rotation={[0, 1.571, 0]}
			/>
			<mesh
				geometry={nodes.Bean_Bag_chair.geometry}
				material={materials["Valvet 01"]}
				position={[2.478, 0.1, 0.293]}
				rotation={[0, 0.332, 0]}
			/>
			<mesh
				geometry={nodes.Bean_Bag_chair001.geometry}
				material={materials["Valvet 01"]}
				position={[2.478, 0.1, 2.502]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<group position={[2.145, 0.63, 1.442]} rotation={[0, -Math.PI / 2, 0]}>
				<mesh
					geometry={nodes.Cube094.geometry}
					material={materials["29113998"]}
				/>
				<mesh
					geometry={nodes.Cube094_1.geometry}
					material={materials["Chess Chronometer plastic.002"]}
				/>
				<mesh
					geometry={nodes.Cube094_2.geometry}
					material={materials["Chess Chronometer numerals"]}
				/>
				<mesh
					geometry={nodes.Cube094_3.geometry}
					material={materials["Chronometer Clock Pointer black"]}
				/>
				<mesh
					geometry={nodes.Cube094_4.geometry}
					material={materials["Chronometer Clock Pointer plastic red"]}
				/>
				<mesh
					geometry={nodes.Cube094_5.geometry}
					material={materials["Chess Chronometer  chrome"]}
				/>
			</group>
			<group position={[-4.006, 0.1, 1.254]}>
				<mesh
					geometry={nodes.Cube036_1.geometry}
					material={materials.tvunit_white}
				/>
				<mesh
					geometry={nodes.Cube036_2.geometry}
					material={materials.tvunit_handles}
				/>
				<mesh
					geometry={nodes.Cube036_3.geometry}
					material={materials.tvunit_black}
				/>
				<mesh
					geometry={nodes.Cube036_4.geometry}
					material={materials.box1}
				/>
				<mesh
					geometry={nodes.Cube036_5.geometry}
					material={materials.box2}
				/>
				<mesh
					geometry={nodes.Cube036_6.geometry}
					material={materials["tv mat"]}
				/>
				<mesh
					geometry={nodes.Cube036_7.geometry}
					material={materials["tv screen"]}
				/>
				<mesh
					geometry={nodes.Cube036_8.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					geometry={nodes.Cube036_9.geometry}
					material={materials["book covers"]}
				/>
				<mesh
					geometry={nodes.Cube036_10.geometry}
					material={materials.pic_frame}
				/>
				<mesh
					geometry={nodes.Cube036_11.geometry}
					material={materials.pic_image}
				/>
			</group>
			<mesh
				geometry={nodes.Table_Enterprise.geometry}
				material={materials.wood_table}
				position={[-2.516, 0.1, 0.847]}
				rotation={[0, 1.571, 0]}
			/>
			<group position={[-3.717, 0.606, 0.789]} rotation={[0, 1.571, 0]}>
				<mesh
					geometry={nodes["Picture_frame-01_1"].geometry}
					material={materials["Moldura de madeira.001"]}
				/>
				<mesh
					geometry={nodes["Picture_frame-01_2"].geometry}
					material={materials["29113998"]}
				/>
				<mesh
					geometry={nodes["Picture_frame-01_3"].geometry}
					material={materials["Moldura textura.003"]}
				/>
			</group>
			<mesh
				geometry={nodes.Indoor_potted_plant001.geometry}
				material={materials.ceramic_bumped_grey}
				position={[-1.81, 0.209, -3.615]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<group position={[0.009, 0.003, 0.019]}>
					<mesh
						geometry={nodes.twig002.geometry}
						material={materials.leaf_root}
					/>
					<mesh
						geometry={nodes.twig002_1.geometry}
						material={materials["leaf.002"]}
					/>
				</group>
				<group position={[0.003, 0.003, -0.008]}>
					<mesh
						geometry={nodes.twig001.geometry}
						material={materials.leaf_root}
					/>
					<mesh
						geometry={nodes.twig001_1.geometry}
						material={materials["leaf.002"]}
					/>
				</group>
				<group position={[0, 0.003, 0]}>
					<mesh
						geometry={nodes.twig.geometry}
						material={materials.leaf_root}
					/>
					<mesh
						geometry={nodes.twig_1.geometry}
						material={materials["leaf.002"]}
					/>
				</group>
				<mesh
					geometry={nodes.twig_fluffy001.geometry}
					material={materials["flower.001"]}
					position={[0, 0.003, 0]}
				/>
			</mesh>
			<mesh
				geometry={nodes.Succulent_plant.geometry}
				material={materials.porcelain}
				position={[-3.711, 0.606, 0.45]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.ground_real.geometry}
					material={materials["Mud and grass"]}
					position={[0, 0.025, 0]}
				/>
				<mesh
					geometry={nodes.succulent_plant.geometry}
					material={materials["succulent material"]}
					position={[0, 0.076, 0]}
				/>
			</mesh>
			<mesh
				geometry={nodes.Succulent_plant001.geometry}
				material={materials.porcelain}
				position={[-1.568, 0.209, -3.71]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.ground_real001.geometry}
					material={materials["Mud and grass"]}
					position={[0, 0.035, 0]}
				/>
				<mesh
					geometry={nodes.succulent_plant001.geometry}
					material={materials["succulent material"]}
					position={[0, 0.107, 0]}
				/>
			</mesh>
			<mesh
				geometry={nodes.Xbox_Series_X.geometry}
				material={materials["Material.077"]}
				position={[-3.655, 0.606, 2.428]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cube030.geometry}
					material={materials["Material.077"]}
					position={[-0.005, 0.059, -0.045]}
					rotation={[0, -1.571, 0]}
				/>
				<mesh
					geometry={nodes.Cube031_3.geometry}
					material={materials["Material.078"]}
					position={[0.004, 0.251, 0.027]}
				/>
				<mesh
					geometry={nodes.Cylinder029.geometry}
					material={materials["Material.077"]}
					position={[-0.002, 0.022, -0.044]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Cylinder030.geometry}
					material={materials["Material.077"]}
					position={[-0.002, 0.03, -0.044]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Cylinder031.geometry}
					material={materials["Material.077"]}
					position={[-0.054, 0.157, 0.102]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					geometry={nodes.Plane035.geometry}
					material={materials["Material.077"]}
					position={[-0.005, 0.097, -0.039]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Plane037.geometry}
					material={materials["Material.077"]}
					position={[-0.005, 0.075, -0.039]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Plane036.geometry}
					material={materials["Material.077"]}
					position={[-0.004, 0.097, -0.043]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Plane038.geometry}
					material={materials["Material.077"]}
					position={[-0.004, 0.075, -0.043]}
					rotation={[Math.PI / 2, -Math.PI / 2, 0]}
				/>
				<mesh
					geometry={nodes.Xbox_Series_X001.geometry}
					material={materials["Material.076"]}
					position={[-0.051, 0.275, 0.103]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
			</mesh>
			<group
				position={[-4, 3.53, 1.548]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			>
				<mesh
					geometry={nodes.Cube091.geometry}
					material={materials.PORTA_TINTA}
				/>
				<mesh
					geometry={nodes.Cube091_1.geometry}
					material={materials["Material.082"]}
				/>
				<mesh
					geometry={nodes.Cube091_2.geometry}
					material={materials.Carvalho}
				/>
				<mesh
					geometry={nodes.Cube091_3.geometry}
					material={materials.quadro_figura}
				/>
			</group>
			<group position={[-0.337, 2.549, -4]} rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Cube092.geometry}
					material={materials.PORTA_TINTA}
				/>
				<mesh
					geometry={nodes.Cube092_1.geometry}
					material={materials["Material.082"]}
				/>
				<mesh
					geometry={nodes.Cube092_2.geometry}
					material={materials.quadro2_figura}
				/>
			</group>
			<group
				position={[-0.121, 0.783, -3.527]}
				rotation={[-Math.PI, 0, -Math.PI]}
			>
				<mesh
					geometry={nodes.Plane129.geometry}
					material={materials.basic}
				/>
				<mesh
					geometry={nodes.Plane129_1.geometry}
					material={materials["black.005"]}
				/>
				<mesh
					geometry={nodes.Plane129_2.geometry}
					material={materials.metallic}
				/>
				<mesh
					geometry={nodes.Plane129_3.geometry}
					material={materials["screen.001"]}
				/>
				<mesh
					geometry={nodes.Plane129_4.geometry}
					material={materials.glass}
				/>
				<mesh
					geometry={nodes.Plane129_5.geometry}
					material={materials.glossy}
				/>
				<mesh
					geometry={nodes.Plane129_6.geometry}
					material={materials.mic}
				/>
				<mesh
					geometry={nodes.Plane129_7.geometry}
					material={materials.red}
				/>
				<mesh
					geometry={nodes.Plane129_8.geometry}
					material={materials.lens}
				/>
				<mesh
					geometry={nodes.Plane129_9.geometry}
					material={materials.glass}
				/>
			</group>
			<mesh
				geometry={nodes.CoffeeTable.geometry}
				material={materials["beech wood"]}
				position={[2.475, 0.1, 1.462]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.basketball.geometry}
				material={materials.Basketball}
				position={[-0.891, 0.1, -3.67]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
		</group>
	);
}

useGLTF.preload("/testroom-v1.glb");
